force-app/main/default/objects/Proxy_Settings__c/Proxy_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Proxy Settings</label>
</CustomObject>

force-app/main/default/objects/Proxy_Settings__c/fields/Use_Dev_Version__c.field-meta.xml
<CustomField>
    <fullName>Use_Dev_Version__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Dev Version</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CalloutProxyTest.cls
@IsTest
public with sharing class CalloutProxyTest {

    @IsTest
    private static void testProduction() {
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        request.setEndpoint('http://test.test');
        CalloutProxy.doCallout(request);
    }

    @IsTest
    private static void testDev() {
        insert new Proxy_Settings__c(
            Use_Dev_Version__c = true
        );

        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        request.setEndpoint('http://test.test');
        CalloutProxy.doCallout(request);
    }

}