force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Fees_Paid__c</fullName>
    <label>Fees Paid</label>
    <summarizedField>Repayment_Schedule__c.Fees_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Expected_Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Open_Ended_Loan__c</fullName>
    <label>Interest Expected (Open Ended Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid</label>
    <summarizedField>Repayment_Schedule__c.Interest_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Paid__c</fullName>
    <label>Late Repayment Fees Paid</label>
    <summarizedField>Repayment_Schedule__c.Late_Repayment_Fees_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Paid__c</fullName>
    <label>Principal Paid</label>
    <summarizedField>Repayment_Schedule__c.Principal_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Principal_Remaining__c</fullName>
    <formula>Principal_Expected__c - Principal_Paid__c - Principal_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Principal Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Recalculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Recalculation_Status__c</fullName>
    <defaultValue>&#39;Not Needed&#39;</defaultValue>
    <label>Recalculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Needed</fullName>
                <default>true</default>
                <label>Not Needed</label>
            </value>
            <value>
                <fullName>Pending Recalculation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Expected_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Expected_Principal_Balance__c</fullName>
    <label>Expected Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected_Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Open_Ended_Loan__c</fullName>
    <formula>Interest_Expected_On_Last_Paid_Date__c + (TODAY() - IF(ISNULL(Last_Action_Date__c), Loan__r.Disbursement_Date__c, Last_Action_Date__c)) * Principal_Remaining__c * Loan__r.Interest_Rate__c / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected (Open Ended Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <formula>if(Cancel_Late_Repayment_Fee__c, 0, if(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Fixed Fee&#39;, Late_Repayment_Fixed_Fee__c, if(OR(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal&#39;, TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal+Interest&#39;), Late_Repayment_Fees_On_Last_Paid_Date__c + Days_Since_Last_Paid_Date__c * Daily_Late_Repayment_Fees__c, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Paid__c</fullName>
    <label>Late Repayment Fees Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Principal_Balance__c</fullName>
    <description>The total remaining Principal Balance on Investment Level after the latest payment to this schedule.</description>
    <inlineHelpText>The total remaining Principal Balance on Investment Level after the latest payment to this schedule.</inlineHelpText>
    <label>Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Paid__c</fullName>
    <label>Principal Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Principal_Remaining__c</fullName>
    <formula>Principal_Expected__c - Principal_Paid__c - Principal_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Principal Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The amount within this transaction assigned to fees</description>
    <inlineHelpText>The amount within this transaction assigned to fees</inlineHelpText>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <description>The amount within this transaction assigned to interest</description>
    <inlineHelpText>The amount within this transaction assigned to interest</inlineHelpText>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Late_Repayment_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fee_Amount__c</fullName>
    <label>Late Repayment Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Principal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Principal_Amount__c</fullName>
    <description>The amount within this transaction assigned to principal</description>
    <inlineHelpText>The amount within this transaction assigned to principal</inlineHelpText>
    <label>Principal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Principal_Balance__c</fullName>
    <description>The total remaining Principal Balance on Investment level after this Transaction</description>
    <inlineHelpText>The total remaining Principal Balance on Investment level after this Transaction</inlineHelpText>
    <label>Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Repayment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment Schedule</label>
    <referenceTo>Repayment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanHealthCheckController.cls
public with sharing class LoanHealthCheckController {
    
    @AuraEnabled
    public static List<String> getLoanData(Id loanId) {
        // Check to see whether the caller has access to this information.
        if (!Repayment_Schedule__c.SObjectType.getDescribe().isAccessible()
            || !Transaction__c.SObjectType.getDescribe().isAccessible())
        {
            throw new AuraHandledException(System.Label.sfims.error_message_24);
        }

        Investment__c theLoan = [
            SELECT Principal_Remaining__c, Open_Ended_Loan__c, Status__c, Recalculation_Status__c,
                Interest_Expected_Open_Ended_Loan__c, Late_Repayment_Fees_Expected0__c,
            (
                SELECT Fees_Paid__c, Interest_Paid__c, Late_Repayment_Fees_Paid__c, Principal_Paid__c, 
                    Interest_Expected_Open_Ended_Loan__c, Late_Repayment_Fees_Expected0__c, 
                    Expected_Principal_Balance__c, Principal_Balance__c, Due_Date__c, Active__c
                FROM Repayment_Schedules__r
                ORDER BY Due_Date__c DESC
            ),
            (
                SELECT Fee_Amount__c, Interest_Amount__c, Late_Repayment_Fee_Amount__c, Principal_Amount__c,
                    Transaction_Date__c, Type__c, Status__c, Principal_Balance__c
                FROM Transactions__r
                ORDER BY Transaction_Date__c DESC, Name DESC
            )
            FROM Investment__c
            WHERE Id =: loanId
        ];

        return LoanHealthCheckController.getIssues(theLoan);

    }

    public static List<String> getIssues(Investment__c theLoan) {
        List<String> issues = new List<String>();
        List<Investment__c> loansToUpdate = new List<Investment__c>();
        switch on theLoan.Recalculation_Status__c {
            when 'Pending Recalculation' {
                issues.add(System.Label.sfims.health_check_1);
            }
            when 'In Progress' {
                issues.add(System.Label.sfims.health_check_2);
            }
            when 'Failed' {
                issues.add(System.Label.sfims.health_check_3);
            }
        } 
        
        Decimal feesPaid = 0;
        Decimal interestPaid = 0;
        Decimal lateRepaymentFeesPaid = 0;
        Decimal principalPaid = 0;
        Decimal interestExpected = 0;
        Decimal lateRepaymentFeesExpected = 0;
        Decimal feesAmount = 0;
        Decimal interestAmount = 0;
        Decimal lateRepaymentFeesAmount = 0;
        Decimal principalAmount = 0;
        
        Date dueDate;
        Repayment_Schedule__c lastRepaymentSchedule;
        List<Transaction__c> latePlannedDisbursementTansactions = new List<Transaction__c>();

        if (!theLoan.Repayment_Schedules__r.isEmpty()) {
            for (Repayment_Schedule__c rs : theLoan.Repayment_Schedules__r) {
                if (rs.Fees_Paid__c != null) feesPaid += rs.Fees_Paid__c;
                if (rs.Interest_Paid__c != null) interestPaid += rs.Interest_Paid__c;
                if (rs.Late_Repayment_Fees_Paid__c != null) lateRepaymentFeesPaid += rs.Late_Repayment_Fees_Paid__c;
                if (rs.Principal_Paid__c != null) principalPaid += rs.Principal_Paid__c;

                if (theLoan.Open_Ended_Loan__c) {
                    if (rs.Interest_Expected_Open_Ended_Loan__c != null) interestExpected += rs.Interest_Expected_Open_Ended_Loan__c;
                } else {
                    if (rs.Late_Repayment_Fees_Expected0__c != null) lateRepaymentFeesExpected += rs.Late_Repayment_Fees_Expected0__c;
                }

                if (rs.Active__c && dueDate == null) {
                    dueDate = rs.Due_Date__c;
                    lastRepaymentSchedule = rs;
                }
            }
        }

        Integer numberOfDisbursements = 0;
        Integer numberOfRepayments = 0;
        if (!theLoan.Transactions__r.isEmpty()) {
            for (Transaction__c tr : theLoan.Transactions__r) {
                switch on tr.Type__c {
                    when 'Repayment' {
                        if (tr.Fee_Amount__c != null) feesAmount += tr.Fee_Amount__c;
                        if (tr.Interest_Amount__c != null) interestAmount += tr.Interest_Amount__c;
                        if (tr.Late_Repayment_Fee_Amount__c != null) lateRepaymentFeesAmount += tr.Late_Repayment_Fee_Amount__c;
                        if (tr.Principal_Amount__c != null) principalAmount += tr.Principal_Amount__c;

                        numberOfRepayments++;
                    }
                    when 'Disbursement' {
                        if (tr.Status__c == 'Planned' && tr.Transaction_Date__c < System.today()) 
                            latePlannedDisbursementTansactions.add(tr);

                        numberOfDisbursements++;
                    }
                }
            }
        }

        if (!theLoan.Repayment_Schedules__r.isEmpty()) {
            if (theLoan.Open_Ended_Loan__c) {
                if (theLoan.Interest_Expected_Open_Ended_Loan__c != interestExpected.setScale(2)) {
                    theLoan.Interest_Expected_Open_Ended_Loan__c = interestExpected.setScale(2);
                    loansToUpdate.add(theLoan);
                }
            } else {
                if (theLoan.Late_Repayment_Fees_Expected0__c != lateRepaymentFeesExpected.setScale(2)) {
                    theLoan.Late_Repayment_Fees_Expected0__c = lateRepaymentFeesExpected.setScale(2);
                    loansToUpdate.add(theLoan);
                }  
            }
        }
        
        if (feesPaid != feesAmount) issues.add(generateErrorMessageWhenPaidSumsNotEqual(System.Label.sfims.amount_type_1, feesPaid, feesAmount));
        if (interestPaid != interestAmount) issues.add(generateErrorMessageWhenPaidSumsNotEqual(System.Label.sfims.amount_type_2, interestPaid, interestAmount));
        if (lateRepaymentFeesPaid != lateRepaymentFeesAmount) 
            issues.add(generateErrorMessageWhenPaidSumsNotEqual(System.Label.sfims.amount_type_3, lateRepaymentFeesPaid, lateRepaymentFeesAmount));
        if (principalPaid != principalAmount) issues.add(generateErrorMessageWhenPaidSumsNotEqual(System.Label.sfims.amount_type_4, principalPaid, principalAmount));

        if (!latePlannedDisbursementTansactions.isEmpty()) issues.add(System.Label.sfims.health_check_4);

        if (lastRepaymentSchedule != null) {
            if (lastRepaymentSchedule.Expected_Principal_Balance__c != null 
                && lastRepaymentSchedule.Expected_Principal_Balance__c.setScale(2) != 0) 
                issues.add(System.Label.sfims.health_check_5);
            
            if (lastRepaymentSchedule.Principal_Balance__c != null 
                && lastRepaymentSchedule.Principal_Balance__c.setScale(2) != theLoan.Principal_Remaining__c)
                issues.add(System.Label.sfims.health_check_6);
        }  
        if (!theLoan.Transactions__r.isEmpty()) {
            Transaction__c lastTransaction = theLoan.Transactions__r[0];
            if (theLoan.Status__c != 'Closed - Written Off' && lastTransaction.Principal_Balance__c != null 
                && lastTransaction.Principal_Balance__c.setScale(2) != theLoan.Principal_Remaining__c)
                issues.add(System.Label.sfims.health_check_7);
        }

        if (numberOfRepayments > 0 && numberOfDisbursements == 0) issues.add(System.Label.sfims.health_check_8);
        
        if (!loansToUpdate.isEmpty()) update loansToUpdate;

        return issues;
    } 

    public static String generateErrorMessageWhenPaidSumsNotEqual(String typeOfAmount, Decimal paidOnRepaymentSchedules, Decimal paidOnTransactions) {
        
        return System.Label.sfims.part_of_health_check_1 + ' ' + typeOfAmount + ' ' + System.Label.sfims.part_of_health_check_2 + 
            ' (' + currencySymbol + paidOnTransactions.setScale(2) + ') ' + System.Label.sfims.part_of_health_check_3 + ' ' + 
            System.Label.sfims.part_of_health_check_1 + ' ' + typeOfAmount + ' ' + System.Label.sfims.part_of_health_check_4 + 
            ' (' + currencySymbol + paidOnRepaymentSchedules.setScale(2) + ').';
    }

    public static String currencySymbol {
        get{
            if (currencySymbol == null) {
                String Iso = UserInfo.getDefaultCurrency();
                currencySymbol = 
                    ('USD' == Iso ? '$' : 
                    ('CAD' == Iso ? '$' : 
                    ('GBP' == Iso ? '£' : 
                    ('JPY' == Iso ? '¥' : 
                    ('KRW' == Iso ? '₩' : 
                    ('CNY' == Iso ? '元' : 
                    ('EUR' == Iso ? '€' : 
                    Iso)))))));
            }
            return currencySymbol;
        }
        set;
    }

}