force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Fees_Due__c.field-meta.xml
<CustomField>
    <fullName>Fees_Due__c</fullName>
    <label>Fees Due</label>
    <summarizedField>Repayment_Schedule__c.Fees_Due__c</summarizedField>
    <summaryFilterItems>
        <field>Repayment_Schedule__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Due__c.field-meta.xml
<CustomField>
    <fullName>Interest_Due__c</fullName>
    <label>Interest Due</label>
    <summarizedField>Repayment_Schedule__c.Interest_Due__c</summarizedField>
    <summaryFilterItems>
        <field>Repayment_Schedule__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Due__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Due__c</fullName>
    <label>Late Repayment Fees Due</label>
    <summarizedField>Repayment_Schedule__c.Late_Repayment_Fees_Due__c</summarizedField>
    <summaryFilterItems>
        <field>Repayment_Schedule__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Due__c.field-meta.xml
<CustomField>
    <fullName>Principal_Due__c</fullName>
    <label>Principal Due</label>
    <summarizedField>Repayment_Schedule__c.Principal_Due__c</summarizedField>
    <summaryFilterItems>
        <field>Repayment_Schedule__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <summarizedField>Repayment_Schedule__c.Principal_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Due__c.field-meta.xml
<CustomField>
    <fullName>Fees_Due__c</fullName>
    <label>Fees Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Due__c.field-meta.xml
<CustomField>
    <fullName>Interest_Due__c</fullName>
    <label>Interest Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Loan__r.Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Due__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Due__c</fullName>
    <label>Late Repayment Fees Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <formula>if(Cancel_Late_Repayment_Fee__c, 0, if(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Fixed Fee&#39;, Late_Repayment_Fixed_Fee__c, if(OR(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal&#39;, TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal+Interest&#39;), Late_Repayment_Fees_On_Last_Paid_Date__c + Days_Since_Last_Paid_Date__c * Daily_Late_Repayment_Fees__c, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Due__c.field-meta.xml
<CustomField>
    <fullName>Principal_Due__c</fullName>
    <label>Principal Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Due__c.field-meta.xml
<CustomField>
    <fullName>Total_Due__c</fullName>
    <formula>Fees_Due__c + Interest_Due__c + Late_Repayment_Fees_Due__c + Principal_Due__c + Interest_Bonus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvestmentsAccrualBatchController.cls
public with sharing class InvestmentsAccrualBatchController implements Database.Batchable<sObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, Principal_Expected__c, Interest_Expected0__c, Fees_Expected__c, Late_Repayment_Fees_Expected0__c, Principal_Due__c,
                Interest_Due__c, Fees_Due__c, Late_Repayment_Fees_Due__c, Status__c
            FROM Repayment_Schedule__c
            WHERE Loan__r.Status__c = 'Active' AND Due_Date__c < TODAY AND Total_Due__c = 0
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Repayment_Schedule__c> scope) {

        for (Repayment_Schedule__c rs : scope){
            
            rs.Principal_Due__c = rs.Principal_Expected__c;
            rs.Interest_Due__c = rs.Interest_Expected0__c;
            rs.Fees_Due__c = rs.Fees_Expected__c;
            rs.Late_Repayment_Fees_Due__c = rs.Late_Repayment_Fees_Expected0__c;

        }
        
        update scope;
        
    }

    public void finish(Database.BatchableContext BC) {

    }

}