force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Recalculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Recalculation_Status__c</fullName>
    <defaultValue>&#39;Not Needed&#39;</defaultValue>
    <label>Recalculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Needed</fullName>
                <default>true</default>
                <label>Not Needed</label>
            </value>
            <value>
                <fullName>Pending Recalculation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecalculationScheduler.cls
public with sharing class RecalculationScheduler implements Schedulable, Database.Stateful {
    String loanId;
    
    public RecalculationScheduler(String loanId) {
        this.loanId = loanId;
    }
    public void execute(SchedulableContext sc) {
        Investment__c theLoan = [
            SELECT Open_Ended_Loan__c, Recalculation_Status__c 
            FROM Investment__c 
            WHERE Id = :loanId
        ];

        if (theLoan.Recalculation_Status__c == 'Manual Recalculation') {
            theLoan.Recalculation_Status__c = 'Pending Recalculation';

            String result = TriggerHelper.runRecalculateLoanFromScratch(new List<Investment__c>{theLoan});
            if (result != null) RecalculateButtonController.finishWithError(theLoan, null, result);
        }
    }
}