force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Fees_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Fees_Remaining__c</fullName>
    <formula>Fees_Expected__c - Fees_Paid__c - Fees_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fees Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Fees_Written_Off__c</fullName>
    <description>Roll-up summary of Fees written off accross all repayment schedules</description>
    <label>Fees Written Off</label>
    <summarizedField>Repayment_Schedule__c.Fees_Written_Off__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Interest_Remaining__c</fullName>
    <formula>Interest_Expected0__c - Interest_Paid__c - Interest_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Interest_Written_Off__c</fullName>
    <description>Roll-up summary of Interest written off accross all repayment schedules</description>
    <label>Interest Written Off</label>
    <summarizedField>Repayment_Schedule__c.Interest_Written_Off__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Remaining__c</fullName>
    <formula>Late_Repayment_Fees_Expected0__c - Late_Repayment_Fees_Paid__c - Late_Repayment_Fees_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Written_Off__c</fullName>
    <label>Late Repayment Fees Written Off</label>
    <summarizedField>Repayment_Schedule__c.Late_Repayment_Fees_Written_Off__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Principal_Remaining__c</fullName>
    <formula>Principal_Expected__c - Principal_Paid__c - Principal_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Principal Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Principal_Written_Off__c</fullName>
    <description>Sum of all Principal amounts written off accross Repayment Schedules</description>
    <label>Principal Written Off</label>
    <summarizedField>Repayment_Schedule__c.Principal_Written_Off__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date the Loan Event occured</description>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Fees_Written_Off__c</fullName>
    <label>Fees Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Interest_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Interest_Written_Off__c</fullName>
    <label>Interest Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Late_Repayment_Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Written_Off__c</fullName>
    <label>Late Repayment Fees Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event_Type__c</fullName>
    <label>Loan Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Creation</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Interest Rate Change</fullName>
            </value>
            <value>
                <fullName>Interest Rollup Recalculation</fullName>
            </value>
            <value>
                <fullName>Closed (Written Off)</fullName>
            </value>
            <value>
                <fullName>Closed (Early Repayment)</fullName>
            </value>
            <value>
                <fullName>Closed (All Obligations met)</fullName>
            </value>
            <value>
                <fullName>Bullet Repayment</fullName>
            </value>
            <value>
                <fullName>Automatic Schedule Migration for Migrated Loan</fullName>
            </value>
            <value>
                <fullName>Fee Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Principal_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Principal_Written_Off__c</fullName>
    <label>Principal Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestLoanEarlyRepaymentButtonController.cls
@isTest
private class TestLoanEarlyRepaymentButtonController {

    @isTest static void test_loan_early_repayment() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-6), System.today().addMonths(-6));
        i.Status__c = 'Active';
        update i;
    
        Investment__c oldInvestment = [
            SELECT Id, Principal_Remaining__c, Interest_Remaining__c, Fees_Remaining__c, Late_Repayment_Fees_Remaining__c
            FROM Investment__c
            WHERE Id =: i.Id
        ];

        Map<String, Object> dataMap = new Map<String, Object>();
        dataMap.put('recordId', i.Id);
        dataMap.put('totalPrincipalWrittenOff', 0);
        dataMap.put('totalInterestWrittenOff', oldInvestment.Interest_Remaining__c);
        dataMap.put('totalFeesWrittenOff', oldInvestment.Fees_Remaining__c);
        dataMap.put('totalPenaltiesWrittenOff', oldInvestment.Late_Repayment_Fees_Remaining__c);
        dataMap.put('totalEarlyRepaymentAmount', oldInvestment.Principal_Remaining__c);
        dataMap.put('earlyRepaymentDate', System.today());

        Test.startTest();

        LoanEarlyRepaymentButtonController.loanPayOff(dataMap);

        Test.stopTest();

        Investment__c updatedInvestment = [
            SELECT Id, Status__c
            FROM Investment__c
            WHERE Id =: i.Id
        ];
        Loan_Event__c loanEvent = [
            SELECT Id, Event_Date__c, Fees_Written_Off__c, Interest_Written_Off__c, Late_Repayment_Fees_Written_Off__c, Principal_Written_Off__c
            FROM Loan_Event__c
            WHERE Investment__c =: i.Id AND Loan_Event_Type__c = 'Closed (Early Repayment)'
        ];

        System.assertEquals(oldInvestment.Fees_Remaining__c, loanEvent.Fees_Written_Off__c);
        System.assertEquals(oldInvestment.Interest_Remaining__c, loanEvent.Interest_Written_Off__c);
        System.assertEquals(oldInvestment.Late_Repayment_Fees_Remaining__c, loanEvent.Late_Repayment_Fees_Written_Off__c);
        System.assertEquals(0, loanEvent.Principal_Written_Off__c);
        System.assertEquals(System.today(), loanEvent.Event_Date__c);
        System.assertEquals('Closed - Early Repayment', updatedInvestment.Status__c);
    }
}