force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Capitalized_Amount__c.field-meta.xml
<CustomField>
    <fullName>Capitalized_Amount__c</fullName>
    <label>Capitalized Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Capitalized_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Capitalized_Fee_Amount__c</fullName>
    <label>Capitalized Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Day_Count_Convention__c.field-meta.xml
<CustomField>
    <fullName>Day_Count_Convention__c</fullName>
    <description>30/360 
This is a method that calculates interest based on assumed equal months (1/12th). 

Actual/365 
Calculate interest fees based on the number of days in the actual period. So if payments are monthly we charge between 28 and 31 days of interest, depending on the number of days in the month. 

Actual/365L 
Same as Actual/365 but for Leap years 366 days are used and not 365.</description>
    <label>Day Count Convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
                <default>true</default>
                <label>30/360</label>
            </value>
            <value>
                <fullName>Actual/365</fullName>
            </value>
            <value>
                <fullName>Actual/365L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Date__c</fullName>
    <description>The date on which the Loan is (expected to be) disbursed. From this day on, interest will be charged (if applicable)</description>
    <inlineHelpText>The date on which the Loan is (expected to be) disbursed. From this day on, interest will be charged (if applicable)</inlineHelpText>
    <label>Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/First_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date__c</fullName>
    <description>The date on which the first repayment for the loan is due. The rest of the loan schedule will also be based on this date.</description>
    <inlineHelpText>The date on which the first repayment for the loan is due. The rest of the loan schedule will also be based on this date.</inlineHelpText>
    <label>First Repayment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Grace_Periods__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Grace_Periods__c</fullName>
    <label>Number of Grace Periods</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Instalments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Instalments__c</fullName>
    <label>Number of Instalments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Repayment_Frequency_Unit__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency_Unit__c</fullName>
    <label>Repayment Frequency Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Expected__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Expected__c</fullName>
    <formula>if(TEXT(Setup_Fee__c) = &#39;Flat Amount&#39;, Flat_Amount__c, if(TEXT(Setup_Fee__c) = &#39;% of Disbursement Amount&#39;, if(AND(Setup_Fee_Cap__c &gt; 0, Setup_Fee_Cap__c &lt; Amount__c * Percent_of_Disbursement_Amount__c), Setup_Fee_Cap__c, Amount__c * Percent_of_Disbursement_Amount__c), 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Setup Fees Expected (Loan-based)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/First_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date__c</fullName>
    <label>First Repayment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Number_of_Grace_Periods__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Grace_Periods__c</fullName>
    <label>Number of Grace Periods</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Number_of_Instalments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Instalments__c</fullName>
    <label>Number of Instalments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Repayment_Frequency_Unit__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency_Unit__c</fullName>
    <label>Repayment Frequency Unit</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Repayment_Frequency_Unit__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency_Unit__c</fullName>
    <label>Repayment Frequency Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/CreateRemainingScheduleBatch.cls
global with sharing class CreateRemainingScheduleBatch implements Database.Batchable<SObject>, Database.Stateful {
    // this batch generates new schedules for the selected loan, based on repaying the full 'migrated outstanding capital'

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Number_of_Instalments__c, Repayment_Frequency__c, Repayment_Frequency_Unit__c, Amount__c,
                Number_of_Grace_Periods__c, Grace_Period_Type__c, Capitalized_Amount__c, Capitalized_Fee_Amount__c,
                Setup_Fee_Charging_Method__c, Setup_Fee_Expected__c, Disbursement_Date__c, First_Repayment_Date__c,
                Open_Ended_Loan__c, Interest_Rate__c, Day_Count_Convention__c, Variable_Interest_Spread__c,
                Loan_Product__r.Interest_Rate_Source__c, Loan_Product__r.Interest_Reference_Rate__c, Loan_Product__c,
                Loan_Product__r.Maximum_Interest_Bandwidth__c, Loan_Product__r.Minimum_Interest_Bandwidth__c, 
                Non_Working_Days_Rescheduling__c, Monitoring_Fee_Percentage__c, Migrated_Instalment_Amount__c, 
                Migrated_Next_First_Repayment_Date__c, Migrated_Outstanding_Capital__c, Migrated_Remaining_Grace_Periods__c
            FROM Investment__c
            WHERE Create_Remaining_Schedule__c = TRUE AND Open_Ended_Loan__c = FALSE
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Investment__c> scope) {
        // System.debug(scope[0]);
        Investment__c theLoan = scope[0];

        Savepoint sp = Database.setSavepoint();
        String errorMessage;
        try {
            // generate schedule
            List<Repayment_Schedule__c> rsToInsert = CreateRemainingScheduleBatch.createRepaymentSchedules(theLoan);
            try {
                DMLManager.insertAsUser(rsToInsert);
                
                // create a loan event
                Loan_Event__c le = new Loan_Event__c(
                    Event_Date__c = System.today(),
                    Investment__c = theLoan.Id,
                    Loan_Event_Type__c = 'Automatic Schedule Migration for Migrated Loan',
                    Loan_Product__c = theLoan.Loan_Product__c
                );
                
                try {
                    DMLManager.insertAsUser(new List<Loan_Event__c>{le});
                } catch(System.DmlException e) {
                    Database.rollback(sp);
                    errorMessage = System.Label.sfims.part_of_error_message_32 + ': ' + e.getDmlMessage(0);
                }
            } catch(System.DmlException e) {
                errorMessage = System.Label.sfims.part_of_error_message_33 + ': ' + e.getDmlMessage(0);
            }
        } catch(Exception e) {
            errorMessage = System.Label.sfims.part_of_error_message_34 + ': ' + e.getMessage();
        }
        
        // update the loan
        Investment__c inv = [
            SELECT Create_Remaining_Schedule__c, Errors_Creating_Remaining_Schedule__c
            FROM Investment__c
            WHERE Id = :theLoan.Id
        ];
        if (errorMessage != null) inv.Errors_Creating_Remaining_Schedule__c = errorMessage.abbreviate(255);
        inv.Create_Remaining_Schedule__c = false;
    
        DMLManager.updateAsSystem(new List<Investment__c>{inv});
    }

    global void finish(Database.BatchableContext BC) {

    }

    public static List<Repayment_Schedule__c> createRepaymentSchedules(Investment__c theLoan) {
        System.debug('CreateRemainingScheduleBatch.createRepaymentSchedules');

        // apply migrated parameters to the loan
        theLoan.Capitalized_Amount__c = theLoan.Migrated_Outstanding_Capital__c;

        Integer numberOfGracePeriods = 0;
        if (theLoan.Migrated_Remaining_Grace_Periods__c != null)  numberOfGracePeriods = theLoan.Migrated_Remaining_Grace_Periods__c.intValue();
        theLoan.Number_of_Grace_Periods__c = numberOfGracePeriods;
        
        // calculate the number of instalments based on migrated outstanding capital and migrated instalment amount
        Integer numberOfInstalments = Math.floor(theLoan.Migrated_Outstanding_Capital__c / theLoan.Migrated_Instalment_Amount__c).intValue() + 1;
        numberOfInstalments += numberOfGracePeriods;
        theLoan.Number_of_Instalments__c = numberOfInstalments;

        // determine so-called disbursement date
        theLoan.First_Repayment_Date__c = theLoan.Migrated_Next_First_Repayment_Date__c;
        Date startDate;
        switch on theLoan.Repayment_Frequency_Unit__c {
            when 'Days' {
                startDate = theLoan.First_Repayment_Date__c.addDays((-1*theLoan.Repayment_Frequency__c).intValue());
            }
            when 'Weeks' {
                startDate = theLoan.First_Repayment_Date__c.addDays((7*-1*theLoan.Repayment_Frequency__c).intValue());  
            }
            when 'Months' {
                startDate = theLoan.First_Repayment_Date__c.addMonths((-1*theLoan.Repayment_Frequency__c).intValue());
            }
            when 'Years' {
                startDate = theLoan.First_Repayment_Date__c.addYears((-1*theLoan.Repayment_Frequency__c).intValue());
            }
        }
        theLoan.Disbursement_Date__c = startDate;

        // generate future schedules
        return LoanScheduler.generateSchedule(theLoan, 0, 0, theLoan.Migrated_Instalment_Amount__c);   
    }
}