force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Calculation_Method__c</fullName>
    <description>No penalty - Won&#39;t charge penalties when a repayment is late
Overdue Principal * # of Late Days * Penalty Rate - it&#39;s the most common method, where the penalty rate is applied on the principal due late amount and the number of late days</description>
    <inlineHelpText>No penalty
Overdue Principal * # of Late Days * Penalty Rate : penalty rate applied on principal due late amount and number of late days
(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate : same but with overdue interest</inlineHelpText>
    <label>Late Repayment Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Penalty</fullName>
                <default>true</default>
                <label>No Penalty</label>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
                <label>Overdue Principal * # of Late Days * Penalty Rate</label>
            </value>
            <value>
                <fullName>Principal+Interest</fullName>
                <label>(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fixed_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fixed_Fee__c</fullName>
    <label>Late Repayment Fixed Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Total_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Remaining__c</fullName>
    <formula>Total_Expected__c - Total_Paid__c - Total_Amount_Written_Off1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Due_Date_with_Tolerance_Period__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_with_Tolerance_Period__c</fullName>
    <formula>Due_Date__c + IF(ISNULL(Loan__r.Late_Repayment_Tolerance_Period__c), 0, Loan__r.Late_Repayment_Tolerance_Period__c)</formula>
    <label>Due Date with Tolerance Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Remaining__c</fullName>
    <formula>Total_Expected__c - Total_Paid__c - Total_Amount_Written_Off__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PopulateLateRepaymentFixedFeeBatch.cls
public with sharing class PopulateLateRepaymentFixedFeeBatch implements Database.Batchable<sObject>, Database.Stateful {
    // this batch populates the Late Repayment Fixed Fees on the Repayment Shedule records for standard loans
    public Database.QueryLocator start(Database.BatchableContext BC) {
        Date entryDate = System.today();
        return Database.getQueryLocator([
            SELECT Late_Repayment_Fixed_Fee__c, Loan__r.Late_Repayment_Fixed_Fee__c
            FROM Repayment_Schedule__c
            WHERE Loan__r.Status__c = 'Active' AND Loan__r.Open_Ended_Loan__c = FALSE AND Active__c = TRUE 
                AND Loan__r.Late_Repayment_Calculation_Method__c = 'Fixed Fee' AND Late_Repayment_Fixed_Fee__c = NULL
                AND Due_Date_with_Tolerance_Period__c < :entryDate AND Total_Remaining__c > 0
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Repayment_Schedule__c> scope) {
        System.debug(scope);
        List<Repayment_Schedule__c> rsToUpdate = new List<Repayment_Schedule__c>(); 
        for (Repayment_Schedule__c rs : scope) { 
            rs.Late_Repayment_Fixed_Fee__c = rs.Loan__r.Late_Repayment_Fixed_Fee__c;
            rsToUpdate.add(rs);  
        }
        System.debug(rsToUpdate);
        if (!rsToUpdate.isEmpty()) {
            update rsToUpdate;
        }
    }

    public void finish(Database.BatchableContext BC) {

    }

}