force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Fees_Paid__c</fullName>
    <label>Fees Paid</label>
    <summarizedField>Repayment_Schedule__c.Fees_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Fees_Written_Off__c</fullName>
    <description>Roll-up summary of Fees written off accross all repayment schedules</description>
    <label>Fees Written Off</label>
    <summarizedField>Repayment_Schedule__c.Fees_Written_Off__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Monitoring_Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Fees_Expected__c</fullName>
    <label>Monitoring Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Monitoring_Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <summarizedField>Repayment_Schedule__c.Principal_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Paid__c</fullName>
    <label>Principal Paid</label>
    <summarizedField>Repayment_Schedule__c.Principal_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Principal_Written_Off__c</fullName>
    <description>Sum of all Principal amounts written off accross Repayment Schedules</description>
    <label>Principal Written Off</label>
    <summarizedField>Repayment_Schedule__c.Principal_Written_Off__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fees_Expected__c</fullName>
    <label>Setup Fees Expected (Schedule-based)</label>
    <summarizedField>Repayment_Schedule__c.Setup_Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Total_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected__c</fullName>
    <formula>Fees_Expected__c + Interest_Expected0__c + Late_Repayment_Fees_Expected0__c + Principal_Expected__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Balloon_Repayment_Period__c.field-meta.xml
<CustomField>
    <fullName>Balloon_Repayment_Period__c</fullName>
    <label>Balloon Repayment Period</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date the Loan Event occured</description>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Fees_Written_Off__c</fullName>
    <label>Fees Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event_Type__c</fullName>
    <label>Loan Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Creation</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Interest Rate Change</fullName>
            </value>
            <value>
                <fullName>Interest Rollup Recalculation</fullName>
            </value>
            <value>
                <fullName>Closed (Written Off)</fullName>
            </value>
            <value>
                <fullName>Closed (Early Repayment)</fullName>
            </value>
            <value>
                <fullName>Closed (All Obligations met)</fullName>
            </value>
            <value>
                <fullName>Bullet Repayment</fullName>
            </value>
            <value>
                <fullName>Automatic Schedule Migration for Migrated Loan</fullName>
            </value>
            <value>
                <fullName>Fee Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Principal_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Principal_Written_Off__c</fullName>
    <label>Principal Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Expected_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Expected_Principal_Balance__c</fullName>
    <label>Expected Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Fees_Written_Off__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of Fees Written Off for this Repayment Schedule</description>
    <label>Fees Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE then this is a migration record</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Monitoring_Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Fees_Expected__c</fullName>
    <label>Monitoring Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Paid__c</fullName>
    <label>Principal Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Written_Off__c.field-meta.xml
<CustomField>
    <fullName>Principal_Written_Off__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of Principal Written Off for this Repayment Schedule</description>
    <label>Principal Written Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Setup_Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fees_Expected__c</fullName>
    <label>Setup Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected__c</fullName>
    <formula>Fees_Expected__c + Interest_Expected0__c + Late_Repayment_Fees_Expected0__c + Principal_Expected__c + Interest_Bonus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BalloonRepaymentButtonController.cls
public class BalloonRepaymentButtonController {
    // this method is executed when the Schedule Balloon Repayment button is clicked
    @AuraEnabled
    public static Investment__c getRepaymentSchedules(Id loanId) {
        // Check to see whether the caller has access to this information.
        if (!Repayment_Schedule__c.SObjectType.getDescribe().isAccessible()
            || !Repayment_Schedule__c.SObjectType.getDescribe().isUpdateable()
            || !Repayment_Schedule__c.SObjectType.getDescribe().isDeletable())
        {
            throw new AuraHandledException(System.Label.sfims.error_message_1);
        }

        return [
            SELECT Open_Ended_Loan__c,
            (
                SELECT Due_Date__c, Fees_Expected__c, Fees_Paid__c, Fees_Written_Off__c, 
                    Principal_Expected__c, Principal_Paid__c, Principal_Written_Off__c,
                    Monitoring_Fees_Expected__c, Setup_Fees_Expected__c, Total_Expected__c
                FROM Repayment_Schedules__r
                WHERE Active__c = true AND Migration__c = false AND Due_Date__c > TODAY
                ORDER BY Due_Date__c
            )
            FROM Investment__c
            WHERE Id =: loanId    
        ];

    }

    // this method is executed when the Confirm button on the Schedule Balloon Repayment pop-up is clicked
    @AuraEnabled
    public static void scheduleBalloonRepayment(String schedulesString, Integer scheduleNumber, Id loanId) {
        List<Repayment_Schedule__c> schedules = (List<Repayment_Schedule__c>)JSON.deserialize(schedulesString, List<Repayment_Schedule__c>.class);
        
        Map<String, List<Repayment_Schedule__c>> schedulesMap = BalloonRepaymentButtonController.processRepaymentSchedules(schedules, scheduleNumber, loanId);

        // Savepoint sp = Database.setSavepoint();
        // try {
            if (!schedulesMap.get('schedulesToDelete').isEmpty()) DMLManager.deleteAsUser(schedulesMap.get('schedulesToDelete'));
            DMLManager.updateAsUser(schedulesMap.get('schedulesToUpdate'));

            Loan_Event__c le = new Loan_Event__c(
                Event_Date__c = System.today(),                     
                Investment__c = loanId,
                Loan_Event_Type__c = 'Bullet Repayment',
                Balloon_Repayment_Period__c = scheduleNumber
            );
            DMLManager.insertAsSystem(new List<Loan_Event__c>{le});
            
        // } catch(System.DmlException e) {
        //    Database.rollback(sp);
        //    throw new AuraHandledException(e.getDmlMessage(0));
        // }
    }

    public static Map<String, List<Repayment_Schedule__c>> processRepaymentSchedules(List<Repayment_Schedule__c> schedules, Integer scheduleNumber, Id loanId) {
        List<Repayment_Schedule__c> schedulesToDelete = new List<Repayment_Schedule__c>();
        List<Repayment_Schedule__c> schedulesToUpdate = new List<Repayment_Schedule__c>();
        
        Decimal principalExpected = 0;
        Decimal setupFeesExpected = 0;
        Decimal monitoringFeeExpected = 0;
        Decimal principalPaid = 0;
        Decimal feesPaid = 0;
        Decimal principalWrittenOff = 0;
        Decimal feesWrittenOff = 0;
        
        Repayment_Schedule__c schedule = new Repayment_Schedule__c();
        for (Integer i = scheduleNumber + 1; i < schedules.size(); i++) {
            schedule = schedules[i];
            
            principalExpected += schedule.Principal_Expected__c;
            setupFeesExpected += schedule.Setup_Fees_Expected__c;
            monitoringFeeExpected += schedule.Monitoring_Fees_Expected__c;

            principalPaid += schedule.Principal_Paid__c;
            feesPaid += schedule.Fees_Paid__c;

            principalWrittenOff += schedule.Principal_Written_Off__c;
            feesWrittenOff += schedule.Fees_Written_Off__c;

            schedulesToDelete.add(schedule);
        }
        
        schedule = schedules[scheduleNumber];
        schedule.Principal_Expected__c += principalExpected;
        schedule.Fees_Expected__c += setupFeesExpected + monitoringFeeExpected;
        schedule.Setup_Fees_Expected__c += setupFeesExpected;
        schedule.Monitoring_Fees_Expected__c += monitoringFeeExpected;
        schedule.Principal_Paid__c += principalPaid;
        schedule.Fees_Paid__c += feesPaid;
        schedule.Principal_Written_Off__c += principalWrittenOff;
        schedule.Fees_Written_Off__c += feesWrittenOff;

        schedule.Expected_Principal_Balance__c = 0;
        schedulesToUpdate.add(schedule);

        Map<String, List<Repayment_Schedule__c>> returnMap = new Map<String, List<Repayment_Schedule__c>>();
        returnMap.put('schedulesToUpdate', schedulesToUpdate);
        returnMap.put('schedulesToDelete', schedulesToDelete);
        
        return returnMap;

    }
}