force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>A Security is an agreement made by the borrower as protection in case he or she defaults on the repayment. It can be e.g. another person (guarantor) or a collateral like a house or a car.</description>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Security__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Investment that this Security backs up</description>
    <inlineHelpText>The Investment that this Security backs up</inlineHelpText>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Securities</relationshipLabel>
    <relationshipName>Securities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Security__c/recordTypes/Collateral.recordType-meta.xml
<RecordType>
    <fullName>Collateral</fullName>
    <active>true</active>
    <description>An collateral asset for this Security.</description>
    <label>Collateral</label>
</RecordType>

force-app/main/default/objects/Security__c/recordTypes/Guarantor.recordType-meta.xml
<RecordType>
    <fullName>Guarantor</fullName>
    <active>true</active>
    <description>An institution or person is the guarantor for this Security</description>
    <label>Guarantor</label>
</RecordType>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Utility.cls
public with sharing class Utility {
    public static Boolean currentUserIsAdmin {
        get {
            if (currentUserIsAdmin == null){
                List<Profile> adminProfiles = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
                if (!adminProfiles.isEmpty() && UserInfo.getProfileId() == adminProfiles[0].Id) currentUserIsAdmin = true;
                else currentUserIsAdmin = false;        
            }
            return currentUserIsAdmin;
        }
        set;
    }

    public static Id loanRecordTypeId {
        get {
            if (loanRecordTypeId == null){
                loanRecordTypeId = Schema.Sobjecttype.Investment__c.getRecordTypeInfosByName().get('Loan').getRecordTypeId();            
            }
            return loanRecordTypeId;
        }
        set;
    }

    // this variable is used for the deletion metods of the LoanEventTrigger
    public static List<Transaction__c> transactionsToDelete {
        get {
            if (transactionsToDelete == null){
                transactionsToDelete = new List<Transaction__c>();            
            }
            return transactionsToDelete;
        }
        set;
    }

    // this variable is used for the deletion metods of the LoanEventTrigger
    public static List<Investment__c> loansToRecalculate {
        get {
            if (loansToRecalculate == null){
                loansToRecalculate = new List<Investment__c>();            
            }
            return loansToRecalculate;
        }
        set;
    }

    public static Boolean bypassMilestoneHistoryTrigger {
        get {
            if (bypassMilestoneHistoryTrigger == null) bypassMilestoneHistoryTrigger = false;
            return bypassMilestoneHistoryTrigger;
        }
        set;
    }

    public static Boolean bypassLoanEventTrigger {
        get {
            if (bypassLoanEventTrigger == null) bypassLoanEventTrigger = false;
            return bypassLoanEventTrigger;
        }
        set;
    }

    public static Boolean executeFromDeleteMethodOfInvestmentTrigger {
        get {
            if (executeFromDeleteMethodOfInvestmentTrigger == null) executeFromDeleteMethodOfInvestmentTrigger = false;
            return executeFromDeleteMethodOfInvestmentTrigger;
        }
        set;
    }

    public static Id businessHoursId {
        get {
            if (businessHoursId == null) businessHoursId = [SELECT Id FROM BusinessHours WHERE IsDefault = true].Id;
            return businessHoursId;
        }
        set;        
    }

    public static Id guaranteeRecordTypeId {
        get {
            if (guaranteeRecordTypeId == null){
                guaranteeRecordTypeId = Schema.Sobjecttype.Security__c.getRecordTypeInfosByName().get('Guarantor').getRecordTypeId();            
            }
            return guaranteeRecordTypeId;
        }
        set;
    }

    public static Id collateralRecordTypeId {
        get {
            if (collateralRecordTypeId == null){
                collateralRecordTypeId = Schema.Sobjecttype.Security__c.getRecordTypeInfosByName().get('Collateral').getRecordTypeId();            
            }
            return collateralRecordTypeId;
        }
        set;
    }

    public static Decimal InstalmentAmount { get; set; }

    public class FieldSetWrapper {

        public String Label {get;set;}
        public List<String> Fields {get;set;}

        public FieldSetWrapper() {
        
        }
    }
}