force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Interest_Expected_Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Open_Ended_Loan__c</fullName>
    <label>Interest Expected (Open Ended Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Days_Since_Last_Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Paid_Date__c</fullName>
    <formula>IF(
    AND(
        NOT(ISNULL(Last_Paid_Date__c)), 
        Last_Paid_Date__c &gt; IF(Loan__r.Open_Ended_Loan__c, Loan__r.Disbursement_Date__c, Due_Date_with_Tolerance_Period__c), 
        Last_Paid_Date__c &lt;= TODAY()
    ), 
    TODAY() - Last_Paid_Date__c, 
    IF(IF(Loan__r.Open_Ended_Loan__c, Loan__r.Disbursement_Date__c, Due_Date_with_Tolerance_Period__c) &lt;= TODAY(), 
        TODAY() - IF(Loan__r.Open_Ended_Loan__c, Loan__r.Disbursement_Date__c, Due_Date_with_Tolerance_Period__c), 
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Paid Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Due_Date_with_Tolerance_Period__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_with_Tolerance_Period__c</fullName>
    <formula>Due_Date__c + IF(ISNULL(Loan__r.Late_Repayment_Tolerance_Period__c), 0, Loan__r.Late_Repayment_Tolerance_Period__c)</formula>
    <label>Due Date with Tolerance Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected_Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Open_Ended_Loan__c</fullName>
    <formula>Interest_Expected_On_Last_Paid_Date__c + (TODAY() - IF(ISNULL(Last_Action_Date__c), Loan__r.Disbursement_Date__c, Last_Action_Date__c)) * Principal_Remaining__c * Loan__r.Interest_Rate__c / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected (Open Ended Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <formula>if(Cancel_Late_Repayment_Fee__c, 0, if(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Fixed Fee&#39;, Late_Repayment_Fixed_Fee__c, if(OR(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal&#39;, TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal+Interest&#39;), Late_Repayment_Fees_On_Last_Paid_Date__c + Days_Since_Last_Paid_Date__c * Daily_Late_Repayment_Fees__c, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PopulateLoanExpectedAmountBatch.cls
public with sharing class PopulateLoanExpectedAmountBatch implements Database.Batchable<sObject>, Database.Stateful {
    // this batch populates the Late Repayment Fees Expected amount for standard loans
    // and the Interest Expected amount for open ended loans on the Investment object
    // it's an alternative to roll-up summary fields that we cannot use due to the function TODAY
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Open_Ended_Loan__c, Late_Repayment_Fees_Expected0__c, Interest_Expected_Open_Ended_Loan__c,
            (
                SELECT Late_Repayment_Fees_Expected0__c, Interest_Expected_Open_Ended_Loan__c
                FROM Repayment_Schedules__r
                WHERE Active__c = true 
                AND ((Due_Date_with_Tolerance_Period__c = null AND Days_Since_Last_Paid_Date__c > 0) OR Due_Date_with_Tolerance_Period__c < TODAY)
            )
            FROM Investment__c
            WHERE Status__c = 'Active'
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Investment__c> scope) {
        System.debug(scope);
        List<Investment__c> investmentsToUpdate = new List<Investment__c>(); 
        for (Investment__c i : scope) {
            if (!i.Repayment_Schedules__r.isEmpty()) {
                if (i.Open_Ended_Loan__c) {
                    i.Interest_Expected_Open_Ended_Loan__c = i.Repayment_Schedules__r[0].Interest_Expected_Open_Ended_Loan__c;
                    investmentsToUpdate.add(i);
                } else {
                    Decimal lateRepaymentFeesExpected = 0;
                    for (Repayment_Schedule__c rs : i.Repayment_Schedules__r) {
                        if (rs.Late_Repayment_Fees_Expected0__c != null) lateRepaymentFeesExpected += rs.Late_Repayment_Fees_Expected0__c;
                    } 
                    i.Late_Repayment_Fees_Expected0__c = lateRepaymentFeesExpected;
                    investmentsToUpdate.add(i);
                }
            }
        }
        System.debug(investmentsToUpdate);
        if (!investmentsToUpdate.isEmpty()) {
            update investmentsToUpdate;
        }
    }

    public void finish(Database.BatchableContext BC) {

    }

}