force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid__c</fullName>
    <label>Interest Paid</label>
    <summarizedField>Repayment_Schedule__c.Interest_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <summarizedField>Repayment_Schedule__c.Principal_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Paid__c</fullName>
    <label>Principal Paid</label>
    <summarizedField>Repayment_Schedule__c.Principal_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Recalculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Recalculation_Status__c</fullName>
    <defaultValue>&#39;Not Needed&#39;</defaultValue>
    <label>Recalculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Needed</fullName>
                <default>true</default>
                <label>Not Needed</label>
            </value>
            <value>
                <fullName>Pending Recalculation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Loan__r.Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Paid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Paid__c</fullName>
    <label>Principal Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Repayment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment Schedule</label>
    <referenceTo>Repayment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestRecalculateButtonController.cls
@isTest
private class TestRecalculateButtonController {
    @isTest static void test_recalculate_open_ended_loan_on_create(){
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a new loan
        Investment__c i = TestUtils.createNewScheduledOpenEndedLoan(System.today().addMonths(-1), 100);
        i.Loan_Product__c = lp.Id;
        i.Disbursement_Method__c = 'Full disbursement at start';
        update i;

        // add a disbursement
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addMonths(-1));
        DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');

        // add a repayment
        Transaction__c t2 = TestUtils.createNewTransaction(i.Id, i.Amount__c/10, 'Repayment');
        insert t2;

        List<Repayment_Schedule__c> expectedRS = [
            SELECT Principal_Expected__c, Interest_Expected0__c, Principal_Paid__c, Interest_Paid__c, Active__c
            FROM Repayment_Schedule__c
            WHERE Loan__c = :i.Id
        ];
        System.assertEquals(1, expectedRS.size());

        delete [SELECT Id FROM Repayment_Schedule__c WHERE Loan__c = :i.Id];

        // pefrorm test
        RecalculateButtonController.recalculateOpenEndedLoan(i.Id);

        Investment__c result = [
            SELECT Recalculation_Status__c
            FROM Investment__c
            WHERE Id = :i.Id
        ];

        List<Repayment_Schedule__c> actualRS = [
            SELECT Principal_Expected__c, Interest_Expected0__c, Principal_Paid__c, Interest_Paid__c, Active__c
            FROM Repayment_Schedule__c
            WHERE Loan__c = :i.Id
            ORDER BY Due_Date__c ASC
        ];

        // check results
        System.assertEquals('Done', result.Recalculation_Status__c);
        System.assertEquals(expectedRS.size(), actualRS.size());
        System.assertEquals(expectedRS[0].Principal_Expected__c.setscale(2), actualRS[0].Principal_Expected__c.setscale(2));
        System.assertEquals(expectedRS[0].Interest_Expected0__c.setscale(2), actualRS[0].Interest_Expected0__c.setscale(2));
        System.assertEquals(expectedRS[0].Principal_Paid__c.setscale(2), actualRS[0].Principal_Paid__c.setscale(2));
        System.assertEquals(expectedRS[0].Interest_Paid__c.setscale(2), actualRS[0].Interest_Paid__c.setscale(2));
    }
    
    @isTest static void test_recalculate_open_ended_loan_on_delete(){
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a new loan
        Investment__c i = TestUtils.createNewScheduledOpenEndedLoan(System.today().addMonths(-1), 100);
        i.Loan_Product__c = lp.Id;
        i.Disbursement_Method__c = 'Full disbursement at start';
        update i;

        // add a disbursement
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addMonths(-1));
        DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');

        // add a repayment
        Transaction__c t2 = TestUtils.createNewTransaction(i.Id, i.Amount__c/10, 'Repayment');
        insert t2;

        // delete transactions
        delete [SELECT Id FROM Transaction__c WHERE Investment__c = :i.Id];
        
        // pefrorm test
        RecalculateButtonController.recalculateOpenEndedLoan(i.Id);

        Investment__c result = [
            SELECT Status__c, Recalculation_Status__c
            FROM Investment__c
            WHERE Id = :i.Id
        ];

        // check results
        System.assertEquals('Inactive', result.Status__c);
        System.assertEquals('Not Needed', result.Recalculation_Status__c);
    }

    @isTest static void test_recalculation_scheduler(){
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a new loan
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-2), System.today().addMonths(-1));
        i.Loan_Product__c = lp.Id;
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;
        // add a disbursement
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today().addMonths(-2));
        DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');

        // add a repayment
        Transaction__c t2 = TestUtils.createNewTransaction(i.Id, i.Amount__c/12, 'Repayment', System.today().addMonths(-1));
        insert t2;
        
        Test.startTest();
        RecalculateButtonController.runRecalculationScheduler(JSON.serialize(i));
        System.assert([SELECT COUNT() FROM CronTrigger] > 0, 'A job should be scheduled');
        Test.stopTest();

    }

    @isTest static void test_get_loan_data_and_process_loan_event(){
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a new loan
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-2), System.today().addMonths(-1));
        i.Loan_Product__c = lp.Id;
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;
        // add a disbursement
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today().addMonths(-2));
        DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');
        
        Map<String, String> resultMap = RecalculateButtonController.getLoanData(i.Id);
        System.assert(resultMap.containsKey('loan'));
        System.assert(resultMap.containsKey('loanEvents'));

        Investment__c theLoan = (Investment__c)JSON.deserialize(resultMap.get('loan'), Investment__c.class);
        List<Loan_Event__c> loanEvents = (List<Loan_Event__c>)JSON.deserialize(resultMap.get('loanEvents'), List<Loan_Event__c>.class);
        System.debug(loanEvents.size());
        
        Map<String, String> resultMap2 = RecalculateButtonController.processLoanEvent(resultMap.get('loan'), resultMap.get('loanEvents'), 0, null, 0, RecalculateButtonController.runRecalculationScheduler(JSON.serialize(i)));
        System.debug(resultMap2);
        System.assert(resultMap2.containsKey('eventDate'));
        System.assert(resultMap2.containsKey('index'));
        System.assertEquals(loanEvents[0].Event_Date__c, Date.valueOf(resultMap2.get('eventDate')));
        System.assertEquals(1, Integer.valueOf(resultMap2.get('index')));
    }

    @isTest static void test_run_recalculation_without_loan_events(){
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a new loan
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-2), System.today().addMonths(-1));
        i.Loan_Product__c = lp.Id;
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;
        
        Map<String, String> resultMap = RecalculateButtonController.getLoanData(i.Id);
        System.assert(resultMap.containsKey('loan'));
        System.assert(!resultMap.containsKey('loanEvents'));
        
        RecalculateButtonController.runRecalculationWithoutLoanEvents(resultMap.get('loan'));
        
        Investment__c result = [
            SELECT Status__c, Recalculation_Status__c
            FROM Investment__c
            WHERE Id = :i.Id
        ];

        System.assertEquals('Inactive', result.Status__c);
        System.assertEquals('Not Needed', result.Recalculation_Status__c);
    }
}