force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Approval Required</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Pending Approval of the Previous Event</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date the Loan Event occured</description>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event_Type__c</fullName>
    <label>Loan Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Creation</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Interest Rate Change</fullName>
            </value>
            <value>
                <fullName>Interest Rollup Recalculation</fullName>
            </value>
            <value>
                <fullName>Closed (Written Off)</fullName>
            </value>
            <value>
                <fullName>Closed (Early Repayment)</fullName>
            </value>
            <value>
                <fullName>Closed (All Obligations met)</fullName>
            </value>
            <value>
                <fullName>Bullet Repayment</fullName>
            </value>
            <value>
                <fullName>Automatic Schedule Migration for Migrated Loan</fullName>
            </value>
            <value>
                <fullName>Fee Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event_Detail__c/Loan_Event_Detail__c.object-meta.xml
<CustomObject>
    <description>This object describes details of loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event Detail</label>
    <nameField>
        <displayFormat>LED-{00000000}</displayFormat>
        <label>Loan Event Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Event Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event_Detail__c/fields/Cancel_Late_Repayment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Late_Repayment_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancel Late Repayment Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Event_Detail__c/fields/Loan_Event__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event__c</fullName>
    <label>Loan Event</label>
    <referenceTo>Loan_Event__c</referenceTo>
    <relationshipLabel>Loan Event Details</relationshipLabel>
    <relationshipName>Loan_Event_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Cancel_Late_Repayment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Late_Repayment_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancel Late Repayment Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <formula>if(Cancel_Late_Repayment_Fee__c, 0, if(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Fixed Fee&#39;, Late_Repayment_Fixed_Fee__c, if(OR(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal&#39;, TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal+Interest&#39;), Late_Repayment_Fees_On_Last_Paid_Date__c + Days_Since_Last_Paid_Date__c * Daily_Late_Repayment_Fees__c, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CancelLateRepaymentFeeButtonController.cls
public with sharing class CancelLateRepaymentFeeButtonController {
    
    // this method is executed when the Disburse Loan button is clicked
    @AuraEnabled
    public static String cancelLateRepaymentFee(Id rsId) {
        // Check to see whether the caller has access to this information.
        if (!Repayment_Schedule__c.SObjectType.getDescribe().isAccessible()
            || !Loan_Event__c.SObjectType.getDescribe().isCreateable())
        {
            throw new AuraHandledException(System.Label.sfims.error_message_60);
        }
        
        Repayment_Schedule__c rs = [
            SELECT Due_Date__c, Late_Repayment_Fees_Expected0__c, Loan__c, Loan__r.Loan_Product__c, Cancel_Late_Repayment_Fee__c, Loan__r.Open_Ended_Loan__c
            FROM Repayment_Schedule__c
            WHERE Id =: rsId
        ];

        if (rs.Loan__r.Open_Ended_Loan__c) throw new AuraHandledException(System.Label.sfims.error_message_61);
        if (rs.Cancel_Late_Repayment_Fee__c) throw new AuraHandledException(System.Label.sfims.error_message_62);
        if (rs.Late_Repayment_Fees_Expected0__c <= 0) throw new AuraHandledException(System.Label.sfims.error_message_63);
        
        //-----Check if this button has been already clicked and this action is pending approval-----
        List<Loan_Event_Detail__c> leds = [
            SELECT Id, Name
            FROM Loan_Event_Detail__c
            WHERE Loan_Event__r.Investment__c = :rs.Loan__c AND Loan_Event__r.Loan_Event_Type__c = 'Fee Cancelled'
                AND Loan_Event__r.Approval_Status__c = 'Pending Approval' AND Due_Date__c = :rs.Due_Date__c
            LIMIT 1
        ];

        if (leds.isEmpty()) {
            //-----Create a new Loan Event record-----
            Loan_Event__c loanEvent = new Loan_Event__c(
                Event_Date__c = System.today(),
                Loan_Event_Type__c = 'Fee Cancelled',
                Investment__c = rs.Loan__c,
                Loan_Product__c = rs.Loan__r.Loan_Product__c,
                Approval_Status__c = 'Pending Approval'
            );
            DMLManager.insertAsSystem(new List<SObject>{loanEvent});

            //-----Create a new Loan Event Detail record-----
            Loan_Event_Detail__c detail = new Loan_Event_Detail__c(
                Loan_Event__c = loanEvent.Id,
                Cancel_Late_Repayment_Fee__c = true,
                Due_Date__c = rs.Due_Date__c
            );
            DMLManager.insertAsSystem(new List<SObject>{detail});

            //-----Submit for Approval-----
            Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
            request.setObjectId(loanEvent.Id);
            request.setSubmitterId(UserInfo.getUserId());
            
            Approval.ProcessResult result = Approval.process(request, false);
            if (result.isSuccess()) {
                System.debug('success');
                return System.Label.sfims.success_message_2;
            } else {
                System.debug(result.getErrors()[0].getMessage());
                if (result.getErrors()[0].getMessage().contains(System.Label.sfims.error_message_59)) {
                    loanEvent.Approval_Status__c = 'No Approval Required';
                    DMLManager.updateAsSystem(new List<SObject>{loanEvent});
                    return System.Label.sfims.success_message_1;
                } else {
                    throw new AuraHandledException(result.getErrors()[0].getMessage());
                }
            }    
        } else {
            throw new AuraHandledException(System.Label.sfims.error_message_64);
        }    
    }
}