force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Total_Collateral__c.field-meta.xml
<CustomField>
    <fullName>Total_Collateral__c</fullName>
    <description>The total Collateral for this Loan</description>
    <inlineHelpText>The total Collateral for this Loan</inlineHelpText>
    <label>Total Collateral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Total_Guarantee__c.field-meta.xml
<CustomField>
    <fullName>Total_Guarantee__c</fullName>
    <description>The sum of all guarantees for this loan</description>
    <inlineHelpText>The sum of all guarantees for this loan</inlineHelpText>
    <label>Total Guarantee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>A Security is an agreement made by the borrower as protection in case he or she defaults on the repayment. It can be e.g. another person (guarantor) or a collateral like a house or a car.</description>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Security__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The amount/value of the Security</description>
    <inlineHelpText>The amount/value of the Security</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Security__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Investment that this Security backs up</description>
    <inlineHelpText>The Investment that this Security backs up</inlineHelpText>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Securities</relationshipLabel>
    <relationshipName>Securities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Security__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the security. Only securites with status &#39;Confirmed&#39; will be counted as active Securities</description>
    <inlineHelpText>The status of the security. Only securites with status &#39;Confirmed&#39; will be counted as active Securities</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestSecurityTrigger.cls
@isTest
private class TestSecurityTrigger {
    @isTest static void test_populate_investment_fields() {
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a new loan
        Investment__c i1 = TestUtils.createNewScheduledLoan();
        i1.Loan_Product__c = lp.Id;
        i1.Disbursement_Method__c = 'Full disbursement at start';
        update i1;

        // create securities
        Security__c s1 = TestUtils.createCollateral(i1.Id);
        Security__c s2 = TestUtils.createGuarantee(i1.Id);
        insert new List<Security__c>{ s1, s2 };

        Investment__c result = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i1.Id
        ];
        
        // check results
        System.assertEquals(s1.Amount__c, result.Total_Collateral__c);
        System.assertEquals(s2.Amount__c, result.Total_Guarantee__c);

        // create a new loan
        Investment__c i2 = TestUtils.createNewScheduledLoan();
        i2.Loan_Product__c = lp.Id;
        i2.Disbursement_Method__c = 'Full disbursement at start';
        update i2;

        //update securities
        s1.Amount__c = 500;
        s2.Investment__c = i2.Id;
        update new List<Security__c>{ s1, s2 };

        Investment__c result2 = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i1.Id
        ];

        Investment__c result3 = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i2.Id
        ];
        
        // check results
        System.assertEquals(s1.Amount__c, result2.Total_Collateral__c);
        System.assertEquals(0, result2.Total_Guarantee__c);
        System.assertEquals(null, result3.Total_Collateral__c);
        System.assertEquals(s2.Amount__c, result3.Total_Guarantee__c);
        
        // change recordtype
        s1.RecordTypeId = Utility.guaranteeRecordTypeId;
        update s1;

        Investment__c result4 = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i1.Id
        ];

        // check results
        System.assertEquals(0, result4.Total_Collateral__c);
        System.assertEquals(s1.Amount__c, result4.Total_Guarantee__c);
        
        // change status
        s1.Status__c = 'Requested';
        update s1;

        Investment__c result5 = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i1.Id
        ];

        // check results
        System.assertEquals(0, result5.Total_Collateral__c);
        System.assertEquals(0, result5.Total_Guarantee__c);

        // return status
        s1.Status__c = 'Confirmed';
        update s1;

        Investment__c result6 = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i1.Id
        ];

        // check results
        System.assertEquals(0, result6.Total_Collateral__c);
        System.assertEquals(s1.Amount__c, result6.Total_Guarantee__c);

        // delete a security
        delete s1;

        Investment__c result7 = [
            SELECT Total_Collateral__c, Total_Guarantee__c
            FROM Investment__c
            WHERE Id = :i1.Id
        ];

        // check results
        System.assertEquals(0, result7.Total_Collateral__c);
        System.assertEquals(0, result7.Total_Guarantee__c);
    }
}