force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Recalculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Recalculation_Status__c</fullName>
    <defaultValue>&#39;Not Needed&#39;</defaultValue>
    <label>Recalculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Needed</fullName>
                <default>true</default>
                <label>Not Needed</label>
            </value>
            <value>
                <fullName>Pending Recalculation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of transaction</description>
    <inlineHelpText>Type of transaction</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Disbursement Correction</fullName>
            </value>
            <value>
                <fullName>Repayment Correction</fullName>
            </value>
            <value>
                <fullName>Fee Correction</fullName>
            </value>
            <value>
                <fullName>Fund Drawdown</fullName>
            </value>
            <value>
                <fullName>Fund Repayment</fullName>
            </value>
            <value>
                <fullName>Schedule (Not Due)</fullName>
            </value>
            <value>
                <fullName>Schedule (Late)</fullName>
            </value>
            <value>
                <fullName>Schedule (Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid (Late))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionTriggerHandler.cls
/**
 * @description         This is the trigger handler for the Transaction__c sObject. 
 * @author              Guy Clairbois
 */
public with sharing class TransactionTriggerHandler {

    public static Boolean bypassProcessTransactions = false;

    /**
     * @description         Automatically create/update 1 or more Transaction__c based on the VF_Transaction__c
     */
    public void processTransactions(Map<Id,Transaction__c> newTransactionsMap, Map<Id,Transaction__c> oldTransactionsMap){
        if (TransactionTriggerHandler.bypassProcessTransactions) return;

        // we do an entire loan recalculation when a transaction changes, because it's nearly impossible to predict which schedules will be hit and which not
        // collect the loan ids
        Set<Id> loanIds = new Set<Id>();

        // handle the delete scenario (just make sure the calculation is retriggered)
        if(newTransactionsMap == null) newTransactionsMap = oldTransactionsMap;
        
        for(Transaction__c t : newTransactionsMap.values()){
            if((t.Type__c == 'Repayment' || t.Type__c == 'Disbursement') && t.Investment__c != null && !transactionsInRecalculation.contains(t.Id)){
                loanIds.add(t.Investment__c);
                transactionsInRecalculation.add(t.Id);
            }
        }
        Set<Id> standardLoanIds = new Set<Id>();
        List<Investment__c> openEndedLoans = new List<Investment__c>();
        if (!loanIds.isEmpty()) {
            for (Investment__c theLoan : [SELECT Open_Ended_Loan__c, Recalculation_Status__c FROM Investment__c WHERE Id IN :loanIds]) {
                if (theLoan.Open_Ended_Loan__c) openEndedLoans.add(theLoan);
                else standardLoanIds.add(theLoan.Id);
            }
        }
        if (openEndedLoans.size() == 1) {
            Map<String, String> resultMap = RecalculateOpenEndedLoan.processOpenEndedLoan(openEndedLoans[0].Id);
            if (resultMap.containsKey('error')) {
                
                for (Transaction__c temp : newTransactionsMap.values()) {
                    temp.addError(System.Label.sfims.part_of_error_message_7 + ': ' + resultMap.get('error'));
                }
            }
        } else if (openEndedLoans.size() > 1) {
            for (Investment__c inv : openEndedLoans) {
                inv.Recalculation_Status__c = 'Pending Recalculation';
            }    
                
            String result = TriggerHelper.runRecalculateLoanFromScratch(openEndedLoans); 
            if (result != null) {
                for (Transaction__c temp : newTransactionsMap.values()) {
                    temp.addError(result);
                }
            }
        }

        if(!standardLoanIds.isEmpty()) LoanTransactionProcessor.processLoanTransactions(standardLoanIds);
    }

    public static Set<Id> transactionsInRecalculation {
        get{
            if(transactionsInRecalculation == null) transactionsInRecalculation = new Set<Id>();
            return transactionsInRecalculation;
         }
        set;
    }

}