force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <summarizedField>Repayment_Schedule__c.Principal_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Balloon_Repayment_Period__c.field-meta.xml
<CustomField>
    <fullName>Balloon_Repayment_Period__c</fullName>
    <label>Balloon Repayment Period</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event_Type__c</fullName>
    <label>Loan Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Creation</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Interest Rate Change</fullName>
            </value>
            <value>
                <fullName>Interest Rollup Recalculation</fullName>
            </value>
            <value>
                <fullName>Closed (Written Off)</fullName>
            </value>
            <value>
                <fullName>Closed (Early Repayment)</fullName>
            </value>
            <value>
                <fullName>Closed (All Obligations met)</fullName>
            </value>
            <value>
                <fullName>Bullet Repayment</fullName>
            </value>
            <value>
                <fullName>Automatic Schedule Migration for Migrated Loan</fullName>
            </value>
            <value>
                <fullName>Fee Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE then this is a migration record</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestBalloonRepaymentButtonController.cls
@isTest
private class TestBalloonRepaymentButtonController {
    @isTest static void test_get_repayment_schedules() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-2), System.today().addMonths(-1));

        List<Repayment_Schedule__c> result = BalloonRepaymentButtonController.getRepaymentSchedules(i.Id).Repayment_Schedules__r;
        System.assertEquals(10, result.size());
    }

    @isTest static void test_schedule_balloon_repayment() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-2), System.today().addMonths(-1));

        List<Repayment_Schedule__c> rsToProcess = BalloonRepaymentButtonController.getRepaymentSchedules(i.Id).Repayment_Schedules__r;
        Integer listSize = rsToProcess.size();
        
        Decimal principal = rsToProcess[listSize - 1].Principal_Expected__c + rsToProcess[listSize - 2].Principal_Expected__c;
        Decimal fees = rsToProcess[listSize - 1].Fees_Expected__c + rsToProcess[listSize - 2].Fees_Expected__c;

        BalloonRepaymentButtonController.scheduleBalloonRepayment(JSON.serialize(rsToProcess), listSize - 2, i.Id);
        
        List<Repayment_Schedule__c> actualRS = [
            SELECT Fees_Expected__c, Principal_Expected__c 
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id AND Active__c = true AND Migration__c = false
                AND Due_Date__c > TODAY
            ORDER BY Due_Date__c
        ];

        List<Loan_Event__c> loanEvents = [
            SELECT Balloon_Repayment_Period__c
            FROM Loan_Event__c
            WHERE Investment__c =: i.Id AND Loan_Event_Type__c = 'Bullet Repayment'
        ];
        System.assertEquals(listSize - 1, actualRS.size());
        System.assertEquals(1, loanEvents.size());
        System.assertEquals(listSize - 2, loanEvents[0].Balloon_Repayment_Period__c);
        System.assertEquals(principal.setScale(2), actualRS[listSize - 2].Principal_Expected__c.setScale(2));
        System.assertEquals(fees.setScale(2), actualRS[listSize - 2].Fees_Expected__c.setScale(2));

    }

}