force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Health_Check_Fails__c.field-meta.xml
<CustomField>
    <fullName>Health_Check_Fails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Health Check Fails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Health_Check_Failures__c.field-meta.xml
<CustomField>
    <fullName>Health_Check_Failures__c</fullName>
    <label>Health Check Failures</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Expected_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Expected_Principal_Balance__c</fullName>
    <label>Expected Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLoanHealthCheckBatch.cls
@isTest
private class TestLoanHealthCheckBatch {
    @isTest static void test_populate_issues() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));
        i.Status__c = 'Active';
        update i;

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result);
        System.assertEquals(0, result.size());
        
        Repayment_Schedule__c rs = [
            SELECT Expected_Principal_Balance__c
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id AND Active__c = true
            ORDER BY Due_Date__c DESC
            LIMIT 1
        ];
        rs.Expected_Principal_Balance__c = 1;
        update rs;

        // run the batch job
        Test.startTest();
        LoanHealthCheckBatch theBatch = new LoanHealthCheckBatch();
        Database.executebatch(theBatch);        
        Test.stopTest();

        Investment__c inv = [
            SELECT Health_Check_Fails__c, Health_Check_Failures__c
            FROM Investment__c
            WHERE Id =: i.Id
        ];
        System.assert(inv.Health_Check_Fails__c);
        System.assertEquals(System.Label.sfims.health_check_5, inv.Health_Check_Failures__c);
        
    }

    @isTest static void test_clear_issues() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));
        i.Status__c = 'Active';
        update i;

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result);
        System.assertEquals(0, result.size());
        
        Repayment_Schedule__c rs = [
            SELECT Expected_Principal_Balance__c
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id AND Active__c = true
            ORDER BY Due_Date__c DESC
            LIMIT 1
        ];
        rs.Expected_Principal_Balance__c = 1;
        update rs;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result2);
        System.assertEquals(1, result2.size());
        System.assertEquals(System.Label.sfims.health_check_5, result2[0]);

        i.Health_Check_Fails__c = true;
        i.Health_Check_Failures__c = System.Label.sfims.health_check_5;
        update i;
        rs.Expected_Principal_Balance__c = 0;
        update rs;

        // run the batch job
        Test.startTest();
        LoanHealthCheckBatch theBatch = new LoanHealthCheckBatch();
        Database.executebatch(theBatch);        
        Test.stopTest();

        Investment__c inv = [
            SELECT Health_Check_Fails__c, Health_Check_Failures__c
            FROM Investment__c
            WHERE Id =: i.Id
        ];
        System.assert(!inv.Health_Check_Fails__c);
        System.assertEquals(null, inv.Health_Check_Failures__c);
        
    }
    
}