force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Calculation_Method__c</fullName>
    <description>No penalty - Won&#39;t charge penalties when a repayment is late
Overdue Principal * # of Late Days * Penalty Rate - it&#39;s the most common method, where the penalty rate is applied on the principal due late amount and the number of late days</description>
    <inlineHelpText>No penalty
Overdue Principal * # of Late Days * Penalty Rate : penalty rate applied on principal due late amount and number of late days
(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate : same but with overdue interest</inlineHelpText>
    <label>Late Repayment Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Penalty</fullName>
                <default>true</default>
                <label>No Penalty</label>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
                <label>Overdue Principal * # of Late Days * Penalty Rate</label>
            </value>
            <value>
                <fullName>Principal+Interest</fullName>
                <label>(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fixed_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fixed_Fee__c</fullName>
    <label>Late Repayment Fixed Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Interest_Rate__c</fullName>
    <label>Late Repayment Interest Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Tolerance_Period__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Tolerance_Period__c</fullName>
    <description>In the Late Repayment Tolerance Period you can define a number of days before which no penalties will be applied to an account even if there is a late repayment.</description>
    <inlineHelpText>In the Late Repayment Tolerance Period you can define a number of days before which no penalties will be applied to an account even if there is a late repayment.</inlineHelpText>
    <label>Late Repayment Tolerance Period (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event_Detail__c/Loan_Event_Detail__c.object-meta.xml
<CustomObject>
    <description>This object describes details of loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event Detail</label>
    <nameField>
        <displayFormat>LED-{00000000}</displayFormat>
        <label>Loan Event Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Event Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event_Detail__c/fields/Cancel_Late_Repayment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Late_Repayment_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancel Late Repayment Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Event_Detail__c/fields/Late_Repayment_Fixed_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fixed_Fee__c</fullName>
    <label>Late Repayment Fixed Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Event_Detail__c/fields/Loan_Event__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event__c</fullName>
    <label>Loan Event</label>
    <referenceTo>Loan_Event__c</referenceTo>
    <relationshipLabel>Loan Event Details</relationshipLabel>
    <relationshipName>Loan_Event_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Late_Repayment_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Calculation_Method__c</fullName>
    <description>No penalty - Won&#39;t charge penalties when a repayment is late
Overdue Principal * # of Late Days * Penalty Rate - it&#39;s the most common method, where the penalty rate is applied on the principal due late amount and the number of late days</description>
    <inlineHelpText>No penalty
Overdue Principal * # of Late Days * Penalty Rate : penalty rate applied on principal due late amount and number of late days
(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate : same but with overdue interest</inlineHelpText>
    <label>Late Repayment Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Penalty</fullName>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Overdue Principal * # of Late Days * Penalty Rate</fullName>
            </value>
            <value>
                <fullName>(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Late_Repayment_Fixed_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fixed_Fee__c</fullName>
    <label>Late Repayment Fixed Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Late_Repayment_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Interest_Rate__c</fullName>
    <label>Late Repayment Interest Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Cancel_Late_Repayment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Late_Repayment_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancel Late Repayment Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <formula>if(Cancel_Late_Repayment_Fee__c, 0, if(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Fixed Fee&#39;, Late_Repayment_Fixed_Fee__c, if(OR(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal&#39;, TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal+Interest&#39;), Late_Repayment_Fees_On_Last_Paid_Date__c + Days_Since_Last_Paid_Date__c * Daily_Late_Repayment_Fees__c, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestCancelLateRepaymentFeeButton.cls
@isTest
private class TestCancelLateRepaymentFeeButton {
    @isTest static void test_cancel_Late_Repayment_Fee() {
        // create a loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;

        // create a loan in the past
        Investment__c i = TestUtils.createNewLoan(System.today().addmonths(-2), System.today().addmonths(-1));
        i.Loan_Product__c = lp.Id;
        i.Status__c = 'Inactive';
        i.Late_Repayment_Calculation_Method__c = 'Fixed Fee';
        i.Late_Repayment_Fixed_Fee__c = 1;
        i.Late_Repayment_Interest_Rate__c = null;
        i.Late_Repayment_Tolerance_Period__c = 5;
        i.Disbursement_Method__c = 'Full disbursement at start';
        insert i;
        
        // generate repayment schedules
        List<Repayment_Schedule__c> schedules = LoanScheduler.generateScheduleById(i.Id);
        insert schedules;

        Repayment_Schedule__c rs = [
            SELECT Late_Repayment_Fees_Expected0__c, Cancel_Late_Repayment_Fee__c, Due_Date__c 
            FROM Repayment_Schedule__c
            WHERE Loan__c = :i.Id 
            ORDER BY Due_Date__c
            LIMIT 1
        ];
        System.debug(rs);
        
        System.assert(rs.Late_Repayment_Fees_Expected0__c > 0);
        System.assert(!rs.Cancel_Late_Repayment_Fee__c);

        // cancel late repayment fee on the first repayment schedule
        CancelLateRepaymentFeeButtonController.cancelLateRepaymentFee(rs.Id);

        // check the creation of a loan event
        List<Loan_Event__c> les = [
            SELECT Approval_Status__c
            FROM Loan_Event__c
            WHERE Investment__c =: i.Id AND Loan_Event_Type__c = 'Fee Cancelled'
        ];
        System.assertEquals(1, les.size());
        
        Loan_Event__c le = les[0];
        if (le.Approval_Status__c == 'Pending Approval') {
            le.Approval_Status__c = 'Approved';
            update le;
        }
        
        Loan_Event_Detail__c led = [
            SELECT Due_Date__c
            FROM Loan_Event_Detail__c
            WHERE Loan_Event__c = :le.Id
            LIMIT 1
        ];
        System.assertEquals(rs.Due_Date__c, led.Due_Date__c);
       
        // check if repayment schedule was updated
        Repayment_Schedule__c rs1 = [
            SELECT Late_Repayment_Fees_Expected0__c, Cancel_Late_Repayment_Fee__c, Due_Date__c 
            FROM Repayment_Schedule__c
            WHERE Id = :rs.Id 
        ];
        System.debug(rs1);

        System.assert(rs1.Late_Repayment_Fees_Expected0__c == 0);
        System.assert(rs1.Cancel_Late_Repayment_Fee__c);

    }

}