force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date the Loan Event occured</description>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event_Type__c</fullName>
    <label>Loan Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Creation</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Interest Rate Change</fullName>
            </value>
            <value>
                <fullName>Interest Rollup Recalculation</fullName>
            </value>
            <value>
                <fullName>Closed (Written Off)</fullName>
            </value>
            <value>
                <fullName>Closed (Early Repayment)</fullName>
            </value>
            <value>
                <fullName>Closed (All Obligations met)</fullName>
            </value>
            <value>
                <fullName>Bullet Repayment</fullName>
            </value>
            <value>
                <fullName>Automatic Schedule Migration for Migrated Loan</fullName>
            </value>
            <value>
                <fullName>Fee Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Event__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Event</label>
    <referenceTo>Loan_Event__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of transaction</description>
    <inlineHelpText>Type of transaction</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Disbursement Correction</fullName>
            </value>
            <value>
                <fullName>Repayment Correction</fullName>
            </value>
            <value>
                <fullName>Fee Correction</fullName>
            </value>
            <value>
                <fullName>Fund Drawdown</fullName>
            </value>
            <value>
                <fullName>Fund Repayment</fullName>
            </value>
            <value>
                <fullName>Schedule (Not Due)</fullName>
            </value>
            <value>
                <fullName>Schedule (Late)</fullName>
            </value>
            <value>
                <fullName>Schedule (Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid (Late))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLoanEventTrigger.cls
@isTest
private class TestLoanEventTrigger {
	@isTest static void test_generate_loan_event_name() {
        
		Loan_Event__c newLoanEvent = new Loan_Event__c(
            Loan_Event_Type__c = 'Loan Creation',
            Event_Date__c = System.today().addDays(-1)
        );

        insert newLoanEvent;

        Loan_Event__c loanEvent = [
            SELECT Name 
            FROM Loan_Event__c
            WHERE Id =: newLoanEvent.Id
        ];
        System.assertEquals('Loan Creation - ' + System.today().addDays(-1).format(), loanEvent.Name);

        newLoanEvent.Loan_Event_Type__c = 'Reschedule';
        newLoanEvent.Event_Date__c = System.today();
        update newLoanEvent;

        Loan_Event__c loanEvent2 = [
            SELECT Name 
            FROM Loan_Event__c
            WHERE Id =: newLoanEvent.Id
        ];
        System.assertEquals('Reschedule - ' + System.today().format(), loanEvent2.Name);
    }

    @isTest static void test_delete_disbursed_transactions() {
        // create a loan
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(1), System.today().addMonths(2));
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;

        // create disbursed transactions
        List<Transaction__c> trToInsert = new List<Transaction__c>();
        Integer numberOfTransactions = 4;
        for (Integer k = 0; k < numberOfTransactions; k++) {
            trToInsert.add(
                TestUtils.createNewTransaction(i.Id, i.Amount__c/numberOfTransactions, 'Disbursement', 'Disbursed', System.today().addMonths(1 + k))
            );
        }
        
        Map<String, String> status = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(trToInsert), '[]');
        System.debug(status);
        // in this case, for each disbursed transaction the loan must be rescheduled
        // this also means that a loan event associated with this loan must be created 
        List<Loan_Event__c> loanEvents = [
            SELECT Id
            FROM Loan_Event__c
            WHERE Investment__c =: i.Id AND Loan_Event_Type__c = 'Disbursement'
            ORDER BY Event_Date__c ASC
        ];

        // Perform test
        Database.DeleteResult result = Database.delete(loanEvents[0], false);
        // Verify 
        // In this case the deletion should have been stopped by the trigger,
        // so verify that we got back an error.
        
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals(System.Label.sfims.error_message_44, result.getErrors()[0].getMessage());

        System.assertEquals([SELECT COUNT() FROM Transaction__c WHERE Investment__c =: i.Id AND Type__c = 'Disbursement'], loanEvents.size());
        System.assertEquals(numberOfTransactions, loanEvents.size());

        delete loanEvents;

        System.assertEquals([SELECT COUNT() FROM Transaction__c WHERE Investment__c =: i.Id AND Type__c = 'Disbursement'], 0);
    }
}