force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Calculation_Method__c</fullName>
    <description>No penalty - Won&#39;t charge penalties when a repayment is late
Overdue Principal * # of Late Days * Penalty Rate - it&#39;s the most common method, where the penalty rate is applied on the principal due late amount and the number of late days</description>
    <inlineHelpText>No penalty
Overdue Principal * # of Late Days * Penalty Rate : penalty rate applied on principal due late amount and number of late days
(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate : same but with overdue interest</inlineHelpText>
    <label>Late Repayment Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Penalty</fullName>
                <default>true</default>
                <label>No Penalty</label>
            </value>
            <value>
                <fullName>Fixed Fee</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
                <label>Overdue Principal * # of Late Days * Penalty Rate</label>
            </value>
            <value>
                <fullName>Principal+Interest</fullName>
                <label>(Overdue Principal + Overdue Interest) * # of Late Days * Penalty Rate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fixed_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fixed_Fee__c</fullName>
    <label>Late Repayment Fixed Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Interest_Rate__c</fullName>
    <label>Late Repayment Interest Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Tolerance_Period__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Tolerance_Period__c</fullName>
    <description>In the Late Repayment Tolerance Period you can define a number of days before which no penalties will be applied to an account even if there is a late repayment.</description>
    <inlineHelpText>In the Late Repayment Tolerance Period you can define a number of days before which no penalties will be applied to an account even if there is a late repayment.</inlineHelpText>
    <label>Late Repayment Tolerance Period (days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Total_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected__c</fullName>
    <formula>Fees_Expected__c + Interest_Expected0__c + Late_Repayment_Fees_Expected0__c + Principal_Expected__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Total_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid__c</fullName>
    <label>Total Paid</label>
    <summarizedField>Repayment_Schedule__c.Total_Paid__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected__c</fullName>
    <formula>Fees_Expected__c + Interest_Expected0__c + Late_Repayment_Fees_Expected0__c + Principal_Expected__c + Interest_Bonus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid__c</fullName>
    <formula>Fees_Paid__c + Interest_Paid__c + Late_Repayment_Fees_Paid__c + Principal_Paid__c +  Interest_Bonus_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestRepaymentScheduleTriggerHandler.cls
@isTest
private class TestRepaymentScheduleTriggerHandler {
	
	@isTest static void test_field_update_methods() {
		User platformUser = TestUtils.createPlatformUser();

        System.runAs(platformUser){     
            // initially total paid = 0
            Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
            
            // take the first schedule and check the status
            Repayment_Schedule__c rs = [Select Id, Status__c, Total_Expected__c, Total_Paid__c From Repayment_Schedule__C Where Loan__c = :i.Id ORDER BY Due_Date__c ASC LIMIT 1];
            System.debug(rs);
            System.assertEquals('Late', rs.Status__c);
        }
    }

    @isTest static void test_delete_methods() {
		User platformUser = TestUtils.createPlatformUser();

        System.runAs(platformUser){        
            // default number of instalments - 12
            Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
            
            // take the first schedule and delete it
            Repayment_Schedule__c rs = [Select Id, Status__c, Total_Expected__c, Total_Paid__c From Repayment_Schedule__c Where Loan__c = :i.Id ORDER BY Due_Date__c ASC LIMIT 1];
            delete rs;
            System.assertEquals(11,[Select Id, Status__c, Total_Expected__c, Total_Paid__c From Repayment_Schedule__C Where Loan__c = :i.Id].size());
        }
    }   

    @isTest static void test_populate_late_repayment_fixed_fee() {
        // create a loan in the past
        Investment__c i = TestUtils.createNewLoan(System.today().addmonths(-2), System.today().addmonths(-1));
        i.Status__c = 'Active';
        i.Late_Repayment_Calculation_Method__c = 'Fixed Fee';
        i.Late_Repayment_Fixed_Fee__c = 1;
        i.Late_Repayment_Interest_Rate__c = null;
        i.Late_Repayment_Tolerance_Period__c = 5;
        insert i;
        
        // generate repayment schedules
        List<Repayment_Schedule__c> schedules = LoanScheduler.generateScheduleById(i.Id);
        insert schedules;

        Repayment_Schedule__c rs = [
            SELECT Late_Repayment_Fixed_Fee__c 
            FROM Repayment_Schedule__c 
            WHERE Loan__c = :i.Id 
            ORDER BY Due_Date__c ASC 
            LIMIT 1
        ];

        // verify if Late Repayment Fixed Fee was calculated
        System.assertEquals(i.Late_Repayment_Fixed_Fee__c, rs.Late_Repayment_Fixed_Fee__c);
    } 
}