force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestLoanUtils.cls
@isTest
private class TestLoanUtils {
	
	@isTest static void test_getLoanSchedule() {
	
        // initially total paid = 0
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));

        List<Repayment_Schedule__c> repList = LoanUtils.getLoanSchedule(i.Id);
        System.assertEquals([SELECT COUNT() FROM Repayment_Schedule__c WHERE Loan__c =: i.Id],repList.size());

        // test the same with unauthorized user
		User newUser = TestUtils.ensureRestrictedUser();
		System.runAs(newUser){
            List<Repayment_Schedule__c> repList2;
			try{
				repList2 = LoanUtils.getLoanSchedule(i.Id);
				System.assert(false,'Expected an exception (unauthorized user');
			} catch (AuraHandledException e){
                // expected
                system.assertEquals(repList2,null);
            }
        }         

    }

	@isTest static void test_getLoanScheduleWrappers() {
	
        // initially total paid = 0
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));

        List<RepaymentScheduleWrapper> repList = LoanUtils.getLoanScheduleWrappers(i.Id);
        system.assertEquals([SELECT COUNT() FROM Repayment_Schedule__c WHERE Loan__c =: i.Id],repList.size());


        // test the same with unauthorized user
		User newUser = TestUtils.ensureRestrictedUser();
		System.runAs(newUser){
            List<RepaymentScheduleWrapper> repList2;
			try{
				repList2 = LoanUtils.getLoanScheduleWrappers(i.Id);
				System.assert(false,'Expected an exception (unauthorized user');
			} catch (AuraHandledException e){
                // expected
                system.assertEquals(repList2,null);
            }
        }  
    }

	@isTest static void test_updateLoanSchedule() {
		
        // initially total paid = 0
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));
        List<Repayment_Schedule__c> rsList = [SELECT Fees_Expected__c FROM Repayment_Schedule__c WHERE Loan__c =: i.Id];
        rsList[0].Fees_Expected__c = 10;

        Boolean success = LoanUtils.updateLoanSchedule(rsList);
        system.assertEquals(10,[SELECT Fees_Expected__c FROM Repayment_Schedule__c WHERE Id = :rsList[0].Id].Fees_Expected__c);
        
        // test the same with unauthorized user
		User newUser = TestUtils.ensureRestrictedUser();
		System.runAs(newUser){
            Boolean success2;
			try{
				success2 = LoanUtils.updateLoanSchedule(rsList);
				System.assert(false,'Expected an exception (unauthorized user');
			} catch (AuraHandledException e){
                // expected
                system.assertEquals(success2,null);
            }
        }  
    }    
}