force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of transaction</description>
    <inlineHelpText>Type of transaction</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Disbursement Correction</fullName>
            </value>
            <value>
                <fullName>Repayment Correction</fullName>
            </value>
            <value>
                <fullName>Fee Correction</fullName>
            </value>
            <value>
                <fullName>Fund Drawdown</fullName>
            </value>
            <value>
                <fullName>Fund Repayment</fullName>
            </value>
            <value>
                <fullName>Schedule (Not Due)</fullName>
            </value>
            <value>
                <fullName>Schedule (Late)</fullName>
            </value>
            <value>
                <fullName>Schedule (Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid (Late))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanInternalTransferController.cls
public without sharing class LoanInternalTransferController {

    public class CommonException extends Exception {
    }

    @AuraEnabled
    public static void createTransferTransactions(Double amount, Date transactionDate, Id fromLoanId, Id toLoanId, Map<String, Object> dataMap) {
        try {
            // validations
            if (fromLoanId == null || toLoanId == null || amount == null || transactionDate == null) {
                throw new CommonException('Required parameters are not correct.');
            }
            Map<Id, Investment__c> investments = new Map<Id, Investment__c>([SELECT sfims__Available_Disbursement_Amount__c,sfims__Status__c,sfims__Principal_Remaining__c FROM Investment__c WHERE RecordType.Name = 'Loan' AND (Id = :fromLoanId OR Id = :toLoanId)]);
            if (investments.size() != 2 ||
                    !investments.containsKey(fromLoanId) ||
                    !investments.containsKey(toLoanId) ||
                    investments.get(fromLoanId).sfims__Available_Disbursement_Amount__c <= 0 ||
                    investments.get(toLoanId).sfims__Status__c != 'Active' ||
                    investments.get(toLoanId).sfims__Principal_Remaining__c <= 0) {
                throw new CommonException('Required parameters are invalid.');
            }
            if (amount > investments.get(toLoanId).sfims__Principal_Remaining__c) {
                throw new CommonException('Amount cannot be more ' + investments.get(toLoanId).sfims__Principal_Remaining__c);
            }
            // END validations

            List<Transaction__c> internalTransferTransactions = new List<Transaction__c>();
            // for From Loan
            internalTransferTransactions.add(new Transaction__c (
                    Type__c = 'Disbursement',
                    Status__c = 'Disbursed',
                    Transaction_Date__c = transactionDate,
                    Amount__c = amount,
                    Investment__c = fromLoanId
                    // Allow_To_Disburse_Loan_From_Trigger__c = true
            ));
            // for To Loan
            internalTransferTransactions.add(new Transaction__c (
                    Type__c = 'Repayment',
                    Status__c = 'Received',
                    Transaction_Date__c = transactionDate,
                    Amount__c = amount,
                    Investment__c = toLoanId
            ));
            insert internalTransferTransactions;
        } catch (Exception err) {
            throw new CommonException(err.getMessage());
        }
    }
}