force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Expected_Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Open_Ended_Loan__c</fullName>
    <label>Interest Expected (Open Ended Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Recalculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Recalculation_Status__c</fullName>
    <defaultValue>&#39;Not Needed&#39;</defaultValue>
    <label>Recalculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Needed</fullName>
                <default>true</default>
                <label>Not Needed</label>
            </value>
            <value>
                <fullName>Pending Recalculation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Expected_Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Expected_Principal_Balance__c</fullName>
    <label>Expected Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected_Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Open_Ended_Loan__c</fullName>
    <formula>Interest_Expected_On_Last_Paid_Date__c + (TODAY() - IF(ISNULL(Last_Action_Date__c), Loan__r.Disbursement_Date__c, Last_Action_Date__c)) * Principal_Remaining__c * Loan__r.Interest_Rate__c / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected (Open Ended Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Late_Repayment_Fees_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fees_Expected0__c</fullName>
    <formula>if(Cancel_Late_Repayment_Fee__c, 0, if(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Fixed Fee&#39;, Late_Repayment_Fixed_Fee__c, if(OR(TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal&#39;, TEXT(Loan__r.Late_Repayment_Calculation_Method__c) == &#39;Principal+Interest&#39;), Late_Repayment_Fees_On_Last_Paid_Date__c + Days_Since_Last_Paid_Date__c * Daily_Late_Repayment_Fees__c, 0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Repayment Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE then this is a migration record</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Principal_Balance__c</fullName>
    <description>The total remaining Principal Balance on Investment Level after the latest payment to this schedule.</description>
    <inlineHelpText>The total remaining Principal Balance on Investment Level after the latest payment to this schedule.</inlineHelpText>
    <label>Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The amount within this transaction assigned to fees</description>
    <inlineHelpText>The amount within this transaction assigned to fees</inlineHelpText>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <description>The amount within this transaction assigned to interest</description>
    <inlineHelpText>The amount within this transaction assigned to interest</inlineHelpText>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Late_Repayment_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fee_Amount__c</fullName>
    <label>Late Repayment Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is TRUE then it is a migration record</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Principal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Principal_Amount__c</fullName>
    <description>The amount within this transaction assigned to principal</description>
    <inlineHelpText>The amount within this transaction assigned to principal</inlineHelpText>
    <label>Principal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Principal_Balance__c</fullName>
    <description>The total remaining Principal Balance on Investment level after this Transaction</description>
    <inlineHelpText>The total remaining Principal Balance on Investment level after this Transaction</inlineHelpText>
    <label>Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Repayment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment Schedule</label>
    <referenceTo>Repayment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestLoanHealthCheckController.cls
@isTest
private class TestLoanHealthCheckController {

    @isTest static void test_getLoanData_sums_of_paid() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-7), System.today().addMonths(-6));
        i.Disbursement_Method__c = 'Full disbursement at start';
        update i;
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addMonths(-7));
        Transaction__c t1 = TestUtils.createNewTransaction(i.Id, 10, 'Repayment');
        insert new List<Transaction__c>{t,t1};

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result);
        System.assertEquals(0, result.size());
        
        Transaction__c t2 =  TestUtils.createNewTransaction(i.Id, 4, 'Repayment', System.today().addDays(-1));
        t2.Migration__c = true;
        t2.Fee_Amount__c = 1;
        t2.Interest_Amount__c = 1;
        t2.Late_Repayment_Fee_Amount__c = 1;
        t2.Principal_Amount__c = 1;
        insert t2;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        for (String str : result2) {
            System.debug(str);
        }
        System.assertEquals(5, result2.size());
    }

    @isTest static void test_getLoanData_transaction_date() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(0, result.size());
        
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', 'Planned', System.today().addDays(-1));
        insert t;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(1, result2.size());
        System.assertEquals(System.Label.sfims.health_check_4, result2[0]);

    }

    @isTest static void test_getLoanData_recalculation_status() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(0, result.size());
        
        i.Recalculation_Status__c = 'Pending Recalculation';
        update i;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(1, result2.size());
        System.assertEquals(System.Label.sfims.health_check_1, result2[0]);

        i.Recalculation_Status__c = 'In Progress';
        update i;

        List<String> result3 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(1, result3.size());
        System.assertEquals(System.Label.sfims.health_check_2, result3[0]);

        i.Recalculation_Status__c = 'Failed';
        update i;

        List<String> result4 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(1, result4.size());
        System.assertEquals(System.Label.sfims.health_check_3, result4[0]);

    }

    @isTest static void test_getLoanData_expected_principal_balance() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result);
        System.assertEquals(0, result.size());
        
        Repayment_Schedule__c rs = [
            SELECT Expected_Principal_Balance__c
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id AND Active__c = true
            ORDER BY Due_Date__c DESC
            LIMIT 1
        ];
        rs.Expected_Principal_Balance__c = 1;
        update rs;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(1, result2.size());
        System.assertEquals(System.Label.sfims.health_check_5, result2[0]);

    }

    @isTest static void test_getLoanData_principal_balance() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
        i.Disbursement_Method__c = 'Full disbursement at start';
        update i;
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addMonths(-1));
        Transaction__c t1 = TestUtils.createNewTransaction(i.Id, 10, 'Repayment');
        insert new List<Transaction__c>{t,t1};

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result);
        System.assertEquals(0, result.size());
        
        Repayment_Schedule__c rs = [
            SELECT Principal_Balance__c
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id AND Active__c = true
            ORDER BY Due_Date__c DESC
            LIMIT 1
        ];
        rs.Principal_Balance__c += 1;
        update rs;
        Transaction__c tr = [
            SELECT Principal_Balance__c
            FROM Transaction__c
            WHERE Investment__c =: i.Id
            ORDER BY Transaction_Date__c DESC
            LIMIT 1
        ];
        tr.Principal_Balance__c += 1;
        update tr;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(2, result2.size());
        System.assertEquals(System.Label.sfims.health_check_6, result2[0]);
        System.assertEquals(System.Label.sfims.health_check_7, result2[1]);

    }

    @isTest static void test_getLoanData_populate_late_repayment_fees_expected() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addmonths(-6), System.today().addmonths(-5));

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);

        Investment__c inv = [
            SELECT Late_Repayment_Fees_Expected0__c
            FROM Investment__c
            WHERE Id =: i.Id
        ];

        AggregateResult rsResult = [
            SELECT SUM(Late_Repayment_Fees_Expected0__c) lateRepaymentFeesExpected
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id
        ];
        System.debug(rsResult);
        
        System.assertEquals(inv.Late_Repayment_Fees_Expected0__c, rsResult.get('lateRepaymentFeesExpected'));
    }

    @isTest static void test_getLoanData_populate_interest_expected() {
        Investment__c i = TestUtils.createNewScheduledOpenEndedLoan(System.today().addDays(-7), 100);

        List<String> result = LoanHealthCheckController.getLoanData(i.Id);

        Investment__c inv = [
            SELECT Interest_Expected_Open_Ended_Loan__c
            FROM Investment__c
            WHERE Id =: i.Id
        ];

        AggregateResult rsResult = [
            SELECT SUM(Interest_Expected_Open_Ended_Loan__c) interestExpected
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id
        ];
        System.debug(rsResult);
        
        System.assertEquals(inv.Interest_Expected_Open_Ended_Loan__c, rsResult.get('interestExpected'));
    }

    @isTest static void test_getLoanData_repayment_before_disbursement() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
        
        List<String> result = LoanHealthCheckController.getLoanData(i.Id);
        System.debug(result);
        System.assertEquals(0, result.size());

        Transaction__c t = TestUtils.createNewTransaction(i.Id, 10, 'Repayment');
        insert t;

        List<String> result2 = LoanHealthCheckController.getLoanData(i.Id);
        System.assertEquals(1, result2.size());
        System.assertEquals(System.Label.sfims.health_check_8, result2[0]);

    }

}