force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Expected_Standard_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Standard_Loan__c</fullName>
    <label>Interest Expected (Standard Loan)</label>
    <summarizedField>Repayment_Schedule__c.Interest_Expected_Standard_Loan__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <summarizedField>Repayment_Schedule__c.Principal_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected_Standard_Loan__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected_Standard_Loan__c</fullName>
    <label>Interest Expected (Standard Loan)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Event__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Event</label>
    <referenceTo>Loan_Event__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Repayment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment Schedule</label>
    <referenceTo>Repayment_Schedule__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of transaction</description>
    <inlineHelpText>Type of transaction</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Disbursement Correction</fullName>
            </value>
            <value>
                <fullName>Repayment Correction</fullName>
            </value>
            <value>
                <fullName>Fee Correction</fullName>
            </value>
            <value>
                <fullName>Fund Drawdown</fullName>
            </value>
            <value>
                <fullName>Fund Repayment</fullName>
            </value>
            <value>
                <fullName>Schedule (Not Due)</fullName>
            </value>
            <value>
                <fullName>Schedule (Late)</fullName>
            </value>
            <value>
                <fullName>Schedule (Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid (Late))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDisburseLoanButtonController.cls
@isTest
private class TestDisburseLoanButtonController {
    @isTest static void test_get_disbursement_transactions() {
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
        i.Disbursement_Method__c = 'Full disbursement at start';
        update i;
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement');
        insert t;

        List<Transaction__c> result = DisburseLoanButtonController.getDisbursementTransactions(i.Id);
        System.assertEquals(1, result.size());
        System.assertEquals(t.Id, result[0].Id);
    }

    @isTest static void test_generate_schedule_preview() {
        System.assertEquals(0, [SELECT COUNT() FROM Transaction__c WHERE Type__c = 'Disbursement']);
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;
        
        Transaction__c t = TestUtils.createNewTransaction(i.Id, 50, 'Disbursement', System.today().addMonths(-1));
        
        Test.startTest();
        Map<String, String> status = DisburseLoanButtonController.generateSchedulePreview(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');
        Test.stopTest();
        
        // verify that transactions have not been saved
        System.assertEquals(0, [SELECT COUNT() FROM Transaction__c WHERE Type__c = 'Disbursement']);

        // perform the saveData method to verify results
        t.Status__c = 'Disbursed';
        DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');

        List<Repayment_Schedule__c> result = [
            SELECT Id, Due_Date__c, Principal_Expected__c, Interest_Expected_Standard_Loan__c, Fees_Expected__c
            FROM Repayment_Schedule__c
            WHERE Loan__c =: i.Id AND Active__c = true
        ];

        System.assert(status.containsKey('toInsert'));
        List<Repayment_Schedule__c> rsToPreview = (List<Repayment_Schedule__c>)JSON.deserialize(status.get('toInsert'), List<Repayment_Schedule__c>.class);
        System.assertEquals(result.size(), rsToPreview.size());
        for (Integer k = 0; k < result.size(); k++) {
            System.debug(result[k]);
            System.debug(rsToPreview[k]);
            System.assertEquals(result[k].Due_Date__c, rsToPreview[k].Due_Date__c);
            System.assertEquals(result[k].Principal_Expected__c, rsToPreview[k].Principal_Expected__c);
            System.assertEquals(result[k].Interest_Expected_Standard_Loan__c, rsToPreview[k].Interest_Expected_Standard_Loan__c);
            System.assertEquals(result[k].Fees_Expected__c, rsToPreview[k].Fees_Expected__c);
        }
    }

    @isTest static void test_process_disbursed_transactions() {
        // create a loan
        Investment__c i = TestUtils.createNewScheduledLoan(System.today(), System.today().addMonths(1));
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;

        // create disbursed transactions (test in bulk)
        List<Transaction__c> trToInsert = new List<Transaction__c>();
        Integer numberOfTransactions = 100;
        for (Integer k = 0; k < numberOfTransactions; k++) {
            trToInsert.add(
                TestUtils.createNewTransaction(i.Id, i.Amount__c/numberOfTransactions, 'Disbursement', System.today().addDays(k))
            );
        }
        Test.startTest();
        Map<String, String> status = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(trToInsert), '[]');
		Test.stopTest();
        // in this case, for each disbursed transaction the loan must be rescheduled
        // this also means that a loan event associated with this loan must be created 
        List<Loan_Event__c> loanEvents = [
            SELECT Amount__c
            FROM Loan_Event__c
            WHERE Investment__c =: i.Id AND Loan_Event_Type__c = 'Disbursement'
            ORDER BY Amount__c DESC
        ];
        Investment__c inv = [
            SELECT Principal_Remaining__c, Fees_Remaining__c
            FROM Investment__c
            WHERE Id =: i.Id 
        ];

        System.debug(status.containsKey('error'));
        System.debug(status.get('error'));
        System.assertEquals([SELECT COUNT() FROM Transaction__c WHERE Investment__c =: i.Id AND Type__c = 'Disbursement'], loanEvents.size());
        System.assertEquals(inv.Principal_Remaining__c, 100);
        Id recordTypeId = Schema.Sobjecttype.Transaction__c.getRecordTypeInfosByName().get('Investment Transaction').getRecordTypeId();
        List<Transaction__c> trs = [SELECT RecordTypeId, Created_Using_The_Disburse_Button__c FROM Transaction__c WHERE Investment__c =: i.Id AND Type__c = 'Disbursement'];
        System.debug(trs.size());
        System.assertEquals(recordTypeId, trs[0].RecordTypeId);
        System.assert(!trs[0].Created_Using_The_Disburse_Button__c);  
    }

    @isTest static void test_process_disbursed_transactions_for_a_loan_with_no_repayment_schedules() {
        // create a loan
        Investment__c i = TestUtils.createNewLoan();
        i.Amount__c = 100;
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        insert i;

        // create disbursed transactions
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today());
        Transaction__c t2 = TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today().addMonths(1));
        Test.startTest();
        Map<String, String> status = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t, t2}), '[]');
		Test.stopTest();
        
        // in this case, the transactions that we tried to insert were not saved
        // it was blocked because of the 'no repayment schedule' validation 
        List<Transaction__c> trs = [
            SELECT Id
            FROM Transaction__c
            WHERE Investment__c =: i.Id AND Type__c = 'Disbursement' AND Status__c = 'Disbursed'
        ];

        System.assertEquals(0, trs.size());
        System.assert(status.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_9, status.get('error'));
               
    }

    @isTest static void test_disburse_open_ended_loan() {
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        insert lp;
        
        // create a loan
        Integer days = 100;
        Investment__c i = TestUtils.createNewScheduledOpenEndedLoan(System.today().addDays(-days), 100);
        i.Loan_Product__c = lp.Id;
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        update i;
        // create a disbursed transaction
        List<Transaction__c> tr = new List<Transaction__c>{
            TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today().addDays(-days)),
            TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today())
        };
        
        Test.startTest();
        Map<String, String> result = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(tr), '[]');
        System.debug(result);
		Test.stopTest();
        
        // pay interest on the tansaction date
        Transaction__c t = TestUtils.createNewTransaction(i.Id, 0.005 * days, 'Repayment', System.today());
        insert t;
        
        // in this case, for the disbursed transaction the loan must be rescheduled
        // this also means that a loan event associated with this loan must be created 
        List<Loan_Event__c> loanEvents = [
            SELECT Amount__c
            FROM Loan_Event__c
            WHERE Investment__c =: i.Id AND Loan_Event_Type__c = 'Disbursement'
            ORDER BY Amount__c DESC
        ];
        Investment__c inv = [
            SELECT Principal_Remaining__c, Fees_Remaining__c
            FROM Investment__c
            WHERE Id =: i.Id 
        ];

        System.assertEquals(tr.size(), loanEvents.size());
        
        System.assertEquals(tr.size(), [SELECT COUNT() FROM Transaction__c WHERE Type__c = 'Disbursement']);
        Id recordTypeId = Schema.Sobjecttype.Transaction__c.getRecordTypeInfosByName().get('Investment Transaction').getRecordTypeId();
        List<Transaction__c> trs = [SELECT RecordTypeId FROM Transaction__c WHERE Type__c = 'Disbursement'];
        System.assertEquals(recordTypeId, trs[0].RecordTypeId);
        System.assertEquals(inv.Principal_Remaining__c, i.Amount__c);
               
    }

    @isTest static void test_run_validations_full_disbursement_at_start() {      
        Investment__c i = TestUtils.createNewScheduledLoan();
        i.Disbursement_Method__c = 'Full disbursement at start';
        i.Status__c = 'Inactive';
        update i;

        // try to add more that 1 record
        Transaction__c t1 = TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today());
        Transaction__c t2 = TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today().addDays(1));
        List<Transaction__c> transactions = new List<Transaction__c>{t1,t2};
       
        // Perform validation
        Map<String, String> result = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t1, t2}), '[]');
        // Verify 
        // In this case the insertion should have been stopped,
        // so verify that we got back an error.
        System.assert(result.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_14, result.get('error'));
       
        // Perform validation
        Map<String, String> result2 = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t1}), '[]');
        // Verify 
        // In this case the insertion should have been stopped,
        // so verify that we got back an error.
        System.assert(result2.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_16, result2.get('error'));

        i.Setup_Fee_Charging_Method__c = 'Deducted From Principal';
        update i;

        // Perform validation
        Map<String, String> result3 = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t1}), '[]');
        // Verify 
        // In this case the insertion should have been stopped,
        // so verify that we got back an error.
        System.assert(result3.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_15, result3.get('error'));
    }

    @isTest static void test_run_validations_tranched_disbursement_allowed() {
        Investment__c i = TestUtils.createNewScheduledLoan();
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)';
        i.Disbursement_Method__c = 'Tranched disbursement allowed';
        i.Status__c = 'Inactive';
        update i;

        // try to add a planned transaction and a disbursed transaction, the transaction date of which is after the transaction date of the planned transaction 
        List<Transaction__c> transactions = new List<Transaction__c>();
        transactions.add(TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', 'Planned', System.today().addMonths(-1)));
        transactions.add(TestUtils.createNewTransaction(i.Id, i.Amount__c/2, 'Disbursement', System.today().addDays(-15)));
    
        // Perform validation
        Map<String, String> result = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(transactions), '[]');
        // Verify 
        // In this case the insertion should have been stopped,
        // so verify that we got back an error.
    
        System.assert(result.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_17, result.get('error'));

        // try to add transactions with the total amount higher tnan the loan amount
        transactions = new List<Transaction__c>();
        transactions.add(TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addMonths(-1)));
        transactions.add(TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addDays(1)));
        
        // Perform validation
        Map<String, String> result2 = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(transactions), '[]');
        // Verify 
        // In this case the insertion should have been stopped,
        // so verify that we got back an error.
        System.assert(result2.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_18, result2.get('error'));

        // i.Setup_Fee_Charging_Method__c = 'Deducted From Principal';
        // update i;

        // // Perform validation
        // Map<String, String> result3 = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(transactions), '[]');
        // // Verify 
        // // In this case the insertion should have been stopped,
        // // so verify that we got back an error.
        // System.assert(result3.containsKey('error'));
        // System.assertEquals('The total of amounts should not be higher than the Investment Amount minus Setup Fee Expected',
        //                     result3.get('error'));

    }

    @isTest static void test_run_validations_interest_rate_not_found() {      
        // create a new interest rate source
        Interest_Rate_Source__c irs = new Interest_Rate_Source__c(Name = 'Test Interest Rate Source');
        insert irs;

        // create interest rates
        Interest_Rate__c ir1 = TestUtils.createNewInterestRate(irs.Id, System.today().addDays(-10), 1);
        Interest_Rate__c ir2 = TestUtils.createNewInterestRate(irs.Id, System.today().addDays(-5), 2);
        
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct('Test Loan Product');
        lp.Interest_Rate_Source__c = 'Variable Interest';
        lp.Interest_Reference_Rate__c = irs.Id;
        lp.Interest_Rate_Review_Frequency__c = 'Monthly';
        lp.CBO_Default_Variable_Interest_Spread__c = true;

        insert new List<SObject>{ir1, ir2, lp};

        // create a new loan
        Investment__c i = TestUtils.createNewScheduledLoan(System.today().addMonths(-1), System.today());
        i.Loan_Product__c = lp.Id;
        i.Disbursement_Method__c = 'Full disbursement at start';
        i.Status__c = 'Inactive';
        update i;

        // try to add a disbursement
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addMonths(-1));
       
        // Perform validation
        Map<String, String> result = DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');
        // Verify 
        // In this case the insertion should have been stopped,
        // so verify that we got back an error.
        System.assert(result.containsKey('error'));
        System.assertEquals(System.Label.sfims.error_message_20, result.get('error'));
    
    }
}