force-app/main/default/objects/Indicator_Catalogue__c/Indicator_Catalogue__c.object-meta.xml
<CustomObject>
    <description>List of impact reporting indicators</description>
    <label>Indicator Catalogue</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Indicator Catalogue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <label>Indicator Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Outcome_Area__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Area__c</fullName>
    <label>Outcome Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Cross-Sector</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing/Community Facilities</fullName>
            </value>
            <value>
                <fullName>Land Conservation</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Employment, training and education</fullName>
            </value>
            <value>
                <fullName>Housing and local facilities</fullName>
            </value>
            <value>
                <fullName>Income and financial inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Standard_Custom__c.field-meta.xml
<CustomField>
    <fullName>Standard_Custom__c</fullName>
    <label>Standard - Custom</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <description>A custom indicator, not part of any standard library</description>
    <label>Custom</label>
</RecordType>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/Progress_Report_Indicators__c.object-meta.xml
<CustomObject>
    <label>Progress Report Indicator</label>
    <nameField>
        <displayFormat>PRI-{000000}</displayFormat>
        <label>Progress Report Indicators Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Report Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <formula>Indicator_Catalogue__r.Metrics_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indicator Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Progress_Report__c.field-meta.xml
<CustomField>
    <fullName>Progress_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Progress Report</label>
    <referenceTo>Progress_Report__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestProgressReportIndicatorTrigger.cls
@isTest
private class TestProgressReportIndicatorTrigger {
    @isTest static void test_set_default_fields() {
        Indicator_Catalogue__c ic = new Indicator_Catalogue__c(
            Active__c = true,
            RecordTypeId = Schema.SObjectType.sfims__Indicator_Catalogue__c.getRecordTypeInfosByName().get('Custom').getRecordTypeId(),
            Indicator_Name__c ='Indicator Custom - 00001',
            Indicator_Type__c = 'Text',
            Outcome_Area__c = 'Education',
            Standard_Custom__c = 'Custom'
        );

        Progress_Report__c pr = new Progress_Report__c();
        insert new List<SObject>{ ic, pr };

        Progress_Report_Indicators__c pri = new Progress_Report_Indicators__c(
            Progress_Report__c = pr.Id,
            Indicator_Catalogue__c = ic.Id
        );
        insert pri;

        Progress_Report_Indicators__c result = [
            SELECT Indicator_Type__c
            FROM Progress_Report_Indicators__c
            WHERE Id = :pri.Id
        ];

        System.assertEquals(result.Indicator_Type__c, ic.Indicator_Type__c);
    }
}