force-app/main/default/objects/Indicator_Catalogue__c/Indicator_Catalogue__c.object-meta.xml
<CustomObject>
    <description>List of impact reporting indicators</description>
    <label>Indicator Catalogue</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Indicator Catalogue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <label>Indicator Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Outcome_Area__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Area__c</fullName>
    <label>Outcome Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Cross-Sector</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing/Community Facilities</fullName>
            </value>
            <value>
                <fullName>Land Conservation</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Employment, training and education</fullName>
            </value>
            <value>
                <fullName>Housing and local facilities</fullName>
            </value>
            <value>
                <fullName>Income and financial inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Report_Template__c/Report_Template__c.object-meta.xml
<CustomObject>
    <label>Report Template</label>
    <nameField>
        <label>Report Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Report_Template_Indicator__c/Report_Template_Indicator__c.object-meta.xml
<CustomObject>
    <label>Report Template Indicator</label>
    <nameField>
        <displayFormat>RTI-{00000}</displayFormat>
        <label>Report Template Indicator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Template Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Report Template Indicators</relationshipLabel>
    <relationshipName>Report_Template_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report Template</label>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Report Template Indicators</relationshipLabel>
    <relationshipName>Report_Template_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestReportTemplateTrigger.cls
@isTest
private class TestReportTemplateTrigger {
    @isTest static void test_delete() {
        Test.startTest();
        Report_Template__c testTemplate = new Report_Template__c(Name = 'Template1', Active__c = true);
        insert testTemplate;
        Map<String, RecordTypeInfo> recordTypesMap = Schema.SObjectType.sfims__Indicator_Catalogue__c.getRecordTypeInfosByName();
        Id recordTypeIdCatalogue;
        for (String key : recordTypesMap.keySet()) {
            if (recordTypesMap.get(key).getName() != 'Master' ) {
                recordTypeIdCatalogue = recordTypesMap.get(key).getRecordTypeId();
                break;
            }
        }
        List<Indicator_Catalogue__c> listIndicators = new List<Indicator_Catalogue__c>();
        for (Integer i = 0; i < 3; i++) {
            listIndicators.add(new Indicator_Catalogue__c(Active__c = true, Indicator_Name__c = 'Indicator_Name__' + i,
                    Indicator_Type__c = 'Number', Outcome_Area__c = 'Health', RecordTypeId = recordTypeIdCatalogue));
        }
        insert listIndicators;
        List<Report_Template_Indicator__c> junctionObjects = new List<Report_Template_Indicator__c>();
        for (Integer j = 0; j < 3; j++) {
            junctionObjects.add(new Report_Template_Indicator__c(Indicator_Catalogue__c = listIndicators[j].Id, Report_Template__c = testTemplate.Id));
        }
        insert junctionObjects;
        System.assertEquals([SELECT Id FROM Report_Template_Indicator__c WHERE Report_Template__c = :testTemplate.Id].size(), 3);
        
        delete testTemplate;
        System.assert([SELECT Id FROM Report_Template_Indicator__c].isEmpty());
        Test.stopTest();
    }
}