force-app/main/default/objects/Indicator_Catalogue__c/Indicator_Catalogue__c.object-meta.xml
<CustomObject>
    <description>List of impact reporting indicators</description>
    <label>Indicator Catalogue</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Indicator Catalogue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <label>Indicator Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/Progress_Report_Indicators__c.object-meta.xml
<CustomObject>
    <label>Progress Report Indicator</label>
    <nameField>
        <displayFormat>PRI-{000000}</displayFormat>
        <label>Progress Report Indicators Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Report Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Currency__c</fullName>
    <label>Actual Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Number__c</fullName>
    <label>Actual Value (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Percentage__c</fullName>
    <label>Actual Value (Percentage)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Text__c</fullName>
    <label>Actual Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Text_Area_Long__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Text_Area_Long__c</fullName>
    <label>Actual Value (Text Area Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comment to the indicator filled in</description>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <formula>Indicator_Catalogue__r.Metrics_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indicator Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Progress_Report__c.field-meta.xml
<CustomField>
    <fullName>Progress_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Progress Report</label>
    <referenceTo>Progress_Report__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Currency__c</fullName>
    <label>Target Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Number__c</fullName>
    <label>Target Value (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Percentage__c</fullName>
    <label>Target Value (Percentage)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Text__c</fullName>
    <label>Target Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Text_Area_Long__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Text_Area_Long__c</fullName>
    <label>Target Value (Text Area Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Currency__c</fullName>
    <formula>Actual_Value_Currency__c - Target_Value_Currency__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Number__c</fullName>
    <formula>Actual_Value_Number__c - Target_Value_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Value (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Percentage__c</fullName>
    <formula>Actual_Value_Percentage__c - Target_Value_Percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Value (Percentage)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Text__c</fullName>
    <label>Variance Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Text_Area_Long__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Text_Area_Long__c</fullName>
    <label>Variance Value (Text Area Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/progressReportIndicatorsEditorController.cls
/*
 * @description         This is controller for component Progress Report Indicators Editor
 * @author              Alexey Eliseev
 * @component           progressReportIndicatorsEditor
 * @date                2/15/19
*/

public with sharing class progressReportIndicatorsEditorController {

    public class showException extends Exception {
    }

    public class progressReportIndicatorsEditorRowClass {
        public Id id;
        public String type;
        public String name;
        public List<Map<String, String>> cols;
    }

    @AuraEnabled
    public static String getProgressReportIndicators(Id progressReportId) {
        return JSON.serialize([
                SELECT Indicator_Catalogue__r.Indicator_Name__c,
                        Indicator_Catalogue__r.Indicator_Type__c,
                        Target_Value_Number__c, Target_Value_Currency__c, Target_Value_Text__c, Target_Value_Percentage__c, Target_Value_Text_Area_Long__c,
                        Actual_Value_Number__c, Actual_Value_Currency__c, Actual_Value_Text__c, Actual_Value_Percentage__c, Actual_Value_Text_Area_Long__c,
                        Variance_Value_Number__c, Variance_Value_Currency__c, Variance_Value_Text__c, Variance_Value_Percentage__c, Variance_Value_Text_Area_Long__c,
                        Comment__c
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :progressReportId
                ORDER BY Sequence_Number__c, Id
        ]);
    }

    @AuraEnabled
    public static Boolean saveProgressReportIndicators(String progressReportIndicatorsJSON) {
        Boolean returnValue = false;

        if (String.isNotBlank(progressReportIndicatorsJSON)) {
            List<progressReportIndicatorsEditorRowClass> indicatorRows = (List<progressReportIndicatorsEditorRowClass>) JSON.deserialize(progressReportIndicatorsJSON, List<progressReportIndicatorsEditorRowClass>.class);
            List<Progress_Report_Indicators__c> updateListIndicators = new List<Progress_Report_Indicators__c>();

            Integer indicatorRowsSize = indicatorRows.size();
            if (indicatorRowsSize > 0) {
                for (Integer i = 0; i < indicatorRowsSize; i++) {
                    Progress_Report_Indicators__c updateItem = new Progress_Report_Indicators__c(Id = indicatorRows[i].id);

                    List<String> fieldValueMap = new List<String>();
                    Integer colSize = indicatorRows[i].cols.size();

                    List<String> ignor = new List<String> {
                            'sfims__Variance_Value_Currency__c',
                            'sfims__Variance_Value_Number__c',
                            'sfims__Variance_Value_Percentage__c'
                    };

                    if (colSize > 0) {
                        for (Map<String, String> j : indicatorRows[i].cols) {

                            if (ignor.indexOf(j.get('name')) != -1) {
                                continue;
                            }

                            if (j.get('name') == 'sfims__Comment__c') {
                                updateItem.put('Comment__c', j.get('value'));
                            } else {

                                switch on indicatorRows[i].type {
                                    when 'Number' {
                                        if (String.isBlank(j.get('value'))) {
                                            //continue;
                                            j.put('value', '0');
                                        }
                                        updateItem.put(j.get('name'), Decimal.valueOf(j.get('value')));
                                    }
                                    when 'Currency' {
                                        if (String.isBlank(j.get('value'))) {
                                            //continue;
                                            j.put('value', '0');
                                        }
                                        updateItem.put(j.get('name'), Decimal.valueOf(j.get('value')));
                                    }
                                    when 'Percentage'{
                                        if (String.isBlank(j.get('value'))) {
                                            //continue;
                                            j.put('value', '0');
                                        }
                                        updateItem.put(j.get('name'), Decimal.valueOf(j.get('value')));
                                    }
                                    when 'Text'{
                                        updateItem.put(j.get('name'), j.get('value'));
                                    }
                                    when 'Text Area (Long)'{
                                        updateItem.put(j.get('name'), j.get('value'));
                                    }
                                    when else {
                                        //updateItem.put(j.get('name'), j.get('value'));
                                    }
                                }
                            }
                        }

                        updateListIndicators.add(updateItem);
                        //system.debug(updateListIndicators);
                    }
                }
            }

            if (updateListIndicators.size() > 0) {
                try {
                    update updateListIndicators;
                    returnValue = true;
                } catch (Exception e) {
                    throw new showException(System.Label.sfims.error_message_6, e);
                }
            }
        }

        return returnValue;
    }
}