force-app/main/default/objects/Indicator_Catalogue__c/Indicator_Catalogue__c.object-meta.xml
<CustomObject>
    <description>List of impact reporting indicators</description>
    <label>Indicator Catalogue</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Indicator Catalogue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <label>Indicator Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Outcome_Area__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Area__c</fullName>
    <label>Outcome Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Cross-Sector</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing/Community Facilities</fullName>
            </value>
            <value>
                <fullName>Land Conservation</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Employment, training and education</fullName>
            </value>
            <value>
                <fullName>Housing and local facilities</fullName>
            </value>
            <value>
                <fullName>Income and financial inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/recordTypes/IRIS.recordType-meta.xml
<RecordType>
    <fullName>IRIS</fullName>
    <active>true</active>
    <description>Impact Measurement library created by the Global Impact Investing Network (GIIN)</description>
    <label>IRIS</label>
</RecordType>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/Progress_Report_Indicators__c.object-meta.xml
<CustomObject>
    <label>Progress Report Indicator</label>
    <nameField>
        <displayFormat>PRI-{000000}</displayFormat>
        <label>Progress Report Indicators Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Report Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Currency__c</fullName>
    <label>Actual Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Number__c</fullName>
    <label>Actual Value (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Percentage__c</fullName>
    <label>Actual Value (Percentage)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Text__c</fullName>
    <label>Actual Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Actual_Value_Text_Area_Long__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value_Text_Area_Long__c</fullName>
    <label>Actual Value (Text Area Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comment to the indicator filled in</description>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <formula>Indicator_Catalogue__r.Metrics_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indicator Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Progress_Report__c.field-meta.xml
<CustomField>
    <fullName>Progress_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Progress Report</label>
    <referenceTo>Progress_Report__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Currency__c</fullName>
    <label>Target Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Number__c</fullName>
    <label>Target Value (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Percentage__c</fullName>
    <label>Target Value (Percentage)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Text__c</fullName>
    <label>Target Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Target_Value_Text_Area_Long__c.field-meta.xml
<CustomField>
    <fullName>Target_Value_Text_Area_Long__c</fullName>
    <label>Target Value (Text Area Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Currency__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Currency__c</fullName>
    <formula>Actual_Value_Currency__c - Target_Value_Currency__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Value (Currency)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Number__c</fullName>
    <formula>Actual_Value_Number__c - Target_Value_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Value (Number)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Percentage__c</fullName>
    <formula>Actual_Value_Percentage__c - Target_Value_Percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Variance Value (Percentage)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Text__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Text__c</fullName>
    <label>Variance Value (Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Variance_Value_Text_Area_Long__c.field-meta.xml
<CustomField>
    <fullName>Variance_Value_Text_Area_Long__c</fullName>
    <label>Variance Value (Text Area Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestProgReportIndicatorsEditorController.cls
/*
 * @description         This is unit test for Progress Report Indicators Editor
 * @author              Alexey Eliseev
 * @component           progressReportIndicatorsEditor
 * @date                2/15/19
*/

@isTest
private with sharing class TestProgReportIndicatorsEditorController {
    @isTest static void test_ProgressReportIndicatorsEditorController() {
        Test.startTest();

        Map<String, RecordTypeInfo> recorsTypesMap = Schema.SObjectType.sfims__Indicator_Catalogue__c.getRecordTypeInfosByName();
        Id recordTypeIdCatalogue;
        for (String key : recorsTypesMap.keySet()) {
            if ((string)recorsTypesMap.get(key).getName() == 'IRIS') {
                recordTypeIdCatalogue = recorsTypesMap.get(key).getRecordTypeId();
                break;
            }
        }

        List<Indicator_Catalogue__c> listIndicators = new List<Indicator_Catalogue__c>();
        for (Integer i = 0; i < 10; i++) {
            listIndicators.add(new Indicator_Catalogue__c(Active__c = true, Indicator_Name__c = 'Indicator_Name__' + i,
                    Indicator_Type__c = 'Number', Outcome_Area__c = 'Agriculture', RecordTypeId = recordTypeIdCatalogue));
        }
        insert listIndicators;

        List<sfims__Progress_Report__c> listReports = new List<sfims__Progress_Report__c>();
        for (Integer i = 0; i < 3; i++) {
            listReports.add(new sfims__Progress_Report__c());
        }
        insert listReports;

        List<Progress_Report_Indicators__c> listProgressIndicators = new List<Progress_Report_Indicators__c>();
        for (Integer i = 0; i < 10; i++) {
            listProgressIndicators.add(new Progress_Report_Indicators__c(Progress_Report__c = listReports[0].Id, Indicator_Catalogue__c = listIndicators[i].Id));
        }

        insert listProgressIndicators;

        system.assertEquals('[]', progressReportIndicatorsEditorController.getProgressReportIndicators(null), 'Invalid results Progress Report Indicators');

        try {
            progressReportIndicatorsEditorController.getProgressReportIndicators('test');
        } catch (exception e) {
            system.assertEquals(string.valueOf(e), 'System.StringException: Invalid id: test');
        }

        system.assertEquals(JSON.serialize([
                SELECT Indicator_Catalogue__r.Indicator_Name__c,
                        Indicator_Catalogue__r.Indicator_Type__c,
                        Target_Value_Number__c, Target_Value_Currency__c, Target_Value_Text__c, Target_Value_Percentage__c, Target_Value_Text_Area_Long__c,
                        Actual_Value_Number__c, Actual_Value_Currency__c, Actual_Value_Text__c, Actual_Value_Percentage__c, Actual_Value_Text_Area_Long__c,
                        Variance_Value_Number__c, Variance_Value_Currency__c, Variance_Value_Text__c, Variance_Value_Percentage__c, Variance_Value_Text_Area_Long__c,
                        Comment__c
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :listReports[0].Id
        ]), progressReportIndicatorsEditorController.getProgressReportIndicators(listReports[0].Id), 'Invalid results Progress Report Indicators');

        system.assertEquals(false, progressReportIndicatorsEditorController.saveProgressReportIndicators(null), 'Invalid save results');

        List<progressReportIndicatorsEditorController.progressReportIndicatorsEditorRowClass> testClass = new List<progressReportIndicatorsEditorController.progressReportIndicatorsEditorRowClass>();


        List<String> types = new List<String>{
                'Number', 'Currency', 'Percentage', 'Text', 'Text Area (Long)'
        };
        List<String> names = new List<String>{
                'sfims__Actual_Value_Number__c', 'sfims__Target_Value_Number__c', 'sfims__Variance_Value_Number__c', 'sfims__Comment__c'
        };
        List<String> namesText = new List<String>{
                'sfims__Actual_Value_Text__c', 'sfims__Target_Value_Text__c', 'sfims__Variance_Value_Text__c', 'sfims__Comment__c'
        };

        Integer listProgressIndicatorsSize = listProgressIndicators.size();
        for (Integer i = 0; i < 5; i++) {

            List<Map<String, String>> testCols = new List<Map<String, String>>();

            for (Integer k = 0; k < 4; k++) {
                Map<String, String> itemMap;
                if ((types[i] == 'Text') || (types[i] == 'Text Area (Long)')) {
                    itemMap = new Map<String, String>{
                            'name' => namesText[k], 'value' => '', 'reset' => ''
                    };
                } else {
                    itemMap = new Map<String, String>{
                            'name' => names[k], 'value' => '', 'reset' => ''
                    };
                }
                testCols.add(itemMap);
            }

            progressReportIndicatorsEditorController.progressReportIndicatorsEditorRowClass testItemClass = new progressReportIndicatorsEditorController.progressReportIndicatorsEditorRowClass();
            testItemClass.id = listProgressIndicators[i].Id;
            testItemClass.type = types[i];
            testItemClass.name = 'TestName' + i;
            testItemClass.cols = testCols;

            testClass.add(testItemClass);
        }

        system.assertEquals(true, progressReportIndicatorsEditorController.saveProgressReportIndicators(JSON.serialize(testClass)), 'Invalid save results');

        delete [SELECT Id FROM Progress_Report_Indicators__c WHERE Id =: testClass[0].Id];
        for (progressReportIndicatorsEditorController.progressReportIndicatorsEditorRowClass p : testClass) {
            for (Integer k = 0; k < 4; k++) {
                p.cols[k].put('value', '1');
            }
        }

        try {
            progressReportIndicatorsEditorController.saveProgressReportIndicators(JSON.serialize(testClass));
        } catch (exception e) {
            system.assertEquals(string.valueOf(e), 'showException:[]: ' + System.Label.sfims.error_message_6);
        }

        Test.stopTest();
    }
}