force-app/main/default/objects/Indicator_Catalogue__c/Indicator_Catalogue__c.object-meta.xml
<CustomObject>
    <description>List of impact reporting indicators</description>
    <label>Indicator Catalogue</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Indicator Catalogue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <description>The definition of the metric.  Please note that bolded words are glossary terms that can be found in the glossary tab.</description>
    <label>Definition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <label>Indicator Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Outcome_Area__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Area__c</fullName>
    <label>Outcome Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Cross-Sector</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing/Community Facilities</fullName>
            </value>
            <value>
                <fullName>Land Conservation</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Employment, training and education</fullName>
            </value>
            <value>
                <fullName>Housing and local facilities</fullName>
            </value>
            <value>
                <fullName>Income and financial inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Standard_Custom__c.field-meta.xml
<CustomField>
    <fullName>Standard_Custom__c</fullName>
    <label>Standard - Custom</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Report_Template__c/Report_Template__c.object-meta.xml
<CustomObject>
    <label>Report Template</label>
    <nameField>
        <label>Report Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Template_Indicator__c/Report_Template_Indicator__c.object-meta.xml
<CustomObject>
    <label>Report Template Indicator</label>
    <nameField>
        <displayFormat>RTI-{00000}</displayFormat>
        <label>Report Template Indicator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Template Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Report Template Indicators</relationshipLabel>
    <relationshipName>Report_Template_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report Template</label>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Report Template Indicators</relationshipLabel>
    <relationshipName>Report_Template_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Standard_Custom__c.field-meta.xml
<CustomField>
    <fullName>Standard_Custom__c</fullName>
    <formula>text(Indicator_Catalogue__r.Standard_Custom__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Standard-Custom</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SelectedIndicatorsController.cls
/* Report Template functionality * @author Alexey Eliseev * @date 2/11/19 * component SelectedIndicators */

public without sharing class SelectedIndicatorsController {

    public class CommonException extends Exception {
    }

    @AuraEnabled
    public static String loadSelectedIndicators(Id templateId) {
        String response = '';
        try {
            IndicatorCatalogsController.getIndicatorCatalogsDataClass indicatorCatalogsData = new IndicatorCatalogsController.getIndicatorCatalogsDataClass();

            indicatorCatalogsData.allIndicators = new List<Indicator_Catalogue__c>();
            Set<Id> indicatorId = new Set<Id>();
            List<Report_Template_Indicator__c> junctionObject = [
                    SELECT Indicator_Catalogue__c
                    FROM Report_Template_Indicator__c
                    WHERE Report_Template__c = :templateId
                    ORDER BY Sequence_Number__c, Id
            ];
            for (Report_Template_Indicator__c i : junctionObject) {
                indicatorId.add(i.Indicator_Catalogue__c);
            }
            List<Indicator_Catalogue__c> results = [
                    SELECT Indicator_Name__c, Indicator_Type__c, RecordTypeId, RecordType.Name, Standard_Custom__c, Definition__c, Outcome_Area__c
                    FROM Indicator_Catalogue__c
                    WHERE Id IN :indicatorId
            ];
            Map<Id, Indicator_Catalogue__c> resultsMap = new Map<Id, Indicator_Catalogue__c>(results);
            for (Id i : indicatorId) {
                if (resultsMap.containsKey(i)) {
                    indicatorCatalogsData.allIndicators.add(resultsMap.get(i));
                }
            }

            /*
            indicatorCatalogsData.allIndicators = new List<Indicator_Catalogue__c>();
            List<sfims__Report_Template_Indicator__c> indicators = [
                    SELECT Id,
                            Indicator_Catalogue__r.Indicator_Name__c,
                            Indicator_Catalogue__r.Indicator_Type__c,
                            Indicator_Catalogue__r.RecordTypeId,
                          //  Indicator_Catalogue__r.RecordType.Name,
                            Indicator_Catalogue__r.Standard_Custom__c,
                            Indicator_Catalogue__r.Definition__c,
                            Indicator_Catalogue__r.Outcome_Area__c
                    FROM sfims__Report_Template_Indicator__c
                    WHERE Report_Template__c = :templateId
                    ORDER BY Id
            ];
            if (indicators.size() > 0) {
                List<Indicator_Catalogue__c> results = new List<Indicator_Catalogue__c>();
                for (sfims__Report_Template_Indicator__c r : indicators) {
                    results.add(new Indicator_Catalogue__c(
                            Id = r.Indicator_Catalogue__r.Id,
                            Indicator_Name__c = r.Indicator_Catalogue__r.Indicator_Name__c,
                            Indicator_Type__c = r.Indicator_Catalogue__r.Indicator_Type__c,
                            RecordTypeId = r.Indicator_Catalogue__r.RecordTypeId,
                        //    RecordType.Name = r.Indicator_Catalogue__r.RecordType.Name,
                            Standard_Custom__c = r.Indicator_Catalogue__r.Standard_Custom__c,
                            Definition__c = r.Indicator_Catalogue__r.Definition__c,
                            Outcome_Area__c = r.Indicator_Catalogue__r.Outcome_Area__c
                    ));
                }
                 indicatorCatalogsData.allIndicators = results;
            }
            */

            indicatorCatalogsData.allRecordTypes = ReportTemplateController.getAllRecordTypes();
            response = JSON.serialize(indicatorCatalogsData);
        } catch (Exception err) {
            throw new CommonException(err.getMessage());
        }
        return response;
    }
}