force-app/main/default/objects/Account/recordTypes/Investee_Account.recordType-meta.xml
<RecordType>
    <fullName>Investee_Account</fullName>
    <active>true</active>
    <label>Investee Account</label>
</RecordType>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/classes/TestLoanStatusController.cls
@isTest
private class TestLoanStatusController {

    // not in use

    // @isTest static void test_loan_writeoff() {
	// 	Account a = TestUtils.createAccount('Investee_Account','test',null);
    //     // initially total paid = 0
    //     Investment__c i = TestUtils.createNewScheduledLoan(a.Id);
    //     i.Status__c = 'Active';
    //     update i;
        
    //     LoanStatusController.loanExecuteWriteOff(i.Id);

    //     i = [Select Id, Status__c From Investment__c Where Id = :i.Id];
    //     system.assertEquals('Closed - Written Off', i.Status__c);

    //     // verify that a loan with status not-active cannot be written off
    //     try{
    //         LoanStatusController.loanExecuteWriteOff(i.Id);
    //         System.assert(false,'Expected an exception (wrong loan status');
    //     } catch (AuraHandledException e){
    //         // expected
    //         system.assertEquals(true,true);
    //     }
        


    //     // test the same with unauthorized user
	// 	User newUser = TestUtils.ensureRestrictedUser();
	// 	System.runAs(newUser){
	// 		try{
	// 			LoanStatusController.loanExecuteWriteOff(i.Id);
	// 			System.assert(false,'Expected an exception (unauthorized user');
	// 		} catch (AuraHandledException e){
    //             // expected
    //             system.assertEquals(true,true);
    //         }
    //     }          
    // }
}