force-app/main/default/objects/Account/recordTypes/Investee_Account.recordType-meta.xml
<RecordType>
    <fullName>Investee_Account</fullName>
    <active>true</active>
    <label>Investee Account</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Assessment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Stage__c</fullName>
    <description>This field can be used to define assessment stages within the application stages. This way you could define multiple rounds of assessments within 1 stage. Use dependent picklists to manage which Assessment Stages belong to which Application Stage.</description>
    <inlineHelpText>This field can be used to define assessment stages within the application stages. This way you could define multiple rounds of assessments within 1 stage. Use dependent picklists to manage which Assessment Stages belong to which Application Stage.</inlineHelpText>
    <label>Assessment Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application Review</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Approved (Pending Contract)</label>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Application Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Implementation</fullName>
                <isActive>false</isActive>
                <label>Implementation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment of an application in a certain stage.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the score for 1 criteria for 1 assessor for an assessment</description>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Assessment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment_Criteria_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Criteria Definition</label>
    <referenceTo>Assessment_Criteria_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/Assessment_Criteria_Definition__c.object-meta.xml
<CustomObject>
    <description>The definition of a criteria that belongs to 1 assessment stage definition and will be instantiated into each assessment that is generated for the particular stage.</description>
    <label>Assessment Criteria Definition</label>
    <nameField>
        <label>Assessment Criteria Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Assessment_Stage_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Stage_Definition__c</fullName>
    <label>Assessment Stage Definition</label>
    <referenceTo>Assessment_Stage_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria Definitions</relationshipLabel>
    <relationshipName>Assessment_Criteria_Definitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/Assessment_Stage_Definition__c.object-meta.xml
<CustomObject>
    <description>Defines an application stage for which assessments are needed. All assessments selected for this stage will be added to any application reaching the stage (within the applicable Fund)</description>
    <label>Assessment Stage Definition</label>
    <nameField>
        <label>Assessment Stage Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Stage Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fund to which this assessment definition is applicable</description>
    <inlineHelpText>The fund to which this assessment definition is applicable</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Assessment Stage Definitions</relationshipLabel>
    <relationshipName>Assessment_Stage_Definitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Funds are used to group individual investments to an overall fund. In reports and dashboards Funds are used as an important filter to look at a portfolio per fund.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/Fund_Assessor__c.object-meta.xml
<CustomObject>
    <description>Junction object that links Assessors to Funds</description>
    <label>Fund Assessor</label>
    <nameField>
        <displayFormat>FA-{00000000}</displayFormat>
        <label>Fund Assessor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Assessors</relationshipLabel>
    <relationshipName>Fund_Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/Stage_Assessment__c.object-meta.xml
<CustomObject>
    <description>This is the placeholder for the set of assessments done at a particular stage in the Application process.</description>
    <label>Stage Assessment</label>
    <nameField>
        <label>Stage Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The application being assessed</description>
    <inlineHelpText>The application being assessed</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Stage Assessments</relationshipLabel>
    <relationshipName>Stage_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Assessment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Stage__c</fullName>
    <label>Assessment Stage</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The application stage to which this assessment belongs.</description>
    <inlineHelpText>The application stage to which this assessment belongs.</inlineHelpText>
    <label>Stage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestStageAssessmentTrigger.cls
/** Application Assessment functionality * @author Alexey Eliseev * @date 10/8/19 **/

@IsTest
public with sharing class TestStageAssessmentTrigger {
    @IsTest static void test_StageAssessmentTrigger() {
        Test.startTest();

        // insert Fund and Account
        Fund__c fund1 = TestUtils.createFund('fund1');
        Account acc = TestUtils.createAccount('Investee_Account');
        insert new List<SObject>{ fund1, acc };

        // insert Fund Assessors
        Fund_Assessor__c fundAssessor1 = TestUtils.createFundAssessor(fund1);
        insert fundAssessor1;

        // insert Assessment Stage Definitions
        Assessment_Stage_Definition__c stage1 = TestUtils.createAssessmentStageDefinition(fund1, 'Application', null, 'Manual selection', 3);
        Assessment_Stage_Definition__c stage2 = TestUtils.createAssessmentStageDefinition(fund1, 'Application', 'Tier 1', 'Manual selection', 5);
        insert new List<Assessment_Stage_Definition__c>{
                stage1, stage2
        };

        // insert Assessment Criteria Definition__c
        Assessment_Criteria_Definition__c criteria1 = TestUtils.createAssessmentCriteriaDefinition(stage1, 'Rating');
        Assessment_Criteria_Definition__c criteria2 = TestUtils.createAssessmentCriteriaDefinition(stage1, 'Text');
        insert new List<Assessment_Criteria_Definition__c>{
                criteria1, criteria2
        };

        // Insert new Applications - true
        Application__c application1 = TestUtils.createNewApplication(acc.Id);
        application1.Name = 'Name-12345678910';
        application1.Fund__c = fund1.Id;
        application1.Stage__c = 'Application';
        insert application1;
        System.assertEquals(1, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c WHERE Assessment_Stage__c = NULL].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(3, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(6, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');
        System.assertEquals('Application-Name-12345678910', [SELECT Name FROM Stage_Assessment__c WHERE Assessment_Stage__c = NULL].Name, 'Invalid Stage_Assessment__c name');

        // Insert new Application - true
        Application__c application2 = TestUtils.createNewApplication(acc.Id);
        application2.Name = 'Name-123456789101112131415161718192021222324252627282930313233343536373839404142';
        application2.Fund__c = fund1.Id;
        application2.Stage__c = 'Application';
        application2.Assessment_Stage__c = 'Tier 1';
        insert application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c WHERE Assessment_Stage__c = 'Tier 1'].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(8, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(6, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');
        System.assertEquals('Application-Tier 1-Name-12345678910111213141516171819202122232425262728293031323', [SELECT Name FROM Stage_Assessment__c WHERE Assessment_Stage__c = 'Tier 1'].Name, 'Invalid Stage_Assessment__c name');

        Test.stopTest();
    }
}