force-app/main/default/objects/Account/recordTypes/Investee_Account.recordType-meta.xml
<RecordType>
    <fullName>Investee_Account</fullName>
    <active>true</active>
    <label>Investee Account</label>
</RecordType>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/From_period__c.field-meta.xml
<CustomField>
    <fullName>From_period__c</fullName>
    <label>From period:</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/Progress_Report_Indicators__c.object-meta.xml
<CustomObject>
    <label>Progress Report Indicator</label>
    <nameField>
        <displayFormat>PRI-{000000}</displayFormat>
        <label>Progress Report Indicators Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Report Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Progress_Report__c.field-meta.xml
<CustomField>
    <fullName>Progress_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Progress Report</label>
    <referenceTo>Progress_Report__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestProgressReportTriggerHandler.cls
@isTest
private class TestProgressReportTriggerHandler {
    
    @isTest static void test_progress_report_methods() {
        User platformUser = TestUtils.createPlatformUser();
        system.runAs(platformUser){        
            Account a = TestUtils.createAccount('Investee_Account','test',null);
            Application__c appl = TestUtils.createNewApplication(a.Id);

            Progress_Report__c pr = new Progress_Report__c();
            pr.Application__c = appl.Id;
            insert pr;

            System.assertEquals(a.Id,[Select Organisation__c from Progress_Report__c Where Application__c = :appl.Id].organisation__c);

            pr.From_period__c = system.today();
            update pr;
                
            delete pr;
        }    
        
    }

    @isTest static void test_delete_child_records() {
        Progress_Report__c pr = new Progress_Report__c();
        insert pr;
        Progress_Report_Indicators__c pri = new Progress_Report_Indicators__c(Progress_Report__c = pr.Id);
        insert pri;

        delete pr;
        
        List<Progress_Report_Indicators__c> progressReportIndicators = [
            SELECT Id 
            FROM Progress_Report_Indicators__c
            WHERE Progress_Report__c = :pr.Id
        ];
        
        System.assertEquals(0, progressReportIndicators.size());
    }
}