force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Contract Object for Singlify</description>
    <label>Contract</label>
    <nameField>
        <displayFormat>CNT-{00000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Signed - Open</fullName>
            </value>
            <value>
                <fullName>Singed - Closed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
            <value>
                <fullName>External Review</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone_Configuration__c/Milestone_Configuration__c.object-meta.xml
<CustomObject>
    <description>Milestone Configuration object sets the stage/status changes on the Application, Contract and Investment object that will trigger the creation of a Milestone History record in the Milestone History object</description>
    <label>Milestone Configuration</label>
    <nameField>
        <displayFormat>MC-{00000000}</displayFormat>
        <label>Milestone Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Configuration__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence number of the Stage/Status change on the Milestone History object. This sequence number is used to determine how long a Milestone has stayed in a certain Stage/Status</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/Milestone_History__c.object-meta.xml
<CustomObject>
    <description>Milestone History object tracks all the milestone an organisation goes through from Application, Contract and Investment record. This is one of the key reporting objects used within the IMS application</description>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>MH-{00000000}</displayFormat>
        <label>Milestone History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_History__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Application that this Milestone belongs to</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Milestone Histories</relationshipLabel>
    <relationshipName>Milestone_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract record that this milestone belongs to</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Milestone Histories</relationshipLabel>
    <relationshipName>Milestone_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Days_in_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Milestone__c</fullName>
    <description>The number of days that the record was in this milestone (automatically calculated field with code)</description>
    <label>Days in Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>The name of the Milestone Stage/Status</description>
    <label>Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <description>The Date the milestone moved into the specific stage/status</description>
    <label>Milestone Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence number of this milestone record for this application</description>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestContractTriggerHandler.cls
@isTest
private class TestContractTriggerHandler {
    @isTest static void test_contract_status_edited() {

        User platformUser = TestUtils.createPlatformUser();
        
        Milestone_Configuration__c mc1 = TestUtils.createNewMilestoneConfiguration('Contract', 'Draft', 'Contract Internal Review', 6);
        Milestone_Configuration__c mc2 = TestUtils.createNewMilestoneConfiguration('Contract', 'Signed - Open', 'Contract External Review', 7);
            
        Application__c app = TestUtils.createNewApplication();
        Contract__c c = new Contract__c(
            Status__c = 'Draft'
        );
        
        // admin creates the setup
        System.runAs(new User(ID = UserInfo.getUserID())){            
            insert new List<SObject>{ mc1, mc2, app };
            c.Application__c = app.Id;
            insert c;

            List<Milestone_History__c> mhList = [
                SELECT Milestone__c, Milestone_Date__c, Days_in_Milestone__c, Contract__c, Application__c, Sequence__c
                FROM Milestone_History__c
                WHERE Contract__c =: c.Id
                ORDER BY Sequence__c DESC
            ];

            System.assertEquals(1, mhList.size());
            System.assertEquals(c.Id, mhList[0].Contract__c);
            System.assertEquals('Contract Internal Review', mhList[0].Milestone__c);
        }
        
        // platform user triggers the logic
        system.runAs(platformUser){
            c.Status__c = 'Signed - Open';
            update c;
        }
        List<Milestone_History__c> mhList2 = [
            SELECT Milestone__c, Milestone_Date__c, Days_in_Milestone__c, Contract__c, Application__c, Sequence__c
            FROM Milestone_History__c
            WHERE Contract__c =: c.Id
            ORDER BY Sequence__c DESC
        ];

        System.assertEquals(2, mhList2.size());
        System.assertEquals(c.Id, mhList2[0].Contract__c);
        System.assertEquals(app.Id, mhList2[0].Application__c);
        System.assertEquals(null, mhList2[1].Days_in_Milestone__c);

    }
}