force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application Review</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Approved (Pending Contract)</label>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Application Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Implementation</fullName>
                <isActive>false</isActive>
                <label>Implementation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment of an application in a certain stage.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Stage_Assessment_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Stage_Assessment_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stage Assessment</label>
    <referenceTo>Stage_Assessment__c</referenceTo>
    <relationshipLabel>Assessments (Stage Assessment)</relationshipLabel>
    <relationshipName>Assessments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the score for 1 criteria for 1 assessor for an assessment</description>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Assessment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment_Criteria_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Criteria Definition</label>
    <referenceTo>Assessment_Criteria_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Selected_Picklist_Value__c.field-meta.xml
<CustomField>
    <fullName>Selected_Picklist_Value__c</fullName>
    <label>Selected Picklist Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/Assessment_Criteria_Definition__c.object-meta.xml
<CustomObject>
    <description>The definition of a criteria that belongs to 1 assessment stage definition and will be instantiated into each assessment that is generated for the particular stage.</description>
    <label>Assessment Criteria Definition</label>
    <nameField>
        <label>Assessment Criteria Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Assessment_Stage_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Stage_Definition__c</fullName>
    <label>Assessment Stage Definition</label>
    <referenceTo>Assessment_Stage_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria Definitions</relationshipLabel>
    <relationshipName>Assessment_Criteria_Definitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Maximum_Rating__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Rating__c</fullName>
    <label>Maximum Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Minimum_Rating__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Rating__c</fullName>
    <label>Minimum Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <inlineHelpText>Use a semicolon as a separator</inlineHelpText>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/Assessment_Stage_Definition__c.object-meta.xml
<CustomObject>
    <description>Defines an application stage for which assessments are needed. All assessments selected for this stage will be added to any application reaching the stage (within the applicable Fund)</description>
    <label>Assessment Stage Definition</label>
    <nameField>
        <label>Assessment Stage Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Stage Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fund to which this assessment definition is applicable</description>
    <inlineHelpText>The fund to which this assessment definition is applicable</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Assessment Stage Definitions</relationshipLabel>
    <relationshipName>Assessment_Stage_Definitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Funds are used to group individual investments to an overall fund. In reports and dashboards Funds are used as an important filter to look at a portfolio per fund.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Assessment__c/Stage_Assessment__c.object-meta.xml
<CustomObject>
    <description>This is the placeholder for the set of assessments done at a particular stage in the Application process.</description>
    <label>Stage Assessment</label>
    <nameField>
        <label>Stage Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The application being assessed</description>
    <inlineHelpText>The application being assessed</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Stage Assessments</relationshipLabel>
    <relationshipName>Stage_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The application stage to which this assessment belongs.</description>
    <inlineHelpText>The application stage to which this assessment belongs.</inlineHelpText>
    <label>Stage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAssessmentCriteriaTrigger.cls
@IsTest
private with sharing class TestAssessmentCriteriaTrigger {
    @IsTest static void test_run_validations() {
        // insert Fund
        Fund__c fund = TestUtils.createFund('Test Fund');
        insert fund;

        // insert Fund Assessors
        insert TestUtils.createFundAssessor(fund);

        // insert Assessment Stage Definitions
        Assessment_Stage_Definition__c asd = TestUtils.createAssessmentStageDefinition(fund, 'Application', null, 'Manual selection', 2);
        insert asd;

        // insert Assessment Criteria Definition__c
        Assessment_Criteria_Definition__c acd1 = TestUtils.createAssessmentCriteriaDefinition(asd, 'Rating');
        acd1.Name = 'AssessmentCriteria1';
        acd1.Minimum_Rating__c = 2;
        acd1.Maximum_Rating__c = 8;
        Assessment_Criteria_Definition__c acd2 = TestUtils.createAssessmentCriteriaDefinition(asd, 'Picklist');
        acd2.Name = 'AssessmentCriteria2';
        acd2.Picklist_Values__c = 'Value 1; Value 2; Value 3';
        insert new List<Assessment_Criteria_Definition__c>{acd1, acd2};

        // insert new Applications - true
        Application__c application = TestUtils.createNewApplication();
        application.Name = 'Name-12345678910';
        application.Fund__c = fund.Id;
        application.Stage__c = 'Application';
        insert application;
        
        // check results
        List<Assessment_Criteria__c> acList1 = [
            SELECT Rating__c, Assessment__c 
            FROM Assessment_Criteria__c 
            WHERE Name = 'AssessmentCriteria1' AND Type__c = 'Rating'
        ];

        List<Assessment_Criteria__c> acList2 = [
            SELECT Selected_Picklist_Value__c, Assessment__c
            FROM Assessment_Criteria__c 
            WHERE Name = 'AssessmentCriteria2' AND Type__c = 'Picklist'
        ];
        
        System.assertEquals(2, acList1.size(), 'Invalid Assessment_Criteria__c name');
        System.assertEquals(2, acList2.size(), 'Invalid Assessment_Criteria__c name');

        // update Rating
        acList1[0].Rating__c = 1;
        acList1[1].Rating__c = 9;

        // Perform test
        List<Database.SaveResult> resultList = Database.update(acList1, false);
        // Verify 
        // In this case the update should have been stopped by the trigger,
        // so verify that we got back an error.
        
        for (Database.SaveResult result : resultList) {
            System.assert(!result.isSuccess());
            System.assert(result.getErrors().size() > 0);
            System.assertEquals('Out of allowed range (Minimum Rating: ' + acd1.Minimum_Rating__c.intValue() + 
                ', Maximum Rating: ' + acd1.Maximum_Rating__c.intValue() + ')', result.getErrors()[0].getMessage());

        }

        // update Selected Picklist Value
        acList2[0].Selected_Picklist_Value__c = 'Value 4';

        // Perform test
        Database.SaveResult result1 = Database.update(acList2[0], false);
        // Verify 
        // In this case the update should have been stopped by the trigger,
        // so verify that we got back an error.
        
        System.assert(!result1.isSuccess());
        System.assert(result1.getErrors().size() > 0);
        System.assertEquals(System.Label.sfims.part_of_error_message_10 + ' "' + acList2[0].Selected_Picklist_Value__c + 
            '" '  + System.Label.sfims.part_of_error_message_11 + '.', result1.getErrors()[0].getMessage());

        // Block editing Assessment Criteria if Assessment Status is 'Approved' or 'Completed'.
        List<Assessment__c> assessments = [
            SELECT Status__c
            FROM Assessment__c
            WHERE Stage_Assessment_Lookup__r.Application__c = :application.Id
        ];
        System.assertEquals(2, assessments.size());

        // change the status
        assessments[0].Status__c = 'Approved';
        assessments[1].Status__c = 'Completed';
        update assessments;
        
        // try to edit assessment criteria
        acList1[0].Rating__c = 5;
        acList2[0].Selected_Picklist_Value__c = 'Value 2';
        
        // Perform test
        List<Database.SaveResult> resultList2 = Database.update(new List<Assessment_Criteria__c>{acList1[0], acList2[0]}, false);
        // Verify 
        // In this case the update should have been stopped by the trigger,
        // so verify that we got back an error.
        
        for (Database.SaveResult result : resultList2) {
            System.assert(!result.isSuccess());
            System.assert(result.getErrors().size() > 0);
            System.assertEquals(System.Label.sfims.error_message_39, result.getErrors()[0].getMessage());

        }
    }
}