force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report Template</label>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/Indicator_Catalogue__c.object-meta.xml
<CustomObject>
    <description>List of impact reporting indicators</description>
    <label>Indicator Catalogue</label>
    <nameField>
        <displayFormat>IC-{00000000}</displayFormat>
        <label>Indicator Catalogue Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Indicator Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <label>Indicator Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Indicator_Catalogue__c/fields/Outcome_Area__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Area__c</fullName>
    <label>Outcome Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Cross-Sector</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing/Community Facilities</fullName>
            </value>
            <value>
                <fullName>Land Conservation</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Employment, training and education</fullName>
            </value>
            <value>
                <fullName>Housing and local facilities</fullName>
            </value>
            <value>
                <fullName>Income and financial inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Report_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Due_Date__c</fullName>
    <label>Report Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Report_Template__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/Progress_Report_Indicators__c.object-meta.xml
<CustomObject>
    <label>Progress Report Indicator</label>
    <nameField>
        <displayFormat>PRI-{000000}</displayFormat>
        <label>Progress Report Indicators Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Report Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Name__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Name__c</fullName>
    <formula>Indicator_Catalogue__r.Metrics_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Indicator Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area (Long)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Progress_Report_Indicators__c/fields/Progress_Report__c.field-meta.xml
<CustomField>
    <fullName>Progress_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Progress Report</label>
    <referenceTo>Progress_Report__c</referenceTo>
    <relationshipLabel>Progress Report Indicators</relationshipLabel>
    <relationshipName>Progress_Report_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Template__c/Report_Template__c.object-meta.xml
<CustomObject>
    <label>Report Template</label>
    <nameField>
        <label>Report Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Template__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Report_Template_Indicator__c/Report_Template_Indicator__c.object-meta.xml
<CustomObject>
    <label>Report Template Indicator</label>
    <nameField>
        <displayFormat>RTI-{00000}</displayFormat>
        <label>Report Template Indicator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Template Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Indicator_Catalogue__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Catalogue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Indicator Catalogue</label>
    <referenceTo>Indicator_Catalogue__c</referenceTo>
    <relationshipLabel>Report Template Indicators</relationshipLabel>
    <relationshipName>Report_Template_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Template_Indicator__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report Template</label>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Report Template Indicators</relationshipLabel>
    <relationshipName>Report_Template_Indicators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestScheduleReportsController.cls
/*
 * @description         This is unit test for SheduleReports
 * @author              Alexey Eliseev
 * @component           SheduleReports
 * @date                2/4/19
*/

@isTest
private with sharing class TestScheduleReportsController {
    @isTest static void test_ScheduleReportsController() {
        Test.startTest();
        Application__c testApplication = TestUtils.createNewApplication();
        insert testApplication;

        Report_Template__c testTemplate = new Report_Template__c(Name = 'Template1', Active__c = true);
        insert testTemplate;

        Map<String, RecordTypeInfo> recorsTypesMap = Schema.SObjectType.sfims__Indicator_Catalogue__c.getRecordTypeInfosByName();
        Id recordTypeIdCatalogue;
        for (String key : recorsTypesMap.keySet()) {
            if (recorsTypesMap.get(key).getName() != 'Master' ) {
                recordTypeIdCatalogue = recorsTypesMap.get(key).getRecordTypeId();
                break;
            }
        }

        List<Indicator_Catalogue__c> listIndicators = new List<Indicator_Catalogue__c>();
        for (Integer i = 0; i < 10; i++) {
            listIndicators.add(new Indicator_Catalogue__c(Active__c = true, Indicator_Name__c = 'Indicator_Name__' + i,
                    Indicator_Type__c = 'Number', Outcome_Area__c = 'Housing and local facilities', RecordTypeId = recordTypeIdCatalogue));
        }
        insert listIndicators;

        list<Report_Template_Indicator__c> junctionObject = new list<Report_Template_Indicator__c>();
        List<Id> indicatorIds = new List<Id>();
        for (Integer j = 0; j < 5; j++) {
            junctionObject.add(new Report_Template_Indicator__c(Indicator_Catalogue__c = listIndicators[j].Id, Report_Template__c = testTemplate.Id));
            indicatorIds.add(listIndicators[j].Id);
        }
        insert junctionObject;

        Progress_Report__c returnDataTest0 = new Progress_Report__c();
        insert returnDataTest0;

        system.assertEquals(0, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest0.Id
        ], 'Invalid count of Progress Report Indicators - Test 0');

        List<Progress_Report__c> returnDataTest1 = ScheduleReportsController.generatedProgressReport(testApplication.Id, testTemplate.Id, '2019-01-16', 'Monthly', 2);
        List<Progress_Report__c> returnDataTest2 = ScheduleReportsController.generatedProgressReport(testApplication.Id, testTemplate.Id, '2025-02-10', 'Quarterly', 3);
        List<Progress_Report__c> returnDataTest3 = ScheduleReportsController.generatedProgressReport(testApplication.Id, testTemplate.Id, '2030-03-05', 'Yearly', 4);

        system.assertEquals(10, [
                SELECT count()
                FROM Progress_Report__c
        ], 'Invalid count of Progress Report');
        system.assertEquals(2, [
                SELECT count()
                FROM Progress_Report__c
                WHERE Report_Template__c = :testTemplate.Id AND Report_Due_Date__c IN (2019-01-16, 2019-02-16)
        ], 'Invalid count of Progress Report - Monthly');
        system.assertEquals(3, [
                SELECT count()
                FROM Progress_Report__c
                WHERE Report_Template__c = :testTemplate.Id AND Report_Due_Date__c IN (2025-02-10, 2025-05-10, 2025-08-10)
        ], 'Invalid count of Progress Report - Quarterly');
        system.assertEquals(4, [
                SELECT count()
                FROM Progress_Report__c
                WHERE Report_Template__c = :testTemplate.Id AND Report_Due_Date__c IN (2030-03-05, 2031-03-05, 2032-03-05, 2033-03-05)
        ], 'Invalid count of Progress Report - Yearly');

        /*----------------------------- Test 1 Monthly ------------------------- */

        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest1[0].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 1');
        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest1[1].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 1');

        /*----------------------------- Test 2 Quarterly ------------------------- */

        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest2[0].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 2');
        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest2[1].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 2');
        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest2[2].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 2');

        /*----------------------------- Test 3 Yearly ------------------------- */

        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest3[0].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 3');
        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest3[1].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 3');
        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest3[2].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 3');
        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest3[3].Id AND Indicator_Catalogue__c IN :indicatorIds
        ], 'Invalid count of Progress Report Indicators - Test 3');

        /*----------------------------- Progress Report Trigger Test (delete) ------------------------- */

        system.assertEquals(5, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest1[0].Id
        ], 'Invalid count of Progress Report Indicators - Progress Report Trigger Test');

        system.assertEquals(1, [
                SELECT count()
                FROM Progress_Report__c
                WHERE Id = :returnDataTest1[0].Id
        ], 'Invalid count of Progress Report - Progress Report Trigger Test');

        delete returnDataTest1[0];

        system.assertEquals(0, [
                SELECT count()
                FROM Progress_Report__c
                WHERE Id = :returnDataTest1[0].Id
        ], 'Invalid count of Progress Report - Progress Report Trigger Test');

        system.assertEquals(0, [
                SELECT count()
                FROM Progress_Report_Indicators__c
                WHERE Progress_Report__c = :returnDataTest1[0].Id
        ], 'Invalid count of Progress Report Indicators - Progress Report Trigger Test');

        Test.stopTest();
    }
}