force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/FormAssembly_Application_Attach_Name__c.field-meta.xml
<CustomField>
    <fullName>FormAssembly_Application_Attach_Name__c</fullName>
    <formula>&quot;Full Application&quot; &amp; &quot; - &quot; &amp; Name &amp; &quot;.pdf&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FormAssembly - Application Attach Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/FormAssembly_EOI_Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>FormAssembly_EOI_Attachment_Name__c</fullName>
    <formula>&quot;Expression of Interest&quot; &amp; &quot; - &quot; &amp; Name &amp; &quot;.pdf&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FormAssembly - EOI Attachment Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/FormAssembly_EOI_content__c.field-meta.xml
<CustomField>
    <fullName>FormAssembly_EOI_content__c</fullName>
    <description>Rich text copy of Form Assembly form for Expression Of Interest content</description>
    <label>FormAssembly - EOI content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/FormAssembly_Full_Application_content__c.field-meta.xml
<CustomField>
    <fullName>FormAssembly_Full_Application_content__c</fullName>
    <description>Rich text download of Form Assembly form of full application form</description>
    <label>FormAssembly - Full Application content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application Review</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Approved (Pending Contract)</label>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Application Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Implementation</fullName>
                <isActive>false</isActive>
                <label>Implementation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the score for 1 criteria for 1 assessor for an assessment</description>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Assessment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment_Criteria_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Criteria Definition</label>
    <referenceTo>Assessment_Criteria_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/Assessment_Criteria_Definition__c.object-meta.xml
<CustomObject>
    <description>The definition of a criteria that belongs to 1 assessment stage definition and will be instantiated into each assessment that is generated for the particular stage.</description>
    <label>Assessment Criteria Definition</label>
    <nameField>
        <label>Assessment Criteria Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Assessment_Stage_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Stage_Definition__c</fullName>
    <label>Assessment Stage Definition</label>
    <referenceTo>Assessment_Stage_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria Definitions</relationshipLabel>
    <relationshipName>Assessment_Criteria_Definitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/Assessment_Stage_Definition__c.object-meta.xml
<CustomObject>
    <description>Defines an application stage for which assessments are needed. All assessments selected for this stage will be added to any application reaching the stage (within the applicable Fund)</description>
    <label>Assessment Stage Definition</label>
    <nameField>
        <label>Assessment Stage Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Stage Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fund to which this assessment definition is applicable</description>
    <inlineHelpText>The fund to which this assessment definition is applicable</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Assessment Stage Definitions</relationshipLabel>
    <relationshipName>Assessment_Stage_Definitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund_Assessor__c/Fund_Assessor__c.object-meta.xml
<CustomObject>
    <description>Junction object that links Assessors to Funds</description>
    <label>Fund Assessor</label>
    <nameField>
        <displayFormat>FA-{00000000}</displayFormat>
        <label>Fund Assessor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Assessors</relationshipLabel>
    <relationshipName>Fund_Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone_Configuration__c/Milestone_Configuration__c.object-meta.xml
<CustomObject>
    <description>Milestone Configuration object sets the stage/status changes on the Application, Contract and Investment object that will trigger the creation of a Milestone History record in the Milestone History object</description>
    <label>Milestone Configuration</label>
    <nameField>
        <displayFormat>MC-{00000000}</displayFormat>
        <label>Milestone Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Configuration__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence number of the Stage/Status change on the Milestone History object. This sequence number is used to determine how long a Milestone has stayed in a certain Stage/Status</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_Configuration__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The value of the Stage/Status field in the object that will need to trigger a Milestone History record</description>
    <label>Stage-Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/Milestone_History__c.object-meta.xml
<CustomObject>
    <description>Milestone History object tracks all the milestone an organisation goes through from Application, Contract and Investment record. This is one of the key reporting objects used within the IMS application</description>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>MH-{00000000}</displayFormat>
        <label>Milestone History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_History__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Application that this Milestone belongs to</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Milestone Histories</relationshipLabel>
    <relationshipName>Milestone_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Days_in_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Milestone__c</fullName>
    <description>The number of days that the record was in this milestone (automatically calculated field with code)</description>
    <label>Days in Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>The name of the Milestone Stage/Status</description>
    <label>Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <description>The Date the milestone moved into the specific stage/status</description>
    <label>Milestone Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence number of this milestone record for this application</description>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/Stage_Assessment__c.object-meta.xml
<CustomObject>
    <description>This is the placeholder for the set of assessments done at a particular stage in the Application process.</description>
    <label>Stage Assessment</label>
    <nameField>
        <label>Stage Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The application being assessed</description>
    <inlineHelpText>The application being assessed</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Stage Assessments</relationshipLabel>
    <relationshipName>Stage_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The application stage to which this assessment belongs.</description>
    <inlineHelpText>The application stage to which this assessment belongs.</inlineHelpText>
    <label>Stage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestApplicationTriggerHandler.cls
@IsTest
private class TestApplicationTriggerHandler {

    @IsTest static void test_application_stage_edited_as_platform_user() {
        User platformUser = TestUtils.createPlatformUser();

        Milestone_Configuration__c mc1 = TestUtils.createNewMilestoneConfiguration('Application', 'Enquiry', 'Expression of Interest', 1);
        Milestone_Configuration__c mc2 = TestUtils.createNewMilestoneConfiguration('Application', 'Application', 'Application', 2);

        Application__c app = TestUtils.createNewApplication();
        app.Stage__c = 'Enquiry';

        // admin creates the setup
        System.runAs(new User(ID = UserInfo.getUserId())) {
            insert new List<SObject>{
                    mc1, mc2, app
            };

            List<Milestone_History__c> mhList = [
                    SELECT Milestone__c, Milestone_Date__c, Days_in_Milestone__c, Application__c, Sequence__c
                    FROM Milestone_History__c
                    ORDER BY Sequence__c DESC
            ];

            System.assertEquals(1, mhList.size());
            System.assertEquals(app.Id, mhList[0].Application__c);
            System.assertEquals('Expression of Interest', mhList[0].Milestone__c);
        }
        // platform user triggers the logic
        System.runAs(platformUser) {

            app.Stage__c = 'Application';
            update app;

            List<Milestone_History__c> mhList2 = [
                    SELECT Milestone__c, Milestone_Date__c, Days_in_Milestone__c, Application__c, Sequence__c
                    FROM Milestone_History__c
                    ORDER BY Sequence__c DESC
            ];

            System.assertEquals(2, mhList2.size());
            System.assertEquals(app.Id, mhList2[0].Application__c);
            System.assertEquals(null, mhList2[1].Days_in_Milestone__c);
        }
    }

    @IsTest static void test_generate_attachment() {
        Application__c app = TestUtils.createNewApplication();
        app.FormAssembly_EOI_content__c = 'EOI content';
        app.FormAssembly_Full_Application_content__c = 'Full content';
        insert app;

        Application__c application = [SELECT Id, FormAssembly_EOI_Attachment_Name__c, FormAssembly_Application_Attach_Name__c FROM Application__c WHERE Id = :app.Id];
        List<Attachment> attachments = [SELECT Id, ParentId, Name FROM Attachment WHERE ParentId = :app.Id ORDER BY Name ASC];
        System.assertEquals(2, attachments.size());
        System.assertEquals(application.FormAssembly_EOI_Attachment_Name__c, attachments[0].Name);
        System.assertEquals(application.FormAssembly_Application_Attach_Name__c, attachments[1].Name);

        app.FormAssembly_EOI_content__c = 'EOI content updated';
        app.FormAssembly_Full_Application_content__c = 'Full content updated';
        update app;

        List<Attachment> newAttachments = [SELECT Id, ParentId, Name FROM Attachment WHERE ParentId = :app.Id ORDER BY Name ASC];
        System.assertEquals(2, newAttachments.size());
        System.assertEquals(application.FormAssembly_EOI_Attachment_Name__c, newAttachments[0].Name);
        System.assertEquals(application.FormAssembly_Application_Attach_Name__c, newAttachments[1].Name);
        System.assertNotEquals(attachments[0].Id, newAttachments[0].Id);
        System.assertNotEquals(attachments[1].Id, newAttachments[1].Id);
    }

    @IsTest static void test_delete_child_records() {
        Application__c app = TestUtils.createNewApplication();
        insert app;
        Progress_Report__c pr = new Progress_Report__c(Application__c = app.Id);
        insert pr;

        delete app;

        List<Progress_Report__c> progressReports = [
                SELECT Id
                FROM Progress_Report__c
                WHERE Application__c = :app.Id
        ];

        System.assertEquals(0, progressReports.size());
    }

    @IsTest static void test_create_assessments() {
        // insert account
        Account acc = TestUtils.createAccount('Investee_Account');
        // insert Fund
        Fund__c fund1 = TestUtils.createFund('fund1');
        Fund__c fund2 = TestUtils.createFund('fund2');
        insert new List<SObject>{ acc, fund1, fund2 };

        // insert Fund Assessors
        Fund_Assessor__c fundAssessor1 = TestUtils.createFundAssessor(fund2);
        Fund_Assessor__c fundAssessor2 = TestUtils.createFundAssessor(fund2);
        Fund_Assessor__c fundAssessor3 = TestUtils.createFundAssessor(fund1);
        Fund_Assessor__c fundAssessor4 = TestUtils.createFundAssessor(fund1);
        insert new List<Fund_Assessor__c>{
                fundAssessor1, fundAssessor2, fundAssessor3, fundAssessor4
        };

        // insert Assessment Stage Definitions
        Assessment_Stage_Definition__c stage1 = TestUtils.createAssessmentStageDefinition(fund1, 'Application', null, 'Random fund assessor', 2);
        Assessment_Stage_Definition__c stage2 = TestUtils.createAssessmentStageDefinition(fund1, 'Application', 'Tier 1', 'Manual selection', 5);
        Assessment_Stage_Definition__c stage3 = TestUtils.createAssessmentStageDefinition(fund2, 'Application', null, 'All fund assessors');
        Assessment_Stage_Definition__c stage4 = TestUtils.createAssessmentStageDefinition(fund2, 'Application', 'Tier 1', 'Random fund assessor', 1);
        insert new List<Assessment_Stage_Definition__c>{
                stage1, stage2, stage3, stage4
        };

        // insert Assessment Criteria Definition__c
        Assessment_Criteria_Definition__c criteria1 = TestUtils.createAssessmentCriteriaDefinition(stage1, 'Rating');
        Assessment_Criteria_Definition__c criteria2 = TestUtils.createAssessmentCriteriaDefinition(stage2, 'Text');
        insert new List<Assessment_Criteria_Definition__c>{
                criteria1, criteria2
        };

        // Insert new Application - true
        Application__c application1 = TestUtils.createNewApplication(acc.Id);
        insert application1;
        System.assertEquals(1, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(0, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');

        // Insert new Application - true
        Application__c application2 = TestUtils.createNewApplication(acc.Id);
        application2.Fund__c = fund1.Id;
        insert application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(0, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');

        // Update Application - true
        application2.Assessment_Stage__c = 'Tier 1';
        update application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(0, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');

        // Update Application - true
        application2.Stage__c = 'Application';
        application2.Assessment_Stage__c = 'Tier 1';
        update application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(5, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(5, [SELECT Id FROM Assessment_Criteria__c WHERE Type__c = 'Text'].size(), 'Invalid size Assessment_Criteria__c');

        // Update Application - true
        application2.Stage__c = 'Enquiry';
        application2.Assessment_Stage__c = 'Tier 1';
        update application2;
        Map<Id, Assessment__c> delMap = new Map<Id, Assessment__c>([SELECT Id FROM Assessment__c LIMIT 2]);
        delete [SELECT Id FROM Assessment__c WHERE Id IN :delMap.keySet()];
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(3, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(3, [SELECT Id FROM Assessment_Criteria__c WHERE Type__c = 'Text'].size(), 'Invalid size Assessment_Criteria__c');

        // Update Application - true
        application2.Stage__c = 'Application';
        application2.Assessment_Stage__c = 'Tier 1';
        update application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(3, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(3, [SELECT Id FROM Assessment_Criteria__c WHERE Type__c = 'Text'].size(), 'Invalid size Assessment_Criteria__c');

        Test.startTest();

        // Update Application - true
        delete [SELECT Id FROM Assessment__c];
        application2.Stage__c = 'Enquiry';
        application2.Assessment_Stage__c = 'Tier 1';
        update application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(0, [SELECT Id FROM Assessment_Criteria__c WHERE Type__c = 'Text'].size(), 'Invalid size Assessment_Criteria__c');

        // Update Application - true
        delete [SELECT Id FROM Assessment__c];
        application2.Stage__c = 'Application';
        application2.Assessment_Stage__c = 'Tier 1';
        update application2;
        System.assertEquals(2, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(1, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(5, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(5, [SELECT Id FROM Assessment_Criteria__c WHERE Type__c = 'Text'].size(), 'Invalid size Assessment_Criteria__c');
        application2.Name = 'New';
        update application2;

        // Insert new Application - true
        Application__c application3 = TestUtils.createNewApplication(acc.Id);
        application3.Fund__c = fund2.Id;
        application3.Assessment_Stage__c = 'Tier 1';
        application3.Stage__c = 'Application';
        insert application3;
        System.assertEquals(3, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(2, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(6, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(5, [SELECT Id FROM Assessment_Criteria__c WHERE Type__c = 'Text'].size(), 'Invalid size Assessment_Criteria__c');

        // Insert new Application - true
        Application__c application4 = TestUtils.createNewApplication(acc.Id);
        application4.Fund__c = fund1.Id; 
        application4.Stage__c = 'Application';
        insert application4;
        System.assertEquals(4, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(3, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(8, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(7, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');

        // Insert new Application - true
        Application__c application5 = TestUtils.createNewApplication(acc.Id);
        application5.Fund__c = fund2.Id;
        application5.Stage__c = 'Application';
        application5.Assessment_Stage__c = 'Tier 2';
        insert application5;
        System.assertEquals(5, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(4, [SELECT Id FROM Stage_Assessment__c].size(), 'Invalid size Stage_Assessment__c');
        System.assertEquals(10, [SELECT Id FROM Assessment__c].size(), 'Invalid size Assessment__c');
        System.assertEquals(7, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size Assessment_Criteria__c');

        Test.stopTest();
    }
}