force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application Review</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Approved (Pending Contract)</label>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Application Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Implementation</fullName>
                <isActive>false</isActive>
                <label>Implementation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment of an application in a certain stage.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>This is the conclusion from the Assessment. The field can be filled manually, or custom logic can be developed by the customer to update it, based on score and other criteria.</description>
    <inlineHelpText>This is the conclusion from the Assessment.</inlineHelpText>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Stage_Assessment_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Stage_Assessment_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stage Assessment</label>
    <referenceTo>Stage_Assessment__c</referenceTo>
    <relationshipLabel>Assessments (Stage Assessment)</relationshipLabel>
    <relationshipName>Assessments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/Assessment_Criteria_Definition__c.object-meta.xml
<CustomObject>
    <description>The definition of a criteria that belongs to 1 assessment stage definition and will be instantiated into each assessment that is generated for the particular stage.</description>
    <label>Assessment Criteria Definition</label>
    <nameField>
        <label>Assessment Criteria Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Assessment_Stage_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Stage_Definition__c</fullName>
    <label>Assessment Stage Definition</label>
    <referenceTo>Assessment_Stage_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria Definitions</relationshipLabel>
    <relationshipName>Assessment_Criteria_Definitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/Assessment_Stage_Definition__c.object-meta.xml
<CustomObject>
    <description>Defines an application stage for which assessments are needed. All assessments selected for this stage will be added to any application reaching the stage (within the applicable Fund)</description>
    <label>Assessment Stage Definition</label>
    <nameField>
        <label>Assessment Stage Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Stage Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fund to which this assessment definition is applicable</description>
    <inlineHelpText>The fund to which this assessment definition is applicable</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Assessment Stage Definitions</relationshipLabel>
    <relationshipName>Assessment_Stage_Definitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Number_of_Assessments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assessments__c</fullName>
    <description>For assessors of type &#39;Random fund assessor&#39; and &#39;Manual selection&#39; specify the total number of assessments to be created here.</description>
    <inlineHelpText>For assessors of type &#39;Random fund assessor&#39; and &#39;Manual selection&#39; specify the total number of assessments to be created here.</inlineHelpText>
    <label>Number of Assessments</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Funds are used to group individual investments to an overall fund. In reports and dashboards Funds are used as an important filter to look at a portfolio per fund.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/Fund_Assessor__c.object-meta.xml
<CustomObject>
    <description>Junction object that links Assessors to Funds</description>
    <label>Fund Assessor</label>
    <nameField>
        <displayFormat>FA-{00000000}</displayFormat>
        <label>Fund Assessor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Assessors</relationshipLabel>
    <relationshipName>Fund_Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/Stage_Assessment__c.object-meta.xml
<CustomObject>
    <description>This is the placeholder for the set of assessments done at a particular stage in the Application process.</description>
    <label>Stage Assessment</label>
    <nameField>
        <label>Stage Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Assessment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The application being assessed</description>
    <inlineHelpText>The application being assessed</inlineHelpText>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Stage Assessments</relationshipLabel>
    <relationshipName>Stage_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Number_of_Assessments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assessments__c</fullName>
    <description>The number of assessments for this stage</description>
    <inlineHelpText>The number of assessments for this stage</inlineHelpText>
    <label>Number of Assessments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Number_of_Assessments_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assessments_Accepted__c</fullName>
    <description>The number of assessments for this stage with outcome &#39;Accepted&#39;</description>
    <inlineHelpText>The number of assessments for this stage with outcome &#39;Accepted&#39;</inlineHelpText>
    <label>Number of Assessments Accepted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Number_of_Assessments_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assessments_Rejected__c</fullName>
    <description>The number of assessments for this stage with status &#39;Rejected&#39;</description>
    <inlineHelpText>The number of assessments for this stage with status &#39;Rejected&#39;</inlineHelpText>
    <label>Number of Assessments Rejected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stage_Assessment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The application stage to which this assessment belongs.</description>
    <inlineHelpText>The application stage to which this assessment belongs.</inlineHelpText>
    <label>Stage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAssessmentTrigger.cls
@IsTest
private with sharing class TestAssessmentTrigger {
    @IsTest static void test_generate_assessment_name() {
        Test.startTest();

        // insert Fund
        Fund__c fund1 = TestUtils.createFund('fund1');
        insert fund1;

        // insert Fund Assessors
        Fund_Assessor__c fundAssessor1 = TestUtils.createFundAssessor(fund1);
        insert fundAssessor1;

        // insert Assessment Stage Definitions
        Assessment_Stage_Definition__c stage1 = TestUtils.createAssessmentStageDefinition(fund1, 'Application', null, 'Manual selection', 3);
        insert stage1;

        // insert Assessment Criteria Definition__c
        Assessment_Criteria_Definition__c criteria1 = TestUtils.createAssessmentCriteriaDefinition(stage1, 'Rating');
        Assessment_Criteria_Definition__c criteria2 = TestUtils.createAssessmentCriteriaDefinition(stage1, 'Text');
        insert new List<Assessment_Criteria_Definition__c>{
                criteria1, criteria2
        };

        // Insert new Applications - true
        Application__c application1 = TestUtils.createNewApplication();
        application1.Name = 'Name-12345678910';
        application1.Fund__c = fund1.Id;
        application1.Stage__c = 'Application';
        insert application1;
        System.assertEquals(1, [SELECT Id FROM Application__c].size(), 'Invalid size Application__c');
        System.assertEquals(3, [SELECT Name FROM Assessment__c WHERE Name = 'Application-Name-12345678910'].size(), 'Invalid Assessment__c name');
        
        Test.stopTest();
    }

    @IsTest static void test_populate_stage_assessment_fields() {
        // create a new stage assessment
        Stage_Assessment__c stageAssessment = new Stage_Assessment__c(Stage__c = 'Application');
        insert stageAssessment;

        // create a new assessment
        Assessment__c assessment1 = new Assessment__c(Stage_Assessment_Lookup__c = stageAssessment.Id, Outcome__c = 'Accepted', Status__c = 'Completed');
        Assessment__c assessment2 = new Assessment__c(Stage_Assessment_Lookup__c = stageAssessment.Id, Outcome__c = 'Rejected', Status__c = 'Completed');
        insert new List<Assessment__c>{assessment1, assessment2};
        
        // check the result
        Stage_Assessment__c result = [
            SELECT Number_of_Assessments__c, Number_of_Assessments_Accepted__c, Number_of_Assessments_Rejected__c
            FROM Stage_Assessment__c
            WHERE Id = :stageAssessment.Id 
        ];

        System.assertEquals(2, result.Number_of_Assessments__c);
        System.assertEquals(1, result.Number_of_Assessments_Accepted__c);
        System.assertEquals(1, result.Number_of_Assessments_Rejected__c);

        // update an assessment
        assessment1.Outcome__c = 'Rejected';
        update assessment1;

        // check the result
        Stage_Assessment__c result2 = [
            SELECT Number_of_Assessments__c, Number_of_Assessments_Accepted__c, Number_of_Assessments_Rejected__c
            FROM Stage_Assessment__c
            WHERE Id = :stageAssessment.Id 
        ];

        System.assertEquals(2, result2.Number_of_Assessments__c);
        System.assertEquals(0, result2.Number_of_Assessments_Accepted__c);
        System.assertEquals(2, result2.Number_of_Assessments_Rejected__c);
        
        // delete an assessment
        delete assessment1;

        // check the result
        Stage_Assessment__c result3 = [
            SELECT Number_of_Assessments__c, Number_of_Assessments_Accepted__c, Number_of_Assessments_Rejected__c
            FROM Stage_Assessment__c
            WHERE Id = :stageAssessment.Id 
        ];

        System.assertEquals(1, result3.Number_of_Assessments__c);
        System.assertEquals(0, result3.Number_of_Assessments_Accepted__c);
        System.assertEquals(1, result3.Number_of_Assessments_Rejected__c);
    }
}