force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report Template</label>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/Progress_Report__c.object-meta.xml
<CustomObject>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Progress_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/From_period__c.field-meta.xml
<CustomField>
    <fullName>From_period__c</fullName>
    <label>From period:</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Report_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Due_Date__c</fullName>
    <label>Report Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/Report_Template__c.field-meta.xml
<CustomField>
    <fullName>Report_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Report Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Report_Template__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Report_Template__c</referenceTo>
    <relationshipLabel>Progress Reports</relationshipLabel>
    <relationshipName>Progress_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Progress_Report__c/fields/To_Period__c.field-meta.xml
<CustomField>
    <fullName>To_Period__c</fullName>
    <label>To Period:</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Report_Template__c/Report_Template__c.object-meta.xml
<CustomObject>
    <label>Report Template</label>
    <nameField>
        <label>Report Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScheduleReportsController.cls
/*
 * @description         This is controller for the component SheduleReports
 * @author              Alexey Eliseev
 * @component           SheduleReports
 * @date                1/16/19
*/

public with sharing class ScheduleReportsController {
    @AuraEnabled
    public static list<Progress_Report__c> generatedProgressReport(Id application, Id reportTemplate, String prDate, String prFrequency, Integer prNumber) {
        Date newDate = Date.valueOf(prDate);
        // calculate startdate for first period
        Date periodStartDate;
        switch on prFrequency {
            when 'Monthly' {
                periodStartDate = newDate.addmonths(-1).addDays(1);
            }
            when 'Quarterly' {
                periodStartDate = newDate.addmonths(-3).addDays(1);
            }
            when 'Yearly' {
                periodStartDate = newDate.addyears(-1).addDays(1);
            }
        }        

        list<Progress_Report__c> addProgressReport = new list<Progress_Report__c>();
        
        for (Integer i = 0; i < prNumber; i++) {
            
            addProgressReport.add(
                new Progress_Report__c(
                    Application__c = application, 
                    Report_Due_Date__c = newDate, 
                    Report_Template__c = reportTemplate,
                    From_Period__c = periodStartDate,
                    To_Period__c = newDate
                )
            );
            // set startdate of new period
            periodStartDate = newDate.addDays(1);
            // determin enddate of new period
            switch on prFrequency {
                when 'Monthly' {
                    newDate = newDate.addmonths(1);
                }
                when 'Quarterly' {
                    newDate = newDate.addmonths(3);
                }
                when 'Yearly' {
                    newDate = newDate.addyears(1);
                }
            }
            
        }

        if (addProgressReport.size() > 0) {
            insert addProgressReport;
        }

        return addProgressReport;
    }
}