force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application Review</fullName>
            </value>
            <value>
                <fullName>Due Diligence</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Approved (Pending Contract)</label>
            </value>
            <value>
                <fullName>Application Approved</fullName>
            </value>
            <value>
                <fullName>Application Withdrawn</fullName>
            </value>
            <value>
                <fullName>Application Declined</fullName>
            </value>
            <value>
                <fullName>Application Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Implementation</fullName>
                <isActive>false</isActive>
                <label>Implementation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Contract Object for Singlify</description>
    <label>Contract</label>
    <nameField>
        <displayFormat>CNT-{00000000}</displayFormat>
        <label>Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Signed - Open</fullName>
            </value>
            <value>
                <fullName>Singed - Closed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Internal Review</fullName>
            </value>
            <value>
                <fullName>External Review</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone_Configuration__c/Milestone_Configuration__c.object-meta.xml
<CustomObject>
    <description>Milestone Configuration object sets the stage/status changes on the Application, Contract and Investment object that will trigger the creation of a Milestone History record in the Milestone History object</description>
    <label>Milestone Configuration</label>
    <nameField>
        <displayFormat>MC-{00000000}</displayFormat>
        <label>Milestone Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_Configuration__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence number of the Stage/Status change on the Milestone History object. This sequence number is used to determine how long a Milestone has stayed in a certain Stage/Status</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_Configuration__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The value of the Stage/Status field in the object that will need to trigger a Milestone History record</description>
    <label>Stage-Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/Milestone_History__c.object-meta.xml
<CustomObject>
    <description>Milestone History object tracks all the milestone an organisation goes through from Application, Contract and Investment record. This is one of the key reporting objects used within the IMS application</description>
    <label>Milestone History</label>
    <nameField>
        <displayFormat>MH-{00000000}</displayFormat>
        <label>Milestone History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone_History__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Application that this Milestone belongs to</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Milestone Histories</relationshipLabel>
    <relationshipName>Milestone_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contract record that this milestone belongs to</description>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Milestone Histories</relationshipLabel>
    <relationshipName>Milestone_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Days_in_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Milestone__c</fullName>
    <description>The number of days that the record was in this milestone (automatically calculated field with code)</description>
    <label>Days in Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Investment record that this milestone belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Milestone Histories</relationshipLabel>
    <relationshipName>Milestone_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <description>The Date the milestone moved into the specific stage/status</description>
    <label>Milestone Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone_History__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence number of this milestone record for this application</description>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestMilestoneHistoryTrigger.cls
@isTest
private class TestMilestoneHistoryTrigger {
    @isTest static void test_countDaysInMilestone() {
        Milestone_Configuration__c mc1 = TestUtils.createNewMilestoneConfiguration('Application', 'Enquiry', 'Expression of Interest', 1);
        Milestone_Configuration__c mc2 = TestUtils.createNewMilestoneConfiguration('Application', 'Application', 'Application', 2);
        Milestone_Configuration__c mc3 = TestUtils.createNewMilestoneConfiguration('Application', 'Application Review', 'Application Review', 3);
        Milestone_Configuration__c mc4 = TestUtils.createNewMilestoneConfiguration('Contract', 'Internal Review', 'Contract Internal Review', 6);
        Milestone_Configuration__c mc5 = TestUtils.createNewMilestoneConfiguration('Investment', 'Active', 'Investment Active', 9);
        Application__c app = TestUtils.createNewApplication();
        app.Stage__c = 'Enquiry';
        insert new List<SObject>{ mc1, mc2, mc3, mc4, mc5, app };
        
        app.Stage__c = 'Application';
        update app; 

        app.Stage__c = 'Application Review';
        update app;

        List<Milestone_History__c> mhList = [
            SELECT Milestone_Date__c
            FROM Milestone_History__c
            ORDER BY Sequence__c ASC
        ];

        Integer days1 = 30;
        Integer days2 = 15;
        Date date1 = System.today().addDays(-days1);
        Date date2 = System.today().addDays(-days2);
        mhList[0].Milestone_Date__c = date1;
        mhList[1].Milestone_Date__c = date2;
       
        update new List<Milestone_History__c>{mhList[0], mhList[1]};

        mhList = [
            SELECT Days_in_Milestone__c, Milestone_Date__c
            FROM Milestone_History__c
            ORDER BY Sequence__c ASC
        ];

        // verify results
        System.assertEquals(3, mhList.size());
        System.assertEquals(date1.daysBetween(date2), mhList[0].Days_in_Milestone__c);
        System.assertEquals(date2.daysBetween(System.today()), mhList[1].Days_in_Milestone__c);
        System.assertEquals(null, mhList[2].Days_in_Milestone__c);

        Integer days3 = 10;
        Date date3 = System.today().addDays(-days3);
        mhList[1].Milestone_Date__c = date3;
        update mhList[1];

        List<Milestone_History__c> mhList2 = [
            SELECT Days_in_Milestone__c
            FROM Milestone_History__c
            ORDER BY Sequence__c ASC
        ];

        // verify results
        System.assertEquals(date1.daysBetween(date3), mhList2[0].Days_in_Milestone__c);
        System.assertEquals(date3.daysBetween(System.today()), mhList2[1].Days_in_Milestone__c);
        System.assertEquals(null, mhList2[2].Days_in_Milestone__c);

        // test after delete
        delete mhList2[2];

        List<Milestone_History__c> mhList3 = [
            SELECT Days_in_Milestone__c
            FROM Milestone_History__c
            ORDER BY Sequence__c ASC
        ];

        // verify results
        System.assertEquals(2, mhList3.size());
        System.assertEquals(date1.daysBetween(date3), mhList3[0].Days_in_Milestone__c);
        System.assertEquals(null, mhList3[1].Days_in_Milestone__c);

        // test after undelete
        undelete [SELECT Id FROM Milestone_History__c WHERE Id =: mhList2[2].Id ALL ROWS];

        List<Milestone_History__c> mhList4 = [
            SELECT Days_in_Milestone__c
            FROM Milestone_History__c
            ORDER BY Sequence__c ASC
        ];

        // verify results
        System.assertEquals(3, mhList4.size());
        System.assertEquals(date1.daysBetween(date3), mhList4[0].Days_in_Milestone__c);
        System.assertEquals(date3.daysBetween(System.today()), mhList4[1].Days_in_Milestone__c);
        System.assertEquals(null, mhList4[2].Days_in_Milestone__c);

        // // test moving to the previous stage
        // // move within the same object
        // app.Stage__c = 'Application';
        // update app;

        // List<Milestone_History__c> mhList5 = [
        //     SELECT Days_in_Milestone__c
        //     FROM Milestone_History__c
        //     ORDER BY Sequence__c ASC
        // ];

        // // verify results
        // System.assertEquals(2, mhList5.size());
        // System.assertEquals(date1.daysBetween(System.today()), mhList5[0].Days_in_Milestone__c);
        // System.assertEquals(null, mhList5[1].Days_in_Milestone__c);

        // insert new Contract__c(Application__c = app.Id, Status__c = 'Internal Review');

        // app.Stage__c = 'Enquiry';
        
        // // Perform test
        // Database.SaveResult result = Database.update(app, false);

        // // Verify 
        // // In this case the update should have been stopped by the trigger,
        // // so verify that we got back an error.
        
        // System.assert(!result.isSuccess());
        // System.assert(result.getErrors().size() > 0);
        // System.assertEquals('An error occurred while trying to insert new Milestone History records: ' + 
        //     'This stage update interferes with a milestone on a related object: Contract' +
        //     ' - Contract Internal Review - ' + System.today().format() + '. Please undo the milestone ' + 
        //     'on the related object before you can apply this stage update.', result.getErrors()[0].getMessage());

        
        // Investment__c i = TestUtils.createNewLoan(System.today(), System.today());
        // i.Application__c = app.Id;
        // i.Status__c = 'Active';
        // insert i;

        // // Perform test
        // Database.SaveResult result2 = Database.update(app, false);
        // // Verify 
        // // In this case the update should have been stopped by the trigger,
        // // so verify that we got back an error.
        
        // System.assert(!result2.isSuccess());
        // System.assert(result2.getErrors().size() > 0);
        // System.assertEquals('An error occurred while trying to insert new Milestone History records: ' + 
        //     'This stage update interferes with a milestone on a related object: Investment' +
        //     ' - Investment Active - ' + System.today().format() + '. Please undo the milestone ' + 
        //     'on the related object before you can apply this stage update.', result2.getErrors()[0].getMessage());
    }

    // @isTest static void test_runValidations() {
    //     Milestone_Configuration__c mc1 = TestUtils.createNewMilestoneConfiguration('Application', 'Enquiry', 'Expression of Interest', 1);
    //     Milestone_Configuration__c mc2 = TestUtils.createNewMilestoneConfiguration('Application', 'Application', 'Application', 2);
    //     Milestone_Configuration__c mc3 = TestUtils.createNewMilestoneConfiguration('Application', 'Application Review', 'Application Review', 3);
    //     Application__c app = TestUtils.createNewApplication();
    //     app.Stage__c = 'Enquiry';
    //     insert new List<SObject>{ mc1, mc2, mc3, app };
        
    //     app.Stage__c = 'Application';
    //     update app; 

    //     app.Stage__c = 'Application Review';
    //     update app;

    //     List<Milestone_History__c> mhList = [
    //         SELECT Milestone_Date__c
    //         FROM Milestone_History__c
    //         ORDER BY Sequence__c ASC
    //     ];

    //     Integer days1 = 30;
    //     Date date1 = System.today().addDays(-days1);
    //     mhList[0].Milestone_Date__c = date1;
       
    //     update mhList[0];

    //     // test when the Milestone Date is not correct
    //     Integer days2 = 45;
    //     Date date2 = System.today().addDays(-days2);
    //     mhList[1].Milestone_Date__c = date2;
        
    //     // Perform test
    //     Database.SaveResult result = Database.update(mhList[1], false);
    //     // Verify 
    //     // In this case the update should have been stopped by the trigger,
    //     // so verify that we got back an error.
        
    //     System.assert(!result.isSuccess());
    //     System.assert(result.getErrors().size() > 0);
    //     System.assertEquals('The Milestone Date must not be earlier than the Milestone Date of the previous Milestone History (' +
    //         mhList[0].Milestone_Date__c.format() + ').', result.getErrors()[0].getMessage());
        
    //     Integer days3 = 15;
    //     Date date3 = System.today().addDays(days3);
    //     mhList[1].Milestone_Date__c = date3;

    //     // Perform test
    //     Database.SaveResult result2 = Database.update(mhList[1], false);
    //     // Verify 
    //     // In this case the update should have been stopped by the trigger,
    //     // so verify that we got back an error.
        
    //     System.assert(!result2.isSuccess());
    //     System.assert(result2.getErrors().size() > 0);
    //     System.assertEquals('The Milestone Date must not be later than the Milestone Date of the next Milestone History (' +
    //         [SELECT Milestone_Date__c FROM Milestone_History__c ORDER BY Sequence__c DESC LIMIT 1].Milestone_Date__c.format() + ').', 
    //         result2.getErrors()[0].getMessage());
    // }
}