force-app/main/default/objects/Assessment_Stage_Definition__c/Assessment_Stage_Definition__c.object-meta.xml
<CustomObject>
    <description>Defines an application stage for which assessments are needed. All assessments selected for this stage will be added to any application reaching the stage (within the applicable Fund)</description>
    <label>Assessment Stage Definition</label>
    <nameField>
        <label>Assessment Stage Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Stage Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Application_Assessment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Application_Assessment_Stage__c</fullName>
    <description>(optional) The Application Assessment Stage in which this set of assessment criteria becomes applicable. If not filled in, only the Application Stage is considered.</description>
    <inlineHelpText>(optional) The Application Assessment Stage in which this set of assessment criteria becomes applicable. If not filled in, only the Application Stage is considered.</inlineHelpText>
    <label>Application Assessment Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Application_Stage__c.field-meta.xml
<CustomField>
    <fullName>Application_Stage__c</fullName>
    <description>The Application Stage for which assessments should be generated.</description>
    <inlineHelpText>The Application Stage for which assessments should be generated.</inlineHelpText>
    <label>Application Stage</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Assessors__c.field-meta.xml
<CustomField>
    <fullName>Assessors__c</fullName>
    <description>Defines how the assessors for the assessments for this stage will be allocated.</description>
    <inlineHelpText>Defines how the assessors for the assessments for this stage will be allocated.</inlineHelpText>
    <label>Assessors</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All fund assessors</fullName>
            </value>
            <value>
                <fullName>Random fund assessor</fullName>
            </value>
            <value>
                <fullName>Manual selection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The fund to which this assessment definition is applicable</description>
    <inlineHelpText>The fund to which this assessment definition is applicable</inlineHelpText>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Assessment Stage Definitions</relationshipLabel>
    <relationshipName>Assessment_Stage_Definitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Stage_Definition__c/fields/Number_of_Assessments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assessments__c</fullName>
    <description>For assessors of type &#39;Random fund assessor&#39; and &#39;Manual selection&#39; specify the total number of assessments to be created here.</description>
    <inlineHelpText>For assessors of type &#39;Random fund assessor&#39; and &#39;Manual selection&#39; specify the total number of assessments to be created here.</inlineHelpText>
    <label>Number of Assessments</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Funds are used to group individual investments to an overall fund. In reports and dashboards Funds are used as an important filter to look at a portfolio per fund.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/Fund_Assessor__c.object-meta.xml
<CustomObject>
    <description>Junction object that links Assessors to Funds</description>
    <label>Fund Assessor</label>
    <nameField>
        <displayFormat>FA-{00000000}</displayFormat>
        <label>Fund Assessor Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fund Assessors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund_Assessor__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Fund Assessors</relationshipLabel>
    <relationshipName>Fund_Assessors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestAssessmentStageDefinitionTrigger.cls
/**
* @description         Application Assessment functionality
* @author              Alexey Eliseev
* @date                9/10/19
**/

@IsTest
private with sharing class TestAssessmentStageDefinitionTrigger {
    @IsTest static void test_AssessmentStageDefinitionTrigger() {
        Test.startTest();

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c();
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_42), 'Invalid exception message');
        }
        System.assertEquals(0, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c(Application_Stage__c = null, Application_Assessment_Stage__c = null, Assessors__c = null, Fund__c = null);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_42), 'Invalid exception message');
        }
        System.assertEquals(0, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c(Application_Stage__c = '', Application_Assessment_Stage__c = '', Assessors__c = 'Random fund assessor', Fund__c = null);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_42), 'Invalid exception message');
        }
        System.assertEquals(0, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c(Application_Stage__c = 'Application_Stage_1', Application_Assessment_Stage__c = '', Fund__c = null);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_42), 'Invalid exception message');
        }
        System.assertEquals(0, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - true
        Fund__c fund1 = new Fund__c();
        try {
            insert fund1;
            insert new List<Fund_Assessor__c>{
                    new Fund_Assessor__c(Fund__c = fund1.Id), new Fund_Assessor__c(Fund__c = fund1.Id)
            };
            insert new Assessment_Stage_Definition__c(Application_Stage__c = 'Application_Stage_1', Application_Assessment_Stage__c = '', Assessors__c = 'Random fund assessor', Fund__c = fund1.Id, Number_of_Assessments__c = 2);
        } catch (Exception err) {
            System.assertEquals(false, true, 'Invalid exception');
        }
        System.assertEquals(1, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c(Application_Stage__c = 'Application_Stage_1', Application_Assessment_Stage__c = '', Assessors__c = 'Random fund assessor', Fund__c = fund1.Id, Number_of_Assessments__c = 2);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_40), 'Invalid exception message');
        }
        System.assertEquals(1, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - true
        Assessment_Stage_Definition__c assessmentStageDefinition7 = new Assessment_Stage_Definition__c(Application_Stage__c = 'Application_Stage_1', Application_Assessment_Stage__c = 'ApplicationAssessmentStage_1', Assessors__c = 'Random fund assessor', Fund__c = fund1.Id, Number_of_Assessments__c = 2);
        try {
            insert assessmentStageDefinition7;
        } catch (Exception err) {
            System.assertEquals(false, true, 'Invalid exception');
        }
        System.assertEquals(2, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c(Application_Stage__c = 'Application_Stage_1', Application_Assessment_Stage__c = 'ApplicationAssessmentStage_1', Assessors__c = 'Random fund assessor', Fund__c = fund1.Id, Number_of_Assessments__c = 2);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_40), 'Invalid exception message');
        }
        System.assertEquals(2, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - true
        Fund__c fund2 = new Fund__c();
        try {
            insert fund2;
            insert new List<Fund_Assessor__c>{
                    new Fund_Assessor__c(Fund__c = fund2.Id), new Fund_Assessor__c(Fund__c = fund2.Id)
            };
            insert new Assessment_Stage_Definition__c(Application_Stage__c = 'Application_Stage_1', Application_Assessment_Stage__c = 'ApplicationAssessmentStage_1', Assessors__c = 'Random fund assessor', Fund__c = fund2.Id, Number_of_Assessments__c = 1);
        } catch (Exception err) {
            System.assertEquals(false, true, 'Invalid exception');
        }
        System.assertEquals(3, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Insert new AssessmentStageDefinition - exception
        try {
            insert new Assessment_Stage_Definition__c(Application_Stage__c = '', Application_Assessment_Stage__c = 'ApplicationAssessmentStage_1', Assessors__c = 'Random fund assessor', Number_of_Assessments__c = 2);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_42), 'Invalid exception message');
        }
        System.assertEquals(3, [SELECT Id FROM Assessment_Stage_Definition__c].size(), 'Invalid size');

        // Update AssessmentStageDefinition - exception
        try {
            assessmentStageDefinition7.Assessors__c = null;
            update assessmentStageDefinition7;
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_42), 'Invalid exception message');
        }

        // Update AssessmentStageDefinition - exception
        try {
            assessmentStageDefinition7.Assessors__c = 'Random fund assessor';
            assessmentStageDefinition7.Application_Assessment_Stage__c = '';
            update assessmentStageDefinition7;
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_40), 'Invalid exception message');
        }

        // Update AssessmentStageDefinition - exception
        try {
            assessmentStageDefinition7.Application_Assessment_Stage__c = 'ApplicationAssessmentStage_1';
            assessmentStageDefinition7.Fund__c = fund2.Id;
            update assessmentStageDefinition7;
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_40), 'Invalid exception message');
        }

        // Update AssessmentStageDefinition - exception
        try {
            assessmentStageDefinition7.Number_of_Assessments__c = 100;
            update assessmentStageDefinition7;
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.part_of_error_message_12), 'Invalid exception message');
        }

        // Update AssessmentStageDefinition - exception
        try {
            assessmentStageDefinition7.Number_of_Assessments__c = null;
            update assessmentStageDefinition7;
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.error_message_41), 'Invalid exception message');
        }

        // Update AssessmentStageDefinition - true
        try {
            assessmentStageDefinition7.Number_of_Assessments__c = 1;
            assessmentStageDefinition7.Application_Assessment_Stage__c = 'ApplicationAssessmentStage_2';
            update assessmentStageDefinition7;
        } catch (Exception err) {
            System.assertEquals(false, true, 'Invalid exception');
        }

        // Update AssessmentStageDefinition - true
        try {
            update assessmentStageDefinition7;
        } catch (Exception err) {
            System.assertEquals(false, true, 'Invalid exception');
        }

        Test.stopTest();
    }
}