force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <description>Funds are used to group individual investments to an overall fund. In reports and dashboards Funds are used as an important filter to look at a portfolio per fund.</description>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Fees_Paid__c</fullName>
    <label>Fees Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Fund_Balance__c.field-meta.xml
<CustomField>
    <fullName>Fund_Balance__c</fullName>
    <label>Fund Balance</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Interest_Repaid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Repaid__c</fullName>
    <label>Interest Repaid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Investment_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Investment_Principal_Disbursed__c</fullName>
    <description>The total principal amount disbursed to investees from this fund</description>
    <label>Investment Principal Disbursed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Penalties_Paid__c.field-meta.xml
<CustomField>
    <fullName>Penalties_Paid__c</fullName>
    <label>Penalties Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Total_Draw_Down__c.field-meta.xml
<CustomField>
    <fullName>Total_Draw_Down__c</fullName>
    <label>Total Draw Down</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Total_Fund_Repayments__c.field-meta.xml
<CustomField>
    <fullName>Total_Fund_Repayments__c</fullName>
    <description>Total amount of funds repaid back to the investor</description>
    <label>Total Fund Repayments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>The amount within this transaction assigned to fees</description>
    <inlineHelpText>The amount within this transaction assigned to fees</inlineHelpText>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Fund_Cashflow_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fund_Cashflow_Amount__c</fullName>
    <formula>CASE(text(Type__c ),
&quot;Disbursement&quot;,-Amount__c,
&quot;Repayment&quot;,Amount__c,
&quot;Fee&quot;,Amount__c,
&quot;Disbursement Correction&quot;,Amount__c,
&quot;Repayment Correction&quot;,-Amount__c,
&quot;Fee Correction&quot;,Amount__c,
&quot;Schedule (Paid)&quot;,Amount__c,
&quot;Schedule (Partially Paid)&quot;,Amount__c,
&quot;Schedule (Late)&quot;,Amount__c,
&quot;Schedule (Not Due)&quot;,Amount__c,
&quot;Schedule (Partially Paid (Late))&quot;,Amount__c,
&quot;Fund Drawdown&quot;,Amount__c,
&quot;Fund Repayment&quot;,-Amount__c,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fund Cashflow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <description>The amount within this transaction assigned to interest</description>
    <inlineHelpText>The amount within this transaction assigned to interest</inlineHelpText>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Late_Repayment_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Late_Repayment_Fee_Amount__c</fullName>
    <label>Late Repayment Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of transaction</description>
    <inlineHelpText>Type of transaction</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Disbursement Correction</fullName>
            </value>
            <value>
                <fullName>Repayment Correction</fullName>
            </value>
            <value>
                <fullName>Fee Correction</fullName>
            </value>
            <value>
                <fullName>Fund Drawdown</fullName>
            </value>
            <value>
                <fullName>Fund Repayment</fullName>
            </value>
            <value>
                <fullName>Schedule (Not Due)</fullName>
            </value>
            <value>
                <fullName>Schedule (Late)</fullName>
            </value>
            <value>
                <fullName>Schedule (Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid)</fullName>
            </value>
            <value>
                <fullName>Schedule (Partially Paid (Late))</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PopulateFundFieldsBatch.cls
public without sharing class PopulateFundFieldsBatch implements Database.Batchable<SObject>, Database.Stateful {

    public Set<Id> fundIds;
    public PopulateFundFieldsBatch(Set<Id> fundIds) {
        this.fundIds = fundIds;
    }

    Map<Id, tempFundCalcData> fundsMap = new Map<Id, tempFundCalcData>();
    public class tempFundCalcData {
        Decimal investmentPrincipalDisbursed;
        Decimal totalDrawDown;
        Decimal totalFundRepayments;
        Decimal fundCashFlowAmount;
        Decimal interestRepaid;
        Decimal feeRepaid;
        Decimal penaltiesRepaid;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
                SELECT Fund__c, Amount__c, Type__c, Fund_Cashflow_Amount__c, Interest_Amount__c, Fee_Amount__c, Late_Repayment_Fee_Amount__c
                FROM Transaction__c
                WHERE Fund__c IN :fundIds
        ]);
    }
 
    public void execute(Database.BatchableContext bc, List<Transaction__c> scope) {
        for (Transaction__c tr : scope) {
            if (!fundsMap.containsKey(tr.Fund__c)) {
                tempFundCalcData baseFund = new tempFundCalcData();
                baseFund.investmentPrincipalDisbursed = 0;
                baseFund.totalDrawDown = 0;
                baseFund.totalFundRepayments = 0;
                baseFund.fundCashFlowAmount = 0;
                baseFund.interestRepaid = 0;
                baseFund.feeRepaid = 0;
                baseFund.penaltiesRepaid = 0;
                fundsMap.put(tr.Fund__c, baseFund);
            }
            tempFundCalcData baseFund = fundsMap.get(tr.Fund__c);
            switch on tr.Type__c {
                when 'Disbursement' {
                    if (tr.Amount__c != null) baseFund.investmentPrincipalDisbursed += tr.Amount__c;
                    if (tr.Fund_Cashflow_Amount__c != null) baseFund.fundCashFlowAmount += tr.Fund_Cashflow_Amount__c;
                }
                when 'Repayment' {
                    if (tr.Amount__c != null) baseFund.totalFundRepayments += tr.Amount__c;
                    if (tr.Fund_Cashflow_Amount__c != null) baseFund.fundCashFlowAmount += tr.Fund_Cashflow_Amount__c;
                    if (tr.Interest_Amount__c != null) baseFund.interestRepaid += tr.Interest_Amount__c;
                    if (tr.Fee_Amount__c != null) baseFund.feeRepaid += tr.Fee_Amount__c;
                    if (tr.Late_Repayment_Fee_Amount__c != null) baseFund.penaltiesRepaid += tr.Late_Repayment_Fee_Amount__c;
                }
                when 'Fund Drawdown' {
                    if (tr.Amount__c != null) baseFund.totalDrawDown += tr.Amount__c;
                    if (tr.Fund_Cashflow_Amount__c != null) baseFund.fundCashFlowAmount += tr.Fund_Cashflow_Amount__c;
                }
                when 'Fund Repayment' {
                    if (tr.Amount__c != null) baseFund.totalFundRepayments += tr.Amount__c;
                    if (tr.Fund_Cashflow_Amount__c != null) baseFund.fundCashFlowAmount += tr.Fund_Cashflow_Amount__c;
                }
            }
            fundsMap.put(tr.Fund__c, baseFund);
        }
    }

    public void finish(Database.BatchableContext bc) {
        List<Fund__c> funds = [
                SELECT Investment_Principal_Disbursed__c, Total_Draw_Down__c, Total_Fund_Repayments__c, Fund_Balance__c, Interest_Repaid__c, Fees_Paid__c, Penalties_Paid__c
                FROM Fund__c
                WHERE Id IN :fundsMap.keySet()
        ];
        for (Fund__c fd : funds) {
            if (fundsMap.containsKey(fd.Id)) {
                tempFundCalcData baseFund = fundsMap.get(fd.Id);
                fd.Investment_Principal_Disbursed__c = baseFund.investmentPrincipalDisbursed;
                fd.Total_Draw_Down__c = baseFund.totalDrawDown;
                fd.Total_Fund_Repayments__c = baseFund.totalFundRepayments;
                fd.Fund_Balance__c = baseFund.fundCashFlowAmount;
                fd.Interest_Repaid__c = baseFund.interestRepaid;
                fd.Fees_Paid__c = baseFund.feeRepaid;
                fd.Penalties_Paid__c = baseFund.penaltiesRepaid;
            }
        }
        update funds;
    }
}