force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment of an application in a certain stage.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the score for 1 criteria for 1 assessor for an assessment</description>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Assessment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment_Criteria_Definition__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Criteria_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Criteria Definition</label>
    <referenceTo>Assessment_Criteria_Definition__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Selected_Picklist_Value__c.field-meta.xml
<CustomField>
    <fullName>Selected_Picklist_Value__c</fullName>
    <label>Selected Picklist Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/Assessment_Criteria_Definition__c.object-meta.xml
<CustomObject>
    <description>The definition of a criteria that belongs to 1 assessment stage definition and will be instantiated into each assessment that is generated for the particular stage.</description>
    <label>Assessment Criteria Definition</label>
    <nameField>
        <label>Assessment Criteria Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Maximum_Rating__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Rating__c</fullName>
    <label>Maximum Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Minimum_Rating__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Rating__c</fullName>
    <label>Minimum Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <inlineHelpText>Use a semicolon as a separator</inlineHelpText>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria_Definition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessmentCriteriaEditorController.cls
public without sharing class AssessmentCriteriaEditorController {
    public class CustomException extends Exception {
    }

    @AuraEnabled
    public static List<Assessment_Criteria__c> getAssessmentCriteria(Id assessmentId) {
        try {
            return [SELECT Name, Type__c, Rating__c, Selected_Picklist_Value__c, Comment__c, Assessment_Criteria_Definition__r.Picklist_Values__c, Assessment_Criteria_Definition__r.Minimum_Rating__c, Assessment_Criteria_Definition__r.Maximum_Rating__c, Assessment_Criteria_Definition__r.sfims__Description__c FROM Assessment_Criteria__c WHERE Assessment__c = :assessmentId];
        } catch (Exception err) {
            throw new CustomException(err.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean setAssessmentCriteria(List<Assessment_Criteria__c> criteria) {
        try {
            update criteria;
            return true;
        } catch (Exception err) {
            throw new CustomException(err.getMessage());
        }
    }
}