force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>An assessment of an application in a certain stage.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/Assessment_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the score for 1 criteria for 1 assessor for an assessment</description>
    <label>Assessment Criteria</label>
    <nameField>
        <label>Assessment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Criteria__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Criteria</relationshipLabel>
    <relationshipName>Assessment_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Criteria__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAssessmentCriteriaEditorController.cls
@IsTest
private with sharing class TestAssessmentCriteriaEditorController {
    @IsTest static void test_AssessmentCriteriaEditorController() {
        Test.startTest();
        Assessment__c assessment = new Assessment__c(
            Name = 'Test',
            Status__c = 'Pending'
        );
        insert assessment;
        System.assertEquals(1, [SELECT Id FROM Assessment__c].size(), 'Invalid size');
        Assessment_Criteria__c criteria1 = new Assessment_Criteria__c(Assessment__c = assessment.Id, Type__c = 'Text');
        Assessment_Criteria__c criteria2 = new Assessment_Criteria__c(Assessment__c = assessment.Id, Type__c = 'Text');
        Assessment_Criteria__c criteria3 = new Assessment_Criteria__c(Assessment__c = assessment.Id, Type__c = 'Text');
        insert new List<Assessment_Criteria__c>{
                criteria1, criteria2, criteria3
        };
        System.assertEquals(3, [SELECT Id FROM Assessment_Criteria__c].size(), 'Invalid size');
        System.assertEquals(3, AssessmentCriteriaEditorController.getAssessmentCriteria(assessment.Id).size(), 'Invalid size');
        criteria1.Name = 'UpdateName';
        System.assertEquals(true, AssessmentCriteriaEditorController.setAssessmentCriteria(new List<Assessment_Criteria__c>{
                criteria1, criteria2, criteria3
        }), 'Invalid save');
        System.assertEquals(1, [SELECT Id FROM Assessment_Criteria__c WHERE Name = 'UpdateName'].size(), 'Invalid size');
        delete [SELECT Id FROM Assessment_Criteria__c WHERE Id =: criteria1.Id];
        try {
            AssessmentCriteriaEditorController.setAssessmentCriteria(new List<Assessment_Criteria__c>{
                criteria1, criteria2, criteria3
            });
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
           
        }
        Test.stopTest();
    }
}