force-app/main/default/objects/Task/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <label>Custom</label>
</RecordType>

force-app/main/default/objects/Task_List_Template__c/Task_List_Template__c.object-meta.xml
<CustomObject>
    <label>Task List Template</label>
    <nameField>
        <displayFormat>TLT-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Object Name with namespace</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Status_Field__c.field-meta.xml
<CustomField>
    <fullName>Object_Status_Field__c</fullName>
    <inlineHelpText>Object field name with namespace</inlineHelpText>
    <label>Object Status Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template__c/fields/Trigger_Status__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Status__c</fullName>
    <label>Trigger Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/Task_List_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Task List Template Item</label>
    <nameField>
        <displayFormat>TLTI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Depends_On__c.field-meta.xml
<CustomField>
    <fullName>Depends_On__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depends On</label>
    <referenceTo>Task_List_Template_Item__c</referenceTo>
    <relationshipLabel>Task List Template Items</relationshipLabel>
    <relationshipName>Task_List_Template_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Task_List_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_List_Template__c</fullName>
    <label>Task List Template</label>
    <referenceTo>Task_List_Template__c</referenceTo>
    <relationshipLabel>Task List Template Items</relationshipLabel>
    <relationshipName>Task_List_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTriggerHelper.cls
/** Action list functionality * @author Alexey Eliseev * @date 8/28/19 **/
@IsTest
private with sharing class TestTriggerHelper {
    @IsTest static void test_TriggerHelper() {
        Test.startTest();

        /** Insert **/
        Task_List_Template__c taskListTemplate1 = new Task_List_Template__c(Object_Name__c = 'Case', Object_Status_Field__c = 'Type', Trigger_Status__c = 'Other');
        insert taskListTemplate1;
        System.assertEquals(1, [SELECT Id FROM Task_List_Template__c].size(), 'Task List Template counts are not correct');

        Task_List_Template_Item__c taskListTemplateItem1 = new Task_List_Template_Item__c(
                Flow_Name__c = 'Test_Flow',
                Task_Type__c = 'Custom',
                Subject__c = 'Fill in form',
                Priority__c = 'Low',
                Task_List_Template__c = taskListTemplate1.Id
        );
        insert taskListTemplateItem1;
        System.assertEquals(1, [SELECT Id FROM Task_List_Template_Item__c].size(), 'Task List Template Item counts are not correct');

        Task_List_Template_Item__c taskListTemplateItem2 = new Task_List_Template_Item__c(
                Flow_Name__c = 'Test_Flow',
                Task_Type__c = 'Custom',
                Subject__c = 'Fill in form',
                Priority__c = 'Low',
                Task_List_Template__c = taskListTemplate1.Id,
                Depends_On__c = taskListTemplateItem1.Id
        );
        insert taskListTemplateItem2;
        System.assertEquals(2, [SELECT Id FROM Task_List_Template_Item__c].size(), 'Task List Template Item counts are not correct');

        Case case1 = new Case(Type = 'Other');
        insert case1;

        List<Case> cases = new List<Case>{
                case1
        };
 
        try {
            TriggerHelper.createCustomTask(new Map<Id, Case>(cases), null, false);
        } catch (Exception err) {
            System.assertEquals(0, err.getMessage().length(), 'Invalid exception message');
        }
        System.assertEquals(2, [SELECT Id FROM Task].size(), 'Task counts are not correct');
        System.assertEquals(1, [SELECT Id FROM Task WHERE Status = 'Open'].size(), 'Task counts are not correct');

        /** Update **/

        List<Case> oldCases = new List<Case>(cases);
        for (Case itemCase : oldCases) {
            itemCase.Type = 'Mechanical';
        }
        cases = [SELECT Type, OwnerId FROM Case];

        try {
            TriggerHelper.createCustomTask(new Map<Id, Case>(cases), new Map<Id, Case>(oldCases), true);
        } catch (Exception err) {
            System.assertEquals(0, err.getMessage().length(), 'Invalid exception message');
        }
        Test.stopTest();
    }
}