force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Loan__r.Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected__c</fullName>
    <formula>Fees_Expected__c + Interest_Expected0__c + Late_Repayment_Fees_Expected0__c + Principal_Expected__c + Interest_Bonus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LoanUtils.cls
public with sharing class LoanUtils {

    public static Double calculatePMT(Integer instalmentCount, Integer periodCount, String periodUnit, Integer gracePeriodCount, String gracePeriodType, Decimal loanAmount, Decimal interestRate){
        
        // calculate PMT value
        Double PMT_value = 0;
        
        Decimal periodsPerYear = getPeriodsPerYear(periodCount,periodUnit);
        Decimal interestPerPeriod = 0;
        if(interestRate != null) interestPerPeriod = (interestRate/periodsPerYear)/100;
        
        // count number of principal payment schedules
        Integer numberOfPrincipalPayments = instalmentCount;
        if(gracePeriodType != 'None'){
            numberOfPrincipalPayments -= gracePeriodCount;
        }
        
        if(interestPerPeriod == 0 || interestPerPeriod == null){
            PMT_value = loanAmount/numberOfPrincipalPayments;
        } else {
            PMT_value = (interestPerPeriod/(1 - Math.pow(Double.valueOf(1+interestPerPeriod) , Double.valueOf(-1*numberOfPrincipalPayments)))) * loanAmount;
        }
        // round to 2 decimals
        PMT_value = Decimal.valueOf(PMT_value).setScale(2);
        return PMT_value;
    }  

    public static Decimal getPeriodsPerYear(Integer periodCount, String periodUnit){
        // system.debug(periodCount);
        // we need to take into account decimals because there might be an unwhole amount of periods per year, e.g. in case of a single 8-year period
        Decimal periodCountDecimal = Decimal.valueOf(periodCount);
    
        Decimal periodsPerYear = 1;
        if(periodUnit == 'Days' ) periodsPerYear = Decimal.valueOf(365).divide(periodCountDecimal,2);
        else if(periodUnit == 'Weeks') periodsPerYear = Decimal.valueOf(52).divide(periodCountDecimal,2);
        else if(periodUnit == 'Months') periodsPerYear = Decimal.valueOf(12).divide(periodCountDecimal,2);
        else if(periodUnit == 'Years') periodsPerYear = Decimal.valueOf(1).divide(periodCountDecimal,2);

        // system.debug(periodsPerYear);

        return periodsPerYear;      
    }  

    @AuraEnabled
    public static List<Repayment_Schedule__c> getLoanSchedule(String loanId){
        if (!Repayment_Schedule__c.SObjectType.getDescribe().isAccessible()) { 
            throw new AuraHandledException(System.Label.sfims.error_message_28);
        }          
        return [
            SELECT Id, Name, Status__c, Due_Date__c, Principal_Expected__c, Interest_Expected0__c, 
                Fees_Expected__c, Interest_Rate__c, Total_Expected__c
            FROM Repayment_Schedule__c WHERE Loan__c = :loanId 
        ];
    }

    @AuraEnabled
    public static List<RepaymentScheduleWrapper> getLoanScheduleWrappers(String loanId){
        if (!Repayment_Schedule__c.SObjectType.getDescribe().isAccessible()) { 
            throw new AuraHandledException(System.Label.sfims.error_message_28);
        }                  
        // system.debug(loanId);
        List<RepaymentScheduleWrapper> rswList = new List<RepaymentScheduleWrapper>();
        for(Repayment_Schedule__c rs : [
            SELECT Id, Name, Status__c, Due_Date__c, Principal_Expected__c, Interest_Expected0__c,
                Fees_Expected__c, Interest_Rate__c, Total_Expected__c
            FROM Repayment_Schedule__c WHERE Loan__c = :loanId
        ])
        {
            RepaymentScheduleWrapper rsw = new RepaymentScheduleWrapper(rs);
            rswList.add(rsw);
        }
        return rswList;
    }    


    @AuraEnabled
    public static Boolean updateLoanSchedule(List<Repayment_Schedule__c> editedLoanScheduleList){
        if (!Repayment_Schedule__c.SObjectType.getDescribe().isUpdateable()) { 
            throw new AuraHandledException(System.Label.sfims.error_message_29);
        }                  
        try{
            DMLManager.updateAsUser(editedLoanScheduleList);
            return true;
        } catch(Exception e){
            return false;
        }
    }

}