force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Expected_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_End_Date__c</fullName>
    <label>Expected End Date</label>
    <summarizedField>Repayment_Schedule__c.Due_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Repayment_Schedule__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Recalculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Recalculation_Status__c</fullName>
    <defaultValue>&#39;Not Needed&#39;</defaultValue>
    <label>Recalculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Needed</fullName>
                <default>true</default>
                <label>Not Needed</label>
            </value>
            <value>
                <fullName>Pending Recalculation</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date the Loan Event occured</description>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Event_Type__c</fullName>
    <label>Loan Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Creation</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Interest Rate Change</fullName>
            </value>
            <value>
                <fullName>Interest Rollup Recalculation</fullName>
            </value>
            <value>
                <fullName>Closed (Written Off)</fullName>
            </value>
            <value>
                <fullName>Closed (Early Repayment)</fullName>
            </value>
            <value>
                <fullName>Closed (All Obligations met)</fullName>
            </value>
            <value>
                <fullName>Bullet Repayment</fullName>
            </value>
            <value>
                <fullName>Automatic Schedule Migration for Migrated Loan</fullName>
            </value>
            <value>
                <fullName>Fee Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Review_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Review_Frequency__c</fullName>
    <description>This defines how often the variable interest rate will be considered.</description>
    <label>Interest Rate Review Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Custom.recordType-meta.xml
<RecordType>
    <fullName>Custom</fullName>
    <active>true</active>
    <label>Custom</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Task_List_Template__c/Task_List_Template__c.object-meta.xml
<CustomObject>
    <label>Task List Template</label>
    <nameField>
        <displayFormat>TLT-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Object Name with namespace</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Status_Field__c.field-meta.xml
<CustomField>
    <fullName>Object_Status_Field__c</fullName>
    <inlineHelpText>Object field name with namespace</inlineHelpText>
    <label>Object Status Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template__c/fields/Trigger_Status__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Status__c</fullName>
    <label>Trigger Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/Task_List_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Task List Template Item</label>
    <nameField>
        <displayFormat>TLTI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Assignee_Field__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Field__c</fullName>
    <inlineHelpText>API field name with user</inlineHelpText>
    <label>Assignee Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Assignee_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Type__c</fullName>
    <label>Assignee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record Owner</fullName>
                <default>true</default>
                <label>Record Owner</label>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Related Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Assignee_User__c.field-meta.xml
<CustomField>
    <fullName>Assignee_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assignee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Task_List_Template_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Depends_On__c.field-meta.xml
<CustomField>
    <fullName>Depends_On__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Depends On</label>
    <referenceTo>Task_List_Template_Item__c</referenceTo>
    <relationshipLabel>Task List Template Items</relationshipLabel>
    <relationshipName>Task_List_Template_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Task_List_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_List_Template__c</fullName>
    <label>Task List Template</label>
    <referenceTo>Task_List_Template__c</referenceTo>
    <relationshipLabel>Task List Template Items</relationshipLabel>
    <relationshipName>Task_List_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <default>true</default>
                <label>Custom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHelper.cls
public with sharing class TriggerHelper {
    public class CustomException extends Exception {
    }
    /** Auto-assigned tasks functionality * @author Alexey Eliseev * @date 8/28/19
    *   for use
    *   if (Trigger.isAfter) {
    *       if (Trigger.isInsert || Trigger.isUpdate) {
    *           TriggerHelper.createCustomTask(Trigger.newMap, Trigger.oldMap, Trigger.isUpdate);
    *       }
    *   }
    * **/
    public static void createCustomTask(Map<Id, SObject> TriggerNewMap, Map<Id, SObject> TriggerOldMap, Boolean TriggerIsUpdate) {
        // list of new tasks for insert after
        Map<String, Task> tasks = new Map<String, Task>();
        String objectName = String.valueOf(TriggerNewMap.getSObjectType());
        // get record types
        Id customRecordTypeId;
        Map<String, RecordTypeInfo> recordTypes = Schema.SObjectType.Task.getRecordTypeInfosByName();
        if (recordTypes.containsKey('Custom')) {
            customRecordTypeId = recordTypes.get('Custom').getRecordTypeId();
        } else {
            throw new CustomException(System.Label.sfims.error_message_36);
        }
        Id standardRecordTypeId;
        if (recordTypes.containsKey('Standard')) {
            standardRecordTypeId = recordTypes.get('Standard').getRecordTypeId();
        } else {
            throw new CustomException(System.Label.sfims.error_message_37);
        }
        // get all templates and template items for the current object
        List<Task_List_Template__c> templatesCurrObj = [
                SELECT Object_Status_Field__c, Trigger_Status__c, (
                        SELECT Subject__c, Assignee_Type__c, Assignee_User__c, Assignee_Field__c, Description__c, Priority__c, Depends_On__c, Flow_Name__c, Task_Type__c
                        FROM Task_List_Template_Items__r
                )
                FROM Task_List_Template__c
                WHERE Object_Name__c = :objectName
        ];

        Map<String, String> relatedFields = new Map<String, String>();
        if (templatesCurrObj.size() > 0) {
            // get related fields
            for (Task_List_Template__c taskListTemplate : templatesCurrObj) {
                String objectField = taskListTemplate.Object_Status_Field__c;
                if (String.isNotBlank(objectField)) {
                    // check status field
                    for (Id recordId : TriggerNewMap.keySet()) {
                        Boolean isTrue = true;
                        if (TriggerIsUpdate) {
                            if (TriggerNewMap.get(recordId).get(objectField) == TriggerOldMap.get(recordId).get(objectField)) {
                                isTrue = false;
                            }
                        }
                        // add related field to list
                        if (isTrue && TriggerNewMap.get(recordId).get(objectField) == taskListTemplate.Trigger_Status__c) {
                            for (Task_List_Template_Item__c taskListTemplateItem : taskListTemplate.Task_List_Template_Items__r) {
                                if (taskListTemplateItem.Assignee_Type__c == 'Related Field') {
                                    if (taskListTemplateItem.Assignee_Field__c != null) {
                                        String key = (String) taskListTemplate.Id + (String) taskListTemplateItem.Id + (String) recordId;
                                        relatedFields.put(key, taskListTemplateItem.Assignee_Field__c);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            // get all tasks for the current object
            for (Task_List_Template__c taskListTemplate : templatesCurrObj) {
                String objectField = taskListTemplate.Object_Status_Field__c;
                if (String.isNotBlank(objectField)) {
                    for (Id recordId : TriggerNewMap.keySet()) {
                        // check stage change
                        Boolean isTrue = true;
                        if (TriggerIsUpdate) {
                            if (TriggerNewMap.get(recordId).get(objectField) == TriggerOldMap.get(recordId).get(objectField)) {
                                isTrue = false;
                            }
                        }
                        if (isTrue && TriggerNewMap.get(recordId).get(objectField) == taskListTemplate.Trigger_Status__c) {
                            // if the status is valid - create tasks
                            for (Task_List_Template_Item__c taskListTemplateItem : taskListTemplate.Task_List_Template_Items__r) {
                                Id ownerId;
                                switch on taskListTemplateItem.Assignee_Type__c {
                                    when 'Record Owner' {
                                        if (TriggerIsUpdate) {
                                            ownerId = (Id) TriggerNewMap.get(recordId).get('OwnerId');
                                        } else {
                                            ownerId = UserInfo.getUserId();
                                        }
                                    }
                                    when 'User' {
                                        ownerId = taskListTemplateItem.Assignee_User__c;
                                    }
                                    when 'Related Field' {
                                        String key = (String) taskListTemplate.Id + (String) taskListTemplateItem.Id + (String) recordId;
                                        if (relatedFields.containsKey(key) && TriggerNewMap.get(recordId).get(relatedFields.get(key)) != null) {
                                            ownerId = (Id) TriggerNewMap.get(recordId).get(relatedFields.get(key));
                                        } else {
                                            throw new CustomException(System.Label.sfims.error_message_38);
                                        }
                                    }
                                    when else {
                                        ownerId = UserInfo.getUserId();
                                    }
                                }
                                tasks.put(recordId + '_' + taskListTemplateItem.Id, new Task(
                                        ActivityDate = Date.today(),
                                        Subject = taskListTemplateItem.Subject__c,
                                        OwnerId = ownerId,
                                        Priority = taskListTemplateItem.Priority__c,
                                        Status = (taskListTemplateItem.Depends_On__c != null) ? 'Pending' : 'Open',
                                        WhatId = recordId,
                                        Read_Only__c = true,
                                        RecordTypeId = (taskListTemplateItem.Task_Type__c == 'Custom') ? customRecordTypeId : standardRecordTypeId,
                                        Description = taskListTemplateItem.Description__c,
                                        Task_List_Template_Item__c = taskListTemplateItem.Id,
                                        Depends_On__c = (taskListTemplateItem.Depends_On__c != null) ? taskListTemplateItem.Depends_On__c : null
                                ));
                            }
                        }
                    }
                }
            }
        }
        // create tasks
        if (tasks.size() > 0) {
            List<Task> insertList = new List<Task>();
            List<Task> notInsertList = new List<Task>();
            Map<String, Id> junctions = new Map<String, Id>();
            // find the last elements in a queue, without dependencies
            for (String key : tasks.keySet()) {
                Task taskItem = tasks.get(key);
                if (taskItem.Depends_On__c == null) {
                    insertList.add(taskItem);
                } else {
                    notInsertList.add(taskItem);
                }
            }
            if (insertList.size() > 0) {
                insert insertList;
                // remember tasks Ids
                for (Task taskItem : insertList) {
                    junctions.put(taskItem.WhatId + '_' + taskItem.Task_List_Template_Item__c, taskItem.Id);
                }
                while (notInsertList.size() > 0) {
                    insertList.clear();
                    Integer size = notInsertList.size();
                    List<Task> tmpNotInsertList = new List<Task>();
                    for (Integer i = 0; i < size; i++) {
                        if (notInsertList[i].WhatId != null && notInsertList[i].Depends_On__c != null) {
                            if (junctions.containsKey(notInsertList[i].WhatId + '_' + notInsertList[i].Depends_On__c)) {
                                notInsertList[i].Depends_On__c = junctions.get(notInsertList[i].WhatId + '_' + notInsertList[i].Depends_On__c);
                                insertList.add(notInsertList[i]);

                            } else {
                                tmpNotInsertList.add(notInsertList[i]);
                            }
                        } else {
                            tmpNotInsertList.add(notInsertList[i]);
                        }
                    }
                    notInsertList = new List<Task>(tmpNotInsertList);
                    if (insertList.size() > 0) {
                        insert insertList;
                        for (Task taskItem : insertList) {
                            junctions.put(taskItem.WhatId + '_' + taskItem.Task_List_Template_Item__c, taskItem.Id);
                        }
                    } else {
                        if (notInsertList.size() > 0) {
                            insert notInsertList;
                            notInsertList.clear();
                        }
                    }
                }
            } else {
                if (notInsertList.size() > 0) {
                    insert notInsertList;
                }
            }
        }
    }

    /** END Auto-assigned tasks functionality **/
    public static List<String> getObjectFieldList(String objectName) {
        List<String> response = new List<String>();
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType cType = schemaMap.get(objectName);
        if (cType != null) {
            Map<String, Schema.SObjectField> schemaMapField = cType.getDescribe().fields.getMap();
            for (String fieldName : schemaMapField.keySet()) {
                response.add(schemaMapField.get(fieldName).getDescribe().getName());
            }
        }
        return response;
    }

    public static String runRecalculateLoanFromScratch(List<Investment__c> loansToUpdate) {
        if (!loansToUpdate.isEmpty()) {
            try {
                DMLManager.updateAsSystem(loansToUpdate);
            } catch(System.DmlException e) {
                System.debug(e.getDmlMessage(0));
                return System.Label.sfims.part_of_error_message_8 + ': ' + e.getDmlMessage(0);
            }
        
            List<String> standardLoanIds = new List<String>();
            List<String> openEndedLoanIds = new List<String>();
            for (Investment__c theLoan : loansToUpdate) {
                if (theLoan.Open_Ended_Loan__c) openEndedLoanIds.add(theLoan.Id);
                else standardLoanIds.add(theLoan.Id);
            }

            if (!standardLoanIds.isEmpty()) {
                if (TriggerHelper.checkAsyncApexJobs('RecalculateLoanFromScratchBatch').isEmpty()) {
                    Database.executeBatch(new RecalculateLoanFromScratchBatch(), 1);
                }
                
            }

            if (!openEndedLoanIds.isEmpty()) {
                if (TriggerHelper.checkAsyncApexJobs('RecalculateOpenEndedLoan').isEmpty()) {
                    Database.executeBatch(new RecalculateOpenEndedLoan(), 1);
                }
            }    
        }

        return null;
    }

    public static List<AsyncApexJob> checkAsyncApexJobs(String apexClassName) {
        return [
            SELECT Id
            FROM AsyncApexJob
            WHERE JobType = 'BatchApex' AND ApexClass.Name = :apexClassName
                AND Status IN ('Holding', 'Queued', 'Preparing', 'Processing')
        ];
    }

    public static Map<String, List<SObject>> processInterestRates(Investment__c theLoan, Date startDate, List<Interest_Rate__c> interestRates) {
        // System.debug('TriggerHelper.processInterestRates');
        Map<String, List<SObject>> returnMap = new Map<String, List<SObject>>();
        List<Investment__c> loansToUpdate = new List<Investment__c>();
        List<Loan_Event__c> newLoanEvents = new List<Loan_Event__c>();
        Set<Date> dateList = new Set<Date>();
        
        Date endDate;
        if (theLoan.Expected_End_Date__c != null && theLoan.Expected_End_Date__c < System.today()) {
            endDate = theLoan.Expected_End_Date__c;
        } else {
            endDate = System.today();
        }
        
        Boolean beforeStartDate = false;
        // define a loan event date for each rate
        for (Interest_Rate__c rate : interestRates) {
            // System.debug(rate);
            if (rate.Date__c < startDate) beforeStartDate = true;
            else if (rate.Date__c >= startDate && rate.Date__c < endDate) {
                if (theLoan.Loan_Product__r.Interest_Rate_Review_Frequency__c == 'Daily') {
                    dateList.add(rate.Date__c.addDays(1));
                } else {
                    Date eventDate;
                    Integer counter = 0;
                    do {
                        switch on theLoan.Loan_Product__r.Interest_Rate_Review_Frequency__c {
                            when 'Monthly' {
                                eventDate = startDate.addMonths(1 + counter);
                            }
                            when 'Quarterly' {
                                eventDate = startDate.addMonths(3 * (1 + counter));
                            }
                            when 'Yearly' {
                                eventDate = startDate.addYears(1 + counter);
                            }
                        }
                        counter++;
                    } while (rate.Date__c >= eventDate);
                    // System.debug(eventDate);
                    if (eventDate <= System.today()) dateList.add(eventDate); 
                }
            } 
        }
        // System.debug(dateList.size());
        // System.debug(dateList);
        if (!dateList.isEmpty()) {
            // this means that there are some new interest rates in active loan period
            // the loan should be recalculated 
            theLoan.Recalculation_Status__c = 'Pending Recalculation';
            loansToUpdate.add(theLoan);

            // check if there are loan events on the dates on which we need to create new loan events
            // remove these dates from the list
            List<Date> loanEventDates = new List<Date>();
            for (Loan_Event__c le : theLoan.Loan_Events__r) {
                loanEventDates.add(le.Event_Date__c);
            }
            // System.debug(loanEventDates.size());
            // System.debug(loanEventDates[0]);
            dateList.removeAll(loanEventDates);
            // System.debug(dateList.size());
            // create a new loan event for each date of the list
            for (Date newLoanEventDate : dateList) {
                newLoanEvents.add(new Loan_Event__c(
                    Event_Date__c = newLoanEventDate,
                    Investment__c = theLoan.Id,
                    Loan_Event_Type__c = 'Interest Rate Change',
                    Loan_Product__c = theLoan.Loan_Product__c
                ));
            }
        } else {
            if (beforeStartDate) {
                theLoan.Recalculation_Status__c = 'Pending Recalculation';
                loansToUpdate.add(theLoan);
            }
        }
        if (!loansToUpdate.isEmpty()) returnMap.put('loans', loansToUpdate);
        if (!newLoanEvents.isEmpty()) returnMap.put('loanEvents', newLoanEvents);
        return returnMap;
    }
}