force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Rate__c/fields/Interest_Rate_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Source__c</fullName>
    <label>Interest Rate Source</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Interest Rates</relationshipLabel>
    <relationshipName>Interest_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Grace_Periods__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Grace_Periods__c</fullName>
    <label>Number of Grace Periods</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Instalments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Instalments__c</fullName>
    <label>Number of Instalments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>Variable_Interest_Spread__c</fullName>
    <description>This is the margin that will be added or subtracted from the base interest rate.</description>
    <label>Variable Interest Spread</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Number_of_Grace_Periods__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Grace_Periods__c</fullName>
    <label>Number of Grace Periods</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Number_of_Instalments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Instalments__c</fullName>
    <label>Number of Instalments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>Variable_Interest_Spread__c</fullName>
    <label>Variable Interest Spread</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/CBO_Default_Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>CBO_Default_Variable_Interest_Spread__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Be Overridden On Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Review_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Review_Frequency__c</fullName>
    <description>This defines how often the variable interest rate will be considered.</description>
    <label>Interest Rate Review Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Source__c</fullName>
    <label>Interest Rate Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Interest</fullName>
            </value>
            <value>
                <fullName>Variable Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Reference_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reference_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is required if ‘Variable Interest’ is selected</description>
    <label>Interest Reference Rate</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Loan Products</relationshipLabel>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All transactions which occur on an Investment, such as disbursements, repayments and adjustments</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestRecalculateInterestRollupLoansBatch.cls
@isTest
private class TestRecalculateInterestRollupLoansBatch {
    @isTest static void test_batch() {
        // create a new interest rate source
        Interest_Rate_Source__c irs = new Interest_Rate_Source__c(Name = 'Test Interest Rate Source');
        insert irs;

        // create interest rates
        Interest_Rate__c ir1 = TestUtils.createNewInterestRate(irs.Id, System.today().addYears(-1), 1);
        Interest_Rate__c ir2 = TestUtils.createNewInterestRate(irs.Id, System.today().addMonths(-6), 2);
        
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct('Test Loan Product');
        lp.Interest_Rate_Source__c = 'Variable Interest';
        lp.Interest_Reference_Rate__c = irs.Id;
        lp.Interest_Rate_Review_Frequency__c = 'Daily';
        lp.CBO_Default_Variable_Interest_Spread__c = true;

        insert new List<SObject>{ir1, ir2, lp};
        
        // create a new loan
        Investment__c i = TestUtils.createNewLoan(System.today().addYears(-1), System.today().addMonths(-11));
        i.Loan_Product__c = lp.Id;
        i.Setup_Fee_Charging_Method__c = 'No Setup Fee';
        i.Number_of_Instalments__c = 60;
        i.Grace_Period_Type__c = 'Interest Rollup';
        i.Number_of_Grace_Periods__c = 12;    
        i.Disbursement_Method__c = 'Full disbursement at start';
        i.Variable_Interest_Spread__c = 5;
        i.Interest_Rate__c = null;
        insert i;

        // generate schedule
        insert LoanScheduler.generateScheduleById(i.Id);

        // add a disbursement
        Transaction__c t = TestUtils.createNewTransaction(i.Id, i.Amount__c, 'Disbursement', System.today().addYears(-1));
        DisburseLoanButtonController.saveData(i.Id, JSON.serialize(new List<Transaction__c>{t}), '[]');

        // run the batch
        Test.startTest();
        Database.executeBatch(new RecalculateInterestRollupLoansBatch(System.today()), 1);
        Test.stopTest();

        Date entryDate = System.today();
        System.assertEquals(1, [
            SELECT COUNT()
            FROM Loan_Event__c
            WHERE Investment__c = :i.Id AND Loan_Event_Type__c = 'Interest Rollup Recalculation' AND Event_Date__c = :entryDate
        ]);

        System.assertEquals(i.Number_of_Grace_Periods__c, [
            SELECT COUNT()
            FROM Repayment_Schedule__c
            WHERE Loan__c = :i.Id AND Status__c = 'Grace'
        ]);
    }
}