force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>7</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Date__c</fullName>
    <description>The date on which the Loan is (expected to be) disbursed. From this day on, interest will be charged (if applicable)</description>
    <inlineHelpText>The date on which the Loan is (expected to be) disbursed. From this day on, interest will be charged (if applicable)</inlineHelpText>
    <label>Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Open Ended loans are loans with no fixed end date and no fixed repayment schedule. Investees can disburse money from it and repay money to it whenever they want, as long as they don’t go over the principal amount.</description>
    <inlineHelpText>Open Ended loans are loans with no fixed end date and no fixed repayment schedule.</inlineHelpText>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Pending Disbursal</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed - All Obligations Met</fullName>
            </value>
            <value>
                <fullName>Closed - Written Off</fullName>
            </value>
            <value>
                <fullName>Closed - Early Repayment</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>Variable_Interest_Spread__c</fullName>
    <description>This is the margin that will be added or subtracted from the base interest rate.</description>
    <label>Variable Interest Spread</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Event__c/Loan_Event__c.object-meta.xml
<CustomObject>
    <description>This object tracks all key loan events that may occur on an investment record (creation, rescheduling, write-off, pay off etc.)</description>
    <label>Loan Event</label>
    <nameField>
        <label>Loan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Event__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Investment__c.field-meta.xml
<CustomField>
    <fullName>Investment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the loan (investment) that this loan event belongs to</description>
    <label>Investment</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loan Events</relationshipLabel>
    <relationshipName>Loan_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Event__c/fields/Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>Variable_Interest_Spread__c</fullName>
    <label>Variable Interest Spread</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Default_Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Interest_Rate__c</fullName>
    <label>Default Interest Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Review_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Review_Frequency__c</fullName>
    <description>This defines how often the variable interest rate will be considered.</description>
    <label>Interest Rate Review Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Reference_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reference_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is required if ‘Variable Interest’ is selected</description>
    <label>Interest Reference Rate</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Loan Products</relationshipLabel>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Maximum_Interest_Bandwidth__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Interest_Bandwidth__c</fullName>
    <label>Maximum Interest Bandwidth</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Minimum_Interest_Bandwidth__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Bandwidth__c</fullName>
    <label>Minimum Interest Bandwidth</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Open_Ended_Loan__c.field-meta.xml
<CustomField>
    <fullName>Open_Ended_Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Ended Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>States if the Repayment Schedule record is currenlty active (i.e. not rescheduled/refinanced/written off)</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE then this is a migration record</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This is a day from which the repayment schedule begins</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VariableInterestRateBatch.cls
public with sharing class VariableInterestRateBatch implements Database.Batchable<sObject>, Database.Stateful {
    // this batch defines which loans should be recalculated

    public final Date currentDate;
    
    public VariableInterestRateBatch(Date entryDate) {
        this.currentDate = entryDate;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Variable_Interest_Spread__c, Open_Ended_Loan__c, Disbursement_Date__c, Loan_Product__c,
                Loan_Product__r.Interest_Rate_Review_Frequency__c, Loan_Product__r.Interest_Reference_Rate__c,
                Loan_Product__r.Maximum_Interest_Bandwidth__c, Loan_Product__r.Minimum_Interest_Bandwidth__c,
                Loan_Product__r.Default_Interest_Rate__c, Grace_Period_Type__c,
                (
                    SELECT Start_Date__c, Due_Date__c
                    FROM Repayment_Schedules__r
                    WHERE (Start_Date__c < :currentDate OR Start_Date__c = null) AND Active__c = true AND Migration__c = false AND Status__c != 'Fee'
                    ORDER BY Start_Date__c ASC
                )
            FROM Investment__c
            WHERE Status__c = 'Active' AND Loan_Product__r.Interest_Rate_Source__c = 'Variable Interest'
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Investment__c> scope) {
        // System.debug(scope[0]);
        
        Investment__c theLoan = scope[0];
        List<Repayment_Schedule__c> rsToUpdate = VariableInterestRateBatch.processRepaymentSchedules(theLoan, currentDate);
        
        if (!rsToUpdate.isEmpty()) {
            Savepoint sp = Database.setSavepoint();
            Loan_Event__c le = new Loan_Event__c(
                Event_Date__c = currentDate,
                Investment__c = theLoan.Id,
                Loan_Event_Type__c = 'Interest Rate Change',
                Loan_Product__c = theLoan.Loan_Product__c
            );
            DMLManager.insertAsSystem(new List<Loan_Event__c>{le});
            
            if (!theLoan.Open_Ended_Loan__c) {
                DMLManager.updateAsUser(rsToUpdate);
                LoanTransactionProcessor.processLoanTransactions(new Set<Id>{theLoan.Id});
            } else {
                Map<String, String> result = RecalculateOpenEndedLoan.processOpenEndedLoan(theLoan.Id);
                // System.debug(result);
                if (result.containsKey('error')) {
                    Database.rollback(sp);
                    throw new ApplicationException(result.get('error'));
                }
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
        Database.executeBatch(new RecalculateInterestRollupLoansBatch(System.today()), 1);
    }

    public static List<Repayment_Schedule__c> processRepaymentSchedules(Investment__c theLoan, Date currentDate) {
        List<Repayment_Schedule__c> rsToUpdate = new List<Repayment_Schedule__c>();
        if (!theLoan.Repayment_Schedules__r.isEmpty()) {
            Repayment_Schedule__c rs = theLoan.Repayment_Schedules__r[0];
            if (theLoan.Open_Ended_Loan__c) {
                rs.Start_Date__c = theLoan.Disbursement_Date__c;
                rs.Due_Date__c = currentDate;
            }

            // check if today is a day when the loan should be recalculated
            Boolean toRecalculate = false;
            Date startDate;
            Date endDate;

            // System.debug(theLoan.Loan_Product__r.Interest_Rate_Review_Frequency__c);
            switch on theLoan.Loan_Product__r.Interest_Rate_Review_Frequency__c {
                when 'Daily' {
                    toRecalculate = true;
                    rs = theLoan.Repayment_Schedules__r[theLoan.Repayment_Schedules__r.size()-1];
                    startDate = rs.Start_Date__c;
                    endDate = rs.Due_Date__c;
                }
                when 'Monthly' {
                    // System.debug(rs.Start_Date__c.day());
                    // System.debug(currentDate.day());
                    if (rs.Start_Date__c.day() == currentDate.day()) {
                        toRecalculate = true;
                        startDate = currentDate.addMonths(-1);
                        endDate = currentDate;
                    }
                }
                when 'Quarterly' {
                    if (rs.Start_Date__c.day() == currentDate.day()) {
                        Decimal result = Decimal.valueOf(currentDate.month() - rs.Start_Date__c.month()).divide(3, 2);
                        if (result.intValue() == result) {
                            toRecalculate = true;
                            startDate = currentDate.addMonths(-3);
                            endDate = currentDate;
                        }
                    }
                }
                when 'Yearly' {
                    if (rs.Start_Date__c.day() == currentDate.day() && rs.Start_Date__c.month() == currentDate.month()) {
                        toRecalculate = true;
                        startDate = currentDate.addYears(-1);
                        endDate = currentDate;
                    }
                }
            }
            
            if (toRecalculate) {
                // check if new Interest Rates were added for the current period
                List<Interest_Rate__c> currentInterestRates = [
                    SELECT Date__c, Rate__c
                    FROM Interest_Rate__c
                    WHERE Interest_Rate_Source__c = :theLoan.Loan_Product__r.Interest_Reference_Rate__c
                        AND Date__c >= :startDate AND Date__c < :endDate
                    ORDER BY Date__c ASC
                ];

                if (theLoan.Loan_Product__r.Interest_Rate_Review_Frequency__c == 'Daily') {
                    Boolean toUpdate = false;
                    for (Integer i = currentInterestRates.size() - 1; i >= 0; i--) {
                        Interest_Rate__c rate = currentInterestRates[i];
                        if (rate.Date__c == currentDate.addDays(-1)) {
                            toUpdate = true;
                            break;
                        }
                    }
                    if (!toUpdate) currentInterestRates.clear();
                }

                if (!currentInterestRates.isEmpty()) {
                    if (theLoan.Open_Ended_Loan__c) {
                        rsToUpdate.add(rs);
                        return rsToUpdate;
                    } else {
                        // determine weighted average interest rate
                        Decimal interestRateOnStartDate = 0;
                        if (currentInterestRates[0].Date__c != startDate) {
                            Interest_Rate__c previousInterestRate = [
                                SELECT Date__c, Rate__c
                                FROM Interest_Rate__c
                                WHERE Interest_Rate_Source__c = :theLoan.Loan_Product__r.Interest_Reference_Rate__c
                                    AND Date__c < :startDate
                                ORDER BY Date__c DESC
                                LIMIT 1
                            ];
                            interestRateOnStartDate = previousInterestRate.Rate__c;
                        } else {
                            interestRateOnStartDate = currentInterestRates[0].Rate__c;
                            // currentInterestRates.remove(0);
                        }
                        System.debug(interestRateOnStartDate);

                        List<Repayment_Schedule__c> repaymentSchedules = [
                            SELECT Interest_Rate__c, Interest_Expected_Standard_Loan__c, Start_Date__c, Due_Date__c, Interest_Charge__c, Status__c
                            FROM Repayment_Schedule__c
                            WHERE Loan__c =: theLoan.Id
                                AND Due_Date__c > :startDate AND Active__c = true AND Migration__c = false AND Status__c != 'Fee'
                            ORDER BY Start_Date__c ASC
                        ];

                        Integer currentRate = 0;
                        for (Repayment_Schedule__c tempRS : repaymentSchedules) {
                            Date startInterestRateDate = tempRS.Start_Date__c;
                            Double expression = 0;
                            for (Integer i = currentRate; i < currentInterestRates.size(); i++) {
                                Interest_Rate__c rate = currentInterestRates[i];
                                if (rate.Date__c < tempRS.Due_Date__c) {
                                    expression += interestRateOnStartDate * startInterestRateDate.daysBetween(rate.Date__c);
                                    startInterestRateDate = rate.Date__c;
                                    interestRateOnStartDate = rate.Rate__c;
                                    currentRate++;
                                }
                            }
                            expression += interestRateOnStartDate * startInterestRateDate.daysBetween(tempRS.Due_Date__c);
                            // System.debug(expression);
                            Decimal weightedAverageInterestRate = expression / tempRS.Start_Date__c.daysBetween(tempRS.Due_Date__c);
                            // System.debug(weightedAverageInterestRate);
                            
                            // add variable interest spread
                            if (theLoan.Variable_Interest_Spread__c != null) {
                                weightedAverageInterestRate += theLoan.Variable_Interest_Spread__c;
                                // System.debug(weightedAverageInterestRate);
                            }

                            // System.debug(theLoan.Loan_Product__r.Maximum_Interest_Bandwidth__c);
                            // System.debug(theLoan.Loan_Product__r.Minimum_Interest_Bandwidth__c);
                            
                            // check if weighted average interest rate is out of allowed range
                            if (theLoan.Loan_Product__r.Maximum_Interest_Bandwidth__c != null
                                && weightedAverageInterestRate > theLoan.Loan_Product__r.Maximum_Interest_Bandwidth__c)
                                weightedAverageInterestRate = theLoan.Loan_Product__r.Maximum_Interest_Bandwidth__c;
                            if (theLoan.Loan_Product__r.Minimum_Interest_Bandwidth__c != null
                                && weightedAverageInterestRate < theLoan.Loan_Product__r.Minimum_Interest_Bandwidth__c)
                                weightedAverageInterestRate = theLoan.Loan_Product__r.Minimum_Interest_Bandwidth__c;

                            System.debug(weightedAverageInterestRate);
                            if (tempRS.Interest_Rate__c != weightedAverageInterestRate) {
                                // repayment schedule should be updated
                                if (theLoan.Grace_Period_Type__c == 'Interest Rollup' && tempRS.Status__c == 'Grace') tempRS.Interest_Charge__c *= weightedAverageInterestRate / tempRS.Interest_Rate__c;
                                else tempRS.Interest_Expected_Standard_Loan__c *= weightedAverageInterestRate / tempRS.Interest_Rate__c;
                                tempRS.Interest_Rate__c = weightedAverageInterestRate;
                                rsToUpdate.add(tempRS);
                            }
                            // System.debug('-----------------------------------------');
                        }
                    }
                }
            }
        }

        return rsToUpdate;
    }

}