force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Rate__c/fields/Interest_Rate_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Source__c</fullName>
    <label>Interest Rate Source</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Interest Rates</relationshipLabel>
    <relationshipName>Interest_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interest_Rate_Source__c/Interest_Rate_Source__c.object-meta.xml
<CustomObject>
    <label>Interest Rate Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Rate Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Day_Count_Convention__c.field-meta.xml
<CustomField>
    <fullName>Day_Count_Convention__c</fullName>
    <description>30/360 
This is a method that calculates interest based on assumed equal months (1/12th). 

Actual/365 
Calculate interest fees based on the number of days in the actual period. So if payments are monthly we charge between 28 and 31 days of interest, depending on the number of days in the month. 

Actual/365L 
Same as Actual/365 but for Leap years 366 days are used and not 365.</description>
    <label>Day Count Convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
                <default>true</default>
                <label>30/360</label>
            </value>
            <value>
                <fullName>Actual/365</fullName>
            </value>
            <value>
                <fullName>Actual/365L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <defaultValue>&#39;Full disbursement at start&#39;</defaultValue>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
                <default>true</default>
                <label>Full disbursement at start</label>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Instalments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Instalments__c</fullName>
    <label>Number of Instalments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>Variable_Interest_Spread__c</fullName>
    <description>This is the margin that will be added or subtracted from the base interest rate.</description>
    <label>Variable Interest Spread</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/CBO_Default_Variable_Interest_Spread__c.field-meta.xml
<CustomField>
    <fullName>CBO_Default_Variable_Interest_Spread__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Be Overridden On Loan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Day_Count_Convention__c.field-meta.xml
<CustomField>
    <fullName>Day_Count_Convention__c</fullName>
    <description>30/360 
This is a method that calculates interest based on assumed equal months (1/12th). 

Actual/365 
Calculate interest fees based on the number of days in the actual period. So if payments are monthly we charge between 28 and 31 days of interest, depending on the number of days in the month. 

Actual/365L 
Same as Actual/365 but for Leap years 366 days are used and not 365.</description>
    <label>Day Count Convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
            </value>
            <value>
                <fullName>Actual/365</fullName>
            </value>
            <value>
                <fullName>Actual/365L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Disbursement_Method__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Method__c</fullName>
    <label>Disbursement Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full disbursement at start</fullName>
            </value>
            <value>
                <fullName>Tranched disbursement allowed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Review_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Review_Frequency__c</fullName>
    <description>This defines how often the variable interest rate will be considered.</description>
    <label>Interest Rate Review Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Source__c</fullName>
    <label>Interest Rate Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Interest</fullName>
            </value>
            <value>
                <fullName>Variable Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Reference_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reference_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is required if ‘Variable Interest’ is selected</description>
    <label>Interest Reference Rate</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Loan Products</relationshipLabel>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestOverriddenLoanPageController.cls
@isTest
private class TestOverriddenLoanPageController {
    @isTest static void test_preview() {
        // create a new interest rate source
        Interest_Rate_Source__c irs = new Interest_Rate_Source__c(Name = 'Test Interest Rate Source');
        insert irs;

        // create interest rates
        Interest_Rate__c ir = TestUtils.createNewInterestRate(irs.Id, System.today(), 1);
        
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct('Test Loan Product');
        lp.Interest_Rate_Source__c = 'Variable Interest';
        lp.Interest_Reference_Rate__c = irs.Id;
        lp.Interest_Rate_Review_Frequency__c = 'Monthly';
        lp.CBO_Default_Variable_Interest_Spread__c = true;

        insert new List<SObject>{ir, lp};
        
        // create a new loan
        Investment__c i = TestUtils.createNewLoan(System.today(), System.today().addMonths(1));
        i.Loan_Product__c = lp.Id;
        i.Disbursement_Method__c = 'Full disbursement at start';
        i.Variable_Interest_Spread__c = 5;
        i.Interest_Rate__c = null;

        Map<String, String> result = OverriddenLoanPageController.generateSchedule(JSON.serialize(i), true);
        System.assert(!result.containsKey('error'));
        System.assert(result.containsKey('schedules'));
        System.assert(result.containsKey('variableInterest'));
        List<Repayment_Schedule__c> rsToPreview = (List<Repayment_Schedule__c>) JSON.deserialize(result.get('schedules'), List<Repayment_Schedule__c>.class);
        System.assertEquals(rsToPreview.size(), i.Number_of_Instalments__c);
    }

    @isTest static void test_save_and_generate_schedule() {
        // create a new interest rate source
        Interest_Rate_Source__c irs = new Interest_Rate_Source__c(Name = 'Test Interest Rate Source');
        insert irs;

        // create interest rates
        Interest_Rate__c ir = TestUtils.createNewInterestRate(irs.Id, System.today(), 1);
        
        // create a new loan product
        Loan_Product__c lp = TestUtils.createNewLoanProduct('Test Loan Product');
        lp.Interest_Rate_Source__c = 'Variable Interest';
        lp.Interest_Reference_Rate__c = irs.Id;
        lp.Interest_Rate_Review_Frequency__c = 'Monthly';
        lp.CBO_Default_Variable_Interest_Spread__c = true;

        insert new List<SObject>{ir, lp};
        
        // create a new loan
        Investment__c i = TestUtils.createNewLoan(System.today(), System.today().addMonths(1));
        i.Loan_Product__c = lp.Id;
        i.Disbursement_Method__c = 'Full disbursement at start';
        i.Variable_Interest_Spread__c = 5;
        i.Interest_Rate__c = null;

        List<Investment__c> loans = [
            SELECT Id, 
            (
                SELECT Id
                FROM Repayment_Schedules__r
            )
            FROM Investment__c 
        ];
        System.assertEquals(loans.size(), 0);

        Map<String, String> result = OverriddenLoanPageController.generateSchedule(JSON.serialize(i), false);
        System.assert(!result.containsKey('error'));
        System.assert(result.containsKey('success'));

        List<Investment__c> loans2 = [
            SELECT Id, 
            (
                SELECT Id
                FROM Repayment_Schedules__r
            )
            FROM Investment__c 
        ];
        System.assertEquals(loans2.size(), 1);
        System.assertEquals(loans2[0].Repayment_Schedules__r.size(), i.Number_of_Instalments__c);
    }

    @isTest static void test_getFieldSets() {
        
        Map<String, Schema.FieldSet> fsMap = Schema.SObjectType.Investment__c.fieldSets.getMap();
        String resultNew = OverriddenLoanPageController.getFieldSets('new');
        String resultEdit = OverriddenLoanPageController.getFieldSets('edit');
        String resultView = OverriddenLoanPageController.getFieldSets('view');

        Integer numberOfTop = 0;
        Integer numberOfBottom = 0;
        for (String key : fsMap.keySet()) {
            if (key.containsIgnoreCase('loan_top')) {
                numberOfTop++;
                continue;
            }
            if (key.containsIgnoreCase('loan_bottom')) {
                numberOfBottom++;
            }
        }
        
        Map<String, List<Utility.FieldSetWrapper>> resultNewMap = (Map<String, List<Utility.FieldSetWrapper>>) JSON.deserialize(resultNew, Map<String, List<Utility.FieldSetWrapper>>.class);
        if (!resultNewMap.isEmpty()) {
            if (resultNewMap.containsKey('top')) System.assertEquals(resultNewMap.get('top').size(), numberOfTop);
            if (resultNewMap.containsKey('bottom')) System.assertEquals(resultNewMap.get('bottom').size(), numberOfBottom);
        } else {
            System.assertEquals(resultNewMap.size(), 0);
        }

        Map<String, List<Utility.FieldSetWrapper>> resultEditMap = (Map<String, List<Utility.FieldSetWrapper>>) JSON.deserialize(resultEdit, Map<String, List<Utility.FieldSetWrapper>>.class);
        if (!resultEditMap.isEmpty()) {
            if (resultEditMap.containsKey('top')) System.assertEquals(resultEditMap.get('top').size(), numberOfTop);
            if (resultEditMap.containsKey('bottom')) System.assertEquals(resultEditMap.get('bottom').size(), numberOfBottom);
        } else {
            System.assertEquals(resultEditMap.size(), 0);
        }

        Map<String, List<Utility.FieldSetWrapper>> resultViewMap = (Map<String, List<Utility.FieldSetWrapper>>) JSON.deserialize(resultView, Map<String, List<Utility.FieldSetWrapper>>.class);
        if (!resultViewMap.isEmpty()) {
            if (resultViewMap.containsKey('top')) System.assertEquals(resultViewMap.get('top').size(), numberOfTop);
            if (resultViewMap.containsKey('bottom')) System.assertEquals(resultViewMap.get('bottom').size(), numberOfBottom);
        } else {
            System.assertEquals(resultViewMap.size(), 0);
        }
    }

    @isTest static void test_getLoanProductSettings() { 
        String dayCountConvention = 'Actual/365';
        Decimal repaymentFrequency = 1;
        
        Loan_Product__c lp = TestUtils.createNewLoanProduct();
        lp.Day_Count_Convention__c = dayCountConvention;
        lp.Repayment_Frequency__c = repaymentFrequency;
        insert lp;
        
        String stringResult = OverriddenLoanPageController.getLoanProductSettings(lp.Id, null);
        Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(stringResult);
        
        System.assertEquals(dayCountConvention, (String)result.get('sfims__Day_Count_Convention__c'));
        System.assertEquals(repaymentFrequency, (Decimal)result.get('sfims__Repayment_Frequency__c'));

        Investment__c i = TestUtils.createNewLoan();
        i.Loan_Product__c = lp.Id;
        insert i;
        
        String stringResult2 = OverriddenLoanPageController.getLoanProductSettings(null, i.Id);
        Map<String, Object> result2 = (Map<String, Object>) JSON.deserializeUntyped(stringResult2);
        
        System.assertEquals(dayCountConvention, (String)result2.get('sfims__Day_Count_Convention__c'));
        System.assertEquals(repaymentFrequency, (Decimal)result2.get('sfims__Repayment_Frequency__c'));

    }

}