force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Rate__c/fields/Interest_Rate_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Source__c</fullName>
    <label>Interest Rate Source</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Interest Rates</relationshipLabel>
    <relationshipName>Interest_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interest_Rate_Source__c/Interest_Rate_Source__c.object-meta.xml
<CustomObject>
    <label>Interest Rate Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Rate Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Loan Product which this Loan is based on.</description>
    <inlineHelpText>The Loan Product which this Loan is based on.</inlineHelpText>
    <label>Loan Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Loan_Product__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Rate_Source__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Source__c</fullName>
    <label>Interest Rate Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Interest</fullName>
            </value>
            <value>
                <fullName>Variable Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Reference_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Reference_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is required if ‘Variable Interest’ is selected</description>
    <label>Interest Reference Rate</label>
    <referenceTo>Interest_Rate_Source__c</referenceTo>
    <relationshipLabel>Loan Products</relationshipLabel>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE then this is a migration record</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Validation_Settings__c/Validation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Validation Settings</label>
</CustomObject>

force-app/main/default/classes/OverriddenLoanPageController.cls
public with sharing class OverriddenLoanPageController {

    public class CommonException extends Exception {
    }

    @AuraEnabled
    public static Boolean checkDisableValidationRules() {
        try {
            Validation_Settings__c vs = Validation_Settings__c.getInstance();
            return vs.sfims__Disable_Validation_Rules_on_Investment__c;
        } catch (Exception err) {
            throw new CommonException(err.getMessage());
        }
    }

    @AuraEnabled
    public static Map<String, String> generateSchedule(String theLoanString, Boolean preview) {
        System.debug(theLoanString);
        Investment__c theLoan = (Investment__c)JSON.deserialize(theLoanString, Investment__c.class);
        Map<String, String> returnMap = new Map<String, String>();
        Savepoint sp = Database.setSavepoint();
        try {
            System.debug(theLoan.Interest_Rate__c);
            upsert theLoan;
            if (preview) {
                return OverriddenLoanPageController.generatePreview(sp, theLoan.Id);
            } else {
                return OverriddenLoanPageController.saveRepaymentSchedules(sp, theLoan.Id);
            }
        } catch (DmlException e) {
            throw new AuraHandledException(e.getDmlMessage(0));
        }
    }

    public static Map<String, String> generatePreview(Savepoint sp, String loanId) {
        Map<String, String> returnMap = new Map<String, String>();
        try {
            returnMap.put('schedules', JSON.serialize(LoanScheduler.generateScheduleById(loanId)));
            Investment__c theLoan = [
                SELECT Loan_Product__c, Loan_Product__r.Interest_Rate_Source__c, Loan_Product__r.Interest_Reference_Rate__c
                FROM Investment__c 
                WHERE Id = :loanId
            ];
            if (theLoan.Loan_Product__c != null && theLoan.Loan_Product__r.Interest_Rate_Source__c == 'Variable Interest'
                && theLoan.Loan_Product__r.Interest_Reference_Rate__c != null) 
            {    
                returnMap.put('variableInterest', System.Label.sfims.warning_message_1);
            }
            Database.rollback(sp);
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug(e.getTypeName());
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            returnMap.put('error', System.Label.sfims.part_of_error_message_3 + ': ' + e.getMessage());
        }
        return returnMap;
    }

    public static Map<String, String> saveRepaymentSchedules(Savepoint sp, String loanId) {
        Map<String, String> returnMap = new Map<String, String>();
        try {
            delete [SELECT Id FROM Repayment_Schedule__c WHERE Loan__c = :loanId AND Migration__c = false];
            LoanScheduler.recalculateLoanSchedule(loanId);
            returnMap.put('success', loanId);
        } catch (DmlException e) {
            Database.rollback(sp);       
            returnMap.put('error', System.Label.sfims.part_of_error_message_4 + ': ' + e.getDmlMessage(0));
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug(e.getTypeName());
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            returnMap.put('error', System.Label.sfims.part_of_error_message_3 + ': ' + e.getMessage());
        }
        return returnMap;
    }

    // @AuraEnabled
    // public static Map<String, SObject> getUserProfileInfo() {
    //     try {
    //         Map<String, SObject> response = new Map<String, SObject>();
    //         response.put('user', OverriddenLoanProductPageController.getUserInfo());
    //         response.put('profile', OverriddenLoanProductPageController.getProfileInfo());
    //         return response;
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

    @AuraEnabled
    public static String getFieldSets(String mode) {
        return JSON.serialize(OverriddenLoanProductPageController.formFieldMap(Schema.SObjectType.Investment__c.fieldSets.getMap(), 'loan', mode));
    }

    @AuraEnabled
    public static String getLoanProductSettings(String loanProductId, String loanId) {
        if (loanProductId == null) {
            Investment__c theLoan = [
                SELECT Loan_Product__c
                FROM Investment__c
                WHERE Id = :loanId
            ];
            loanProductId = theLoan.Loan_Product__c;
        }

        Map<String, Schema.SObjectField> fieldMap = Schema.SObjectType.Loan_Product__c.fields.getMap();
        List<Loan_Product__c> lps = Database.query('SELECT ' + String.join(new List<String>(fieldMap.keySet()), ',') + ' FROM Loan_Product__c WHERE Id =: loanProductId');
        if (!lps.isEmpty()) {
            Loan_Product__c lp = lps[0];
            Map<String, Object> settingsMap = new Map<String, Object>();
            for (Schema.SObjectField fieldAPIName : fieldMap.values()) {
                System.debug(fieldAPIName);
                System.debug(lp.get(fieldAPIName));

                settingsMap.put(String.valueOf(fieldAPIName), lp.get(fieldAPIName));

            }
            for (String key : settingsMap.keySet()) {
                System.debug(key);
                System.debug(settingsMap.get(key));
            }
            return JSON.serialize(settingsMap);
        } else {
            throw new AuraHandledException(System.Label.sfims.error_message_65);
        }
    }

}