force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Grace</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Defaulted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Total_Expected__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected__c</fullName>
    <formula>Fees_Expected__c + Interest_Expected0__c + Late_Repayment_Fees_Expected0__c + Principal_Expected__c + Interest_Bonus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LoanScheduleEditorController.cls
public without sharing class LoanScheduleEditorController {
    public class CustomException extends Exception {
    }

    @AuraEnabled
    public static Map<String, Map<String, Boolean>> getButtonAccess(Id loanId, Boolean isDebugLog) {
        return new Map<String, Map<String, Boolean>>{
            'customPermissions' => new Map<String, Boolean>{
                'Disburse' => FeatureManagement.checkPermission('Disburse_Loans'),
                'EditSchedule' => FeatureManagement.checkPermission('Edit_Repayment_Schedule'),
                'Reschedule' => FeatureManagement.checkPermission('Reschedule_Loans'),
                'EarlyRepayment' => FeatureManagement.checkPermission('Pay_Off_Loans'),
                'WriteOff' => FeatureManagement.checkPermission('Write_Off_Loans')
            },
            'visible' => new Map<String, Boolean>{
                'EditSchedule' => (getSchedules(loanId, isDebugLog).size() > 0)
            }
        };
    }

    @AuraEnabled
    public static List<Repayment_Schedule__c> getSchedules(Id loanId, Boolean isDebugLog) {
        try {
            return [
                SELECT Name, Due_Date__c, Status__c, Total_Expected__c, Principal_Expected__c, sfims__Interest_Expected_Standard_Loan__c, Interest_Rate__c, Fees_Expected__c
                FROM Repayment_Schedule__c
                WHERE sfims__Loan__c = :loanId
                ORDER BY Name
            ];
        } catch (Exception err) {
            throw new CustomException(err.getMessage());
        }
    }
}