force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>Used for tracking the status and value of an investment. Investments can be loans, grants, equity, etc.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Day_Count_Convention__c.field-meta.xml
<CustomField>
    <fullName>Day_Count_Convention__c</fullName>
    <description>30/360 
This is a method that calculates interest based on assumed equal months (1/12th). 

Actual/365 
Calculate interest fees based on the number of days in the actual period. So if payments are monthly we charge between 28 and 31 days of interest, depending on the number of days in the month. 

Actual/365L 
Same as Actual/365 but for Leap years 366 days are used and not 365.</description>
    <label>Day Count Convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
                <default>true</default>
                <label>30/360</label>
            </value>
            <value>
                <fullName>Actual/365</fullName>
            </value>
            <value>
                <fullName>Actual/365L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Date__c</fullName>
    <description>The date on which the Loan is (expected to be) disbursed. From this day on, interest will be charged (if applicable)</description>
    <inlineHelpText>The date on which the Loan is (expected to be) disbursed. From this day on, interest will be charged (if applicable)</inlineHelpText>
    <label>Disbursement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <summarizedField>Repayment_Schedule__c.Fees_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/First_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Repayment_Date__c</fullName>
    <description>The date on which the first repayment for the loan is due. The rest of the loan schedule will also be based on this date.</description>
    <inlineHelpText>The date on which the first repayment for the loan is due. The rest of the loan schedule will also be based on this date.</inlineHelpText>
    <label>First Repayment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Flat_Amount__c.field-meta.xml
<CustomField>
    <fullName>Flat_Amount__c</fullName>
    <label>Flat Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Grace_Period_Type__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period_Type__c</fullName>
    <label>Grace Period Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <label>No Grace</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <label>Pay Admin Fees Only</label>
            </value>
            <value>
                <fullName>Interest</fullName>
                <label>Pay Interest Only</label>
            </value>
            <value>
                <fullName>Interest Rollup</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
                <label>Full Grace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Monitoring_Fee_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Fee_Percentage__c</fullName>
    <label>Monitoring Fee Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Grace_Periods__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Grace_Periods__c</fullName>
    <label>Number of Grace Periods</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Number_of_Instalments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Instalments__c</fullName>
    <label>Number of Instalments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <summarizedField>Repayment_Schedule__c.Principal_Expected__c</summarizedField>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Repayment_Frequency_Unit__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency_Unit__c</fullName>
    <label>Repayment Frequency Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>% of Disbursement Amount</fullName>
            </value>
            <value>
                <fullName>Flat Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Setup_Fee_Charging_Method__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Charging_Method__c</fullName>
    <label>Setup Fee Charging Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Setup Fee</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (manual)</fullName>
            </value>
            <value>
                <fullName>Paid Up Front (scheduled)</fullName>
            </value>
            <value>
                <fullName>Capitalized</fullName>
            </value>
            <value>
                <fullName>Deducted From Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <description>This is a single scheduled repayment for a loan-type of investment</description>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Repayment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Repayment_Schedule__c/fields/Fees_Expected__c.field-meta.xml
<CustomField>
    <fullName>Fees_Expected__c</fullName>
    <label>Fees Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Expected0__c.field-meta.xml
<CustomField>
    <fullName>Interest_Expected0__c</fullName>
    <formula>IF(Loan__r.Open_Ended_Loan__c, Interest_Expected_Open_Ended_Loan__c, Interest_Expected_Standard_Loan__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</description>
    <inlineHelpText>Interest Rate for this period. E.g. for capturing interest rate changes during a schedule.</inlineHelpText>
    <label>Interest Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The Loan (Investment) to which this Repayment Schedule record applies</description>
    <inlineHelpText>The Loan (Investment) to which this Repayment Schedule record applies</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Investment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Expected__c.field-meta.xml
<CustomField>
    <fullName>Principal_Expected__c</fullName>
    <label>Principal Expected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestLoanScheduler.cls
@isTest
private class TestLoanScheduler {

    @isTest static void test_loan_scheduling() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Months';
        i.Number_of_Grace_Periods__c = 2;
        i.Grace_Period_Type__c = 'Interest';
        i.Amount__c = 100;
        i.Interest_Rate__c = 5;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);          
        insert i;

        List<Repayment_Schedule__c> scheduleToInsert = LoanScheduler.generateScheduleById(i.Id);
        
        System.assertEquals(12,scheduleToInsert.size());

        // test the same with unauthorized user
        User newUser = TestUtils.ensureRestrictedUser();
        System.runAs(newUser){
            List<Repayment_Schedule__c> scheduleToInsert2;
            try{
                scheduleToInsert2 = LoanScheduler.generateScheduleById(i.Id);
                System.assert(false,'Expected an exception (unauthorized user');
            } catch (AuraHandledException e){
                // expected
                System.assertEquals(null, scheduleToInsert2);
            }
        }        
    }

    @isTest static void test_loan_scheduling_full_grace() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Years';
        i.Number_of_Grace_Periods__c = 2;
        i.Grace_Period_Type__c = 'Full';
        i.Amount__c = 100;
        i.Interest_Rate__c = null;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);          
        insert i;

        List<Repayment_Schedule__c> scheduleToInsert = LoanScheduler.generateScheduleById(i.Id);
        
        System.assertEquals(12,scheduleToInsert.size());
      
    }

    @isTest static void test_standard_loan_recalculation_30_360() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Months';
        i.Number_of_Grace_Periods__c = 2;
        i.Grace_Period_Type__c = 'Interest';
        i.Amount__c = 100;
        i.Interest_Rate__c = 5;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);          
        insert i;

        LoanScheduler.recalculateLoanSchedule(i.Id);
        
        System.assertEquals(12,[select id from repayment_schedule__c where loan__c = :i.Id].size());

        // test the same with unauthorized user
        User newUser = TestUtils.ensureRestrictedUser();
        System.runAs(newUser){
            try{
                LoanScheduler.recalculateLoanSchedule(i.Id);
                System.assert(false,'Expected an exception (unauthorized user');
            } catch (AuraHandledException e){
                // expected
                System.assertEquals(true,true);
            }
        }          
    }

    @isTest static void test_create_a_repayment_schedule_for_a_loan_with_the_paid_up_front_type_of_the_setup_see_charging_method() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Months';
        i.Number_of_Grace_Periods__c = 2;
        i.Grace_Period_Type__c = 'Interest';
        i.Amount__c = 100;
        i.Interest_Rate__c = 0.05;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);
        i.Setup_Fee_Charging_Method__c = 'Paid Up Front (scheduled)'; 
        i.Setup_Fee__c = 'Flat Amount';
        i.Flat_Amount__c = 5;         
        insert i;

        LoanScheduler.recalculateLoanSchedule(i.Id);

        List<Repayment_Schedule__c> result = [
            SELECT Id, Fees_Expected__c, Interest_Expected0__c, Principal_Expected__c
            FROM Repayment_Schedule__c 
            WHERE Loan__c = :i.Id AND Due_Date__c =: i.Disbursement_Date__c
        ];
        System.assertEquals(1, result.size());
        System.assertEquals(i.Flat_Amount__c, result[0].Fees_Expected__c);
        System.assertEquals(0, result[0].Principal_Expected__c);
        System.assertEquals(0, result[0].Interest_Expected0__c);
        
    }

    @isTest static void test_open_ended_loan_recalculation() {
        Investment__c i = TestUtils.createOpenEndedLoan();        
        insert i;

        LoanScheduler.recalculateLoanSchedule(i.Id);
        
        System.assertEquals(1,[SELECT Id FROM Repayment_Schedule__c WHERE Loan__c = :i.Id].size());

        // test the same with unauthorized user
        User newUser = TestUtils.ensureRestrictedUser();
        System.runAs(newUser){
            try{
                LoanScheduler.recalculateLoanSchedule(i.Id);
                System.assert(false,'Expected an exception (unauthorized user');
            } catch (AuraHandledException e){
                // expected
                System.assertEquals(true,true);
            }
        }          
    }

    @isTest static void test_standard_loan_recalculation_actual_365() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Months';
        i.Number_of_Grace_Periods__c = 2;
        i.Grace_Period_Type__c = 'Interest';
        i.Amount__c = 100;
        i.Interest_Rate__c = 5;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);
        i.Day_Count_Convention__c = 'Actual/365';         
        insert i;

        LoanScheduler.recalculateLoanSchedule(i.Id);
        
        System.assertEquals(12,[select id from repayment_schedule__c where loan__c = :i.Id].size());

        // test the same with unauthorized user
        User newUser = TestUtils.ensureRestrictedUser();
        System.runAs(newUser){
            try{
                LoanScheduler.recalculateLoanSchedule(i.Id);
                System.assert(false,'Expected an exception (unauthorized user');
            } catch (AuraHandledException e){
                // expected
                System.assertEquals(true,true);
            }
        }          
    }

    @isTest static void test_standard_loan_recalculation_actual_365l() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Months';
        i.Number_of_Grace_Periods__c = 2;
        i.Grace_Period_Type__c = 'Interest';
        i.Amount__c = 100;
        i.Interest_Rate__c = 5;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);
        i.Day_Count_Convention__c = 'Actual/365L';          
        insert i;

        LoanScheduler.recalculateLoanSchedule(i.Id);
        
        System.assertEquals(12,[select id from repayment_schedule__c where loan__c = :i.Id].size());

        // test the same with unauthorized user
        User newUser = TestUtils.ensureRestrictedUser();
        System.runAs(newUser){
            try{
                LoanScheduler.recalculateLoanSchedule(i.Id);
                System.assert(false,'Expected an exception (unauthorized user');
            } catch (AuraHandledException e){
                // expected
                System.assertEquals(true,true);
            }
        }          
    }

    @isTest static void test_monitoring_fee_calculations() {
        Investment__c i = TestUtils.createNewLoan();
        i.Number_of_Instalments__c = 12;
        i.Repayment_Frequency__c = 1;
        i.Repayment_Frequency_Unit__c = 'Months';
        i.Grace_Period_Type__c = 'None';
        i.Amount__c = 100;
        i.Interest_Rate__c = 6;
        i.Monitoring_Fee_Percentage__c = 3;
        i.Disbursement_Date__c = System.today();
        i.First_Repayment_Date__c = System.today().addMonths(1);          
        insert i;

        List<Repayment_Schedule__c> scheduleToInsert = LoanScheduler.generateScheduleById(i.Id);
        
        System.assertEquals(i.Number_of_Instalments__c, scheduleToInsert.size());
        for (Repayment_Schedule__c rs : scheduleToInsert) {
            System.assertEquals(rs.Monitoring_Fee_Percentage__c, i.Monitoring_Fee_Percentage__c);
        }

        // test the same with unauthorized user
        User newUser = TestUtils.ensureRestrictedUser();
        System.runAs(newUser){
            List<Repayment_Schedule__c> scheduleToInsert2;
            try{
                scheduleToInsert2 = LoanScheduler.generateScheduleById(i.Id);
                System.assert(false,'Expected an exception (unauthorized user');
            } catch (AuraHandledException e){
                // expected
                System.assertEquals(null,scheduleToInsert2);
            }
        }        
    }

}