force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>A template for a Loan that specifies the specifications and constraints that are then applied to the Loans (Investments) associated with the Loan Products. Each Loan has a required Loan Product.</description>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Day_Count_Convention__c.field-meta.xml
<CustomField>
    <fullName>Day_Count_Convention__c</fullName>
    <description>30/360 
This is a method that calculates interest based on assumed equal months (1/12th). 

Actual/365 
Calculate interest fees based on the number of days in the actual period. So if payments are monthly we charge between 28 and 31 days of interest, depending on the number of days in the month. 

Actual/365L 
Same as Actual/365 but for Leap years 366 days are used and not 365.</description>
    <label>Day Count Convention</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30/360</fullName>
            </value>
            <value>
                <fullName>Actual/365</fullName>
            </value>
            <value>
                <fullName>Actual/365L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Settings__c/Loan_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Settings</label>
</CustomObject>

force-app/main/default/objects/Loan_Settings__c/fields/Day_Count_Convention__c.field-meta.xml
<CustomField>
    <fullName>Day_Count_Convention__c</fullName>
    <description>30/360
This is a method that calculates interest based on assumed equal months (1/12th).

Actual/365
Calculate interest fees based on the number of days in the actual period. So if payments are monthly we charge between 28 and 31 days of interest, depending on the number of days in the month.

Actual/365L
Same as Actual/365 but for Leap years 366 days are used and not 365.</description>
    <inlineHelpText>- 30/360
- Actual/365
- Actual/365L</inlineHelpText>
    <label>Day Count Convention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Settings__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestOverriddenLoanProductPageController.cls
@isTest
private class TestOverriddenLoanProductPageController {
    @isTest static void test_getFieldSets() {
        
        Map<String, Schema.FieldSet> fsMap = Schema.SObjectType.Loan_Product__c.fieldSets.getMap();
        String resultNew = OverriddenLoanProductPageController.getFieldSets('new');
        String resultEdit = OverriddenLoanProductPageController.getFieldSets('edit');
        
        Integer numberOfTop = 0;
        Integer numberOfBottom = 0;
        for (String key : fsMap.keySet()) {
            if (key.containsIgnoreCase('loan_product_top')) {
                numberOfTop++;
                continue;
            }
            if (key.containsIgnoreCase('loan_product_bottom')) {
                numberOfBottom++;
            }
        }
        
        Map<String, List<Utility.FieldSetWrapper>> resultNewMap = (Map<String, List<Utility.FieldSetWrapper>>) JSON.deserialize(resultNew, Map<String, List<Utility.FieldSetWrapper>>.class);
        if (!resultNewMap.isEmpty()) {
            if (resultNewMap.containsKey('top')) System.assertEquals(resultNewMap.get('top').size(), numberOfTop);
            if (resultNewMap.containsKey('bottom')) System.assertEquals(resultNewMap.get('bottom').size(), numberOfBottom);
        } else {
            System.assertEquals(resultNewMap.size(), 0);
        }

        Map<String, List<Utility.FieldSetWrapper>> resultEditMap = (Map<String, List<Utility.FieldSetWrapper>>) JSON.deserialize(resultEdit, Map<String, List<Utility.FieldSetWrapper>>.class);
        if (!resultEditMap.isEmpty()) {
            if (resultEditMap.containsKey('top')) System.assertEquals(resultEditMap.get('top').size(), numberOfTop);
            if (resultEditMap.containsKey('bottom')) System.assertEquals(resultEditMap.get('bottom').size(), numberOfBottom);
        } else {
            System.assertEquals(resultEditMap.size(), 0);
        }
    }

    @isTest static void test_getOrgSettings() {
        String dayCountConvention = 'Actual/365';
        Decimal repaymentFrequency = 1;
        
        Loan_Settings__c settings = Loan_Settings__c.getOrgDefaults();
        settings.Day_Count_Convention__c = dayCountConvention;
        settings.Repayment_Frequency__c = repaymentFrequency;
        upsert settings Loan_Settings__c.Id;

        Map<String, Object> result = OverriddenLoanProductPageController.getOrgSettings();
        
        System.assertEquals(dayCountConvention, (String)result.get('sfims__Day_Count_Convention__c'));
        System.assertEquals(repaymentFrequency, (Decimal)result.get('sfims__Repayment_Frequency__c'));
    }

    @isTest static void test_getAccessLoanProduct() {
        System.assertNotEquals(null, OverriddenLoanProductPageController.getAccessLoanProduct());
    }

    // @isTest static void test_getProfileInfo() {
    //     System.assertNotEquals(null, OverriddenLoanProductPageController.getProfileInfo());
    // }


}