force-app/main/default/objects/Task_List_Template__c/Task_List_Template__c.object-meta.xml
<CustomObject>
    <label>Task List Template</label>
    <nameField>
        <displayFormat>TLT-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Object Name with namespace</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Status_Field__c.field-meta.xml
<CustomField>
    <fullName>Object_Status_Field__c</fullName>
    <inlineHelpText>Object field name with namespace</inlineHelpText>
    <label>Object Status Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestTaskListTemplateTrigger.cls
/** Action list functionality * @author Alexey Eliseev * @date 8/28/19 **/
@IsTest
private with sharing class TestTaskListTemplateTrigger {
    @IsTest static void test_TaskListTemplateTrigger() {
        Test.startTest();
        Boolean isException = false;
        try {
            insert new Task_List_Template__c(Object_Name__c = 'Account', Object_Status_Field__c = 'Name1');
        } catch (Exception err) {
            System.assert(err.getMessage().length() > 0, 'Invalid exception message');
            isException = true;
        }
        System.assertEquals(true, isException, 'Invalid exception message');

        isException = false;
        try {
            insert new Task_List_Template__c(Object_Name__c = 'Account1', Object_Status_Field__c = 'Name');
        } catch (Exception err) {
            isException = true;
            System.assert(err.getMessage().length() > 0, 'Invalid exception message');
        }
        System.assertEquals(true, isException, 'Invalid exception message');

        isException = false;
        try {
            insert new Task_List_Template__c(Object_Name__c = 'Account');
        } catch (Exception err) {
            isException = true;
            System.assert(err.getMessage().length() > 0, 'Invalid exception message');
        }
        System.assertEquals(true, isException, 'Invalid exception message');
        Test.stopTest();
    }
}