force-app/main/default/objects/Task_List_Template__c/Task_List_Template__c.object-meta.xml
<CustomObject>
    <label>Task List Template</label>
    <nameField>
        <displayFormat>TLT-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <inlineHelpText>Object Name with namespace</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template__c/fields/Object_Status_Field__c.field-meta.xml
<CustomField>
    <fullName>Object_Status_Field__c</fullName>
    <inlineHelpText>Object field name with namespace</inlineHelpText>
    <label>Object Status Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/Task_List_Template_Item__c.object-meta.xml
<CustomObject>
    <label>Task List Template Item</label>
    <nameField>
        <displayFormat>TLTI-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task List Template Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approval Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Assignee_Field__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Field__c</fullName>
    <inlineHelpText>API field name with user</inlineHelpText>
    <label>Assignee Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Assignee_Type__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Type__c</fullName>
    <label>Assignee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record Owner</fullName>
                <default>true</default>
                <label>Record Owner</label>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Related Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_List_Template_Item__c/fields/Task_List_Template__c.field-meta.xml
<CustomField>
    <fullName>Task_List_Template__c</fullName>
    <label>Task List Template</label>
    <referenceTo>Task_List_Template__c</referenceTo>
    <relationshipLabel>Task List Template Items</relationshipLabel>
    <relationshipName>Task_List_Template_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestTaskListTemplateItemTrigger.cls
/** Action list functionality * @author Alexey Eliseev * @date 8/28/19 **/
@IsTest
private with sharing class TestTaskListTemplateItemTrigger {
    @IsTest static void test_TaskListTemplateItemTrigger() {
        Test.startTest();
        try {
            insert new Task_List_Template_Item__c();
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.part_of_error_message_26 + ': Subject, Task List Template.'), 'Invalid exception message');
        }
        Task_List_Template__c taskListTemplate1 = new Task_List_Template__c(Object_Name__c = 'sfims__Application__c', Object_Status_Field__c = 'Name');
        insert taskListTemplate1;
        try {
            insert new Task_List_Template_Item__c(Subject__c = 'Subject', Task_List_Template__c = taskListTemplate1.Id);
        } catch (Exception err) {
            System.assertEquals(false, true, 'Invalid exception');
        }
        // Related Field is empty
        try {
            insert new Task_List_Template_Item__c(Subject__c = 'Subject', Assignee_Type__c = 'Related Field', Task_List_Template__c = taskListTemplate1.Id);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.part_of_error_message_26 + ': Assignee Field.'), 'Invalid exception message');
        }
        // Not exists related field
        try {
            insert new Task_List_Template_Item__c(Subject__c = 'Subject', Assignee_Type__c = 'Related Field', Assignee_Field__c = 'Test', Task_List_Template__c = taskListTemplate1.Id);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.part_of_error_message_1 + ' "Test" ' + System.Label.sfims.part_of_error_message_28 + ' ' + System.Label.sfims.part_of_error_message_20 + ' "sfims__Application__c" ' + System.Label.sfims.part_of_error_message_25 + '.'), 'Invalid exception message');
        }
        // Approval_Required__c = true
        try {
            insert new Task_List_Template_Item__c(Subject__c = 'Subject', Assignee_Type__c = 'Related Field', Task_List_Template__c = taskListTemplate1.Id, Approval_Required__c = true);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.part_of_error_message_26 + ': Assignee Field, Flow Name. ' + System.Label.sfims.part_of_error_message_27), 'Invalid exception message');
        }
        // Assignee_Type__c = User
        try {
            insert new Task_List_Template_Item__c(Subject__c = 'Subject', Assignee_Type__c = 'User', Task_List_Template__c = taskListTemplate1.Id);
            System.assertEquals(false, true, 'Invalid exception');
        } catch (Exception err) {
            System.assert(err.getMessage().contains(System.Label.sfims.part_of_error_message_26 + ': Assignee User.'), 'Invalid exception message');
        }

        Test.stopTest();
    }
}